<?php

declare(strict_types=1);

use PortLibs\Pandoc\HtmlNativeAstComparisonHarness;

$fixtureRoot = static fn (): string => dirname(__DIR__) . '/fixtures';

return [
    'skips html native ast comparison when source directory is absent' => static function (TestRunner $t): void {
        $missing = sys_get_temp_dir() . '/missing-html-native-' . bin2hex(random_bytes(4));
        $report = (new HtmlNativeAstComparisonHarness())->run($missing);
        $text = (new HtmlNativeAstComparisonHarness())->formatReport($report);

        $t->same('skipped', $report['status']);
        $t->same(true, $report['skipped']);
        $t->same('html-native-fixture-directory-missing', $report['reason']);
        $t->same(0, $report['comparedPairCount']);
        $t->same('not-evaluated-source-directory-unavailable', $report['astParityStatus']);
        $t->contains('Pandoc HTML/native AST comparison: skipped', $text);
    },

    'checked-in html fixtures match native ast shape' => static function (TestRunner $t) use ($fixtureRoot): void {
        $root = $fixtureRoot();
        $anchorImageHtml = $root . '/upstream-html-anchor-image-attrs.html';
        $anchorImageNative = $root . '/upstream-html-anchor-image-attrs.native';
        $baseAbsoluteImageHtml = $root . '/upstream-html-base-absolute-image.html';
        $baseAbsoluteImageNative = $root . '/upstream-html-base-absolute-image.native';
        $baseMediaHtml = $root . '/upstream-html-base-media.html';
        $baseMediaNative = $root . '/upstream-html-base-media.native';
        $bdoDirectionHtml = $root . '/upstream-html-bdo-direction.html';
        $bdoDirectionNative = $root . '/upstream-html-bdo-direction.native';
        $blockquoteHtml = $root . '/upstream-html-blockquote.html';
        $blockquoteNative = $root . '/upstream-html-blockquote.native';
        $rowHeaderHtml = $root . '/upstream-native-html-row-header-table.html';
        $rowHeaderNative = $root . '/upstream-native-html-row-header-table.native';
        $noterefHtml = $root . '/upstream-html-doc-noteref-footnotes.html';
        $noterefNative = $root . '/upstream-html-doc-noteref-footnotes.native';
        $tablePlacementHtml = $root . '/upstream-html-doc-noteref-table-placement.html';
        $tablePlacementNative = $root . '/upstream-html-doc-noteref-table-placement.native';
        $figureCaptionHtml = $root . '/upstream-html-figure-caption.html';
        $figureCaptionNative = $root . '/upstream-html-figure-caption.native';
        $lineBlockHtml = $root . '/upstream-html-line-block.html';
        $lineBlockNative = $root . '/upstream-html-line-block.native';
        $preCodeHtml = $root . '/upstream-html-pre-code-attributes.html';
        $preCodeNative = $root . '/upstream-html-pre-code-attributes.native';
        $preCodeBreakHtml = $root . '/upstream-html-pre-code-br.html';
        $preCodeBreakNative = $root . '/upstream-html-pre-code-br.native';
        $rawDisabledHtml = $root . '/upstream-html-raw-disabled-skip.html';
        $rawDisabledNative = $root . '/upstream-html-raw-disabled-skip.native';
        $inlineCodeHtml = $root . '/upstream-html-inline-code-aliases.html';
        $inlineCodeNative = $root . '/upstream-html-inline-code-aliases.native';
        $inlineQuoteCiteBaseHtml = $root . '/upstream-html-inline-quote-cite-base.html';
        $inlineQuoteCiteBaseNative = $root . '/upstream-html-inline-quote-cite-base.native';
        $langMetadataHtml = $root . '/upstream-html-lang-metadata.html';
        $langMetadataNative = $root . '/upstream-html-lang-metadata.native';
        $xmlLangMetadataHtml = $root . '/upstream-html-xml-lang-metadata.html';
        $xmlLangMetadataNative = $root . '/upstream-html-xml-lang-metadata.native';
        $listItemIdHtml = $root . '/upstream-html-list-item-id.html';
        $listItemIdNative = $root . '/upstream-html-list-item-id.native';
        $headerNativeDivsHtml = $root . '/upstream-html-header-native-divs.html';
        $headerNativeDivsNative = $root . '/upstream-html-header-native-divs.native';
        $iframeLocalResourceHtml = $root . '/upstream-html-iframe-local-resource.html';
        $iframeLocalResourceNative = $root . '/upstream-html-iframe-local-resource.native';
        $mainNativeDivsHtml = $root . '/upstream-html-main-native-divs.html';
        $mainNativeDivsNative = $root . '/upstream-html-main-native-divs.native';
        $sectionAsideNativeDivsHtml = $root . '/upstream-html-section-aside-native-divs.html';
        $sectionAsideNativeDivsNative = $root . '/upstream-html-section-aside-native-divs.native';
        $mathRendererSpansHtml = $root . '/upstream-html-math-renderer-spans.html';
        $mathRendererSpansNative = $root . '/upstream-html-math-renderer-spans.native';
        $mathmlAnnotationHtml = $root . '/upstream-html-mathml-annotation.html';
        $mathmlAnnotationNative = $root . '/upstream-html-mathml-annotation.native';
        $orphanListBlocksHtml = $root . '/upstream-html-orphan-list-blocks.html';
        $orphanListBlocksNative = $root . '/upstream-html-orphan-list-blocks.native';
        $spanStrikeoutHtml = $root . '/upstream-html-span-strikeout.html';
        $spanStrikeoutNative = $root . '/upstream-html-span-strikeout.native';
        $spanlikeHtml = $root . '/upstream-html-spanlike-inline.html';
        $spanlikeNative = $root . '/upstream-html-spanlike-inline.native';
        $styleRawHtml = $root . '/upstream-html-style-raw-block.html';
        $styleRawNative = $root . '/upstream-html-style-raw-block.native';
        $scriptRawHtml = $root . '/upstream-html-script-raw-block.html';
        $scriptRawNative = $root . '/upstream-html-script-raw-block.native';
        $smallInlineHtml = $root . '/upstream-html-small-inline.html';
        $smallInlineNative = $root . '/upstream-html-small-inline.native';
        $standaloneLinebreakHtml = $root . '/upstream-html-standalone-linebreak.html';
        $standaloneLinebreakNative = $root . '/upstream-html-standalone-linebreak.native';
        $standaloneNoscriptHtml = $root . '/upstream-html-standalone-noscript-inline.html';
        $standaloneNoscriptNative = $root . '/upstream-html-standalone-noscript-inline.native';
        $standaloneInsHtml = $root . '/upstream-html-standalone-ins-inline.html';
        $standaloneInsNative = $root . '/upstream-html-standalone-ins-inline.native';
        $standaloneDelHtml = $root . '/upstream-html-standalone-del-inline.html';
        $standaloneDelNative = $root . '/upstream-html-standalone-del-inline.native';
        $standaloneInlineFlowHtml = $root . '/upstream-html-standalone-inline-flow.html';
        $standaloneInlineFlowNative = $root . '/upstream-html-standalone-inline-flow.native';
        $standaloneButtonHtml = $root . '/upstream-html-standalone-button-inline.html';
        $standaloneButtonNative = $root . '/upstream-html-standalone-button-inline.native';
        $standaloneProgressHtml = $root . '/upstream-html-standalone-progress-inline.html';
        $standaloneProgressNative = $root . '/upstream-html-standalone-progress-inline.native';
        $standaloneMapHtml = $root . '/upstream-html-standalone-map-inline.html';
        $standaloneMapNative = $root . '/upstream-html-standalone-map-inline.native';
        $standaloneAppletHtml = $root . '/upstream-html-standalone-applet-inline.html';
        $standaloneAppletNative = $root . '/upstream-html-standalone-applet-inline.native';
        $standaloneAudioHtml = $root . '/upstream-html-standalone-audio-inline.html';
        $standaloneAudioNative = $root . '/upstream-html-standalone-audio-inline.native';
        $standaloneVideoHtml = $root . '/upstream-html-standalone-video-inline.html';
        $standaloneVideoNative = $root . '/upstream-html-standalone-video-inline.native';
        $standaloneSvgHtml = $root . '/upstream-html-standalone-svg-inline.html';
        $standaloneSvgNative = $root . '/upstream-html-standalone-svg-inline.native';
        $standaloneVoidHtml = $root . '/upstream-html-standalone-void-inline.html';
        $standaloneVoidNative = $root . '/upstream-html-standalone-void-inline.native';
        $supSubHtml = $root . '/upstream-html-sup-sub-inline.html';
        $supSubNative = $root . '/upstream-html-sup-sub-inline.native';
        $smallcapsClassHtml = $root . '/upstream-html-smallcaps-class.html';
        $smallcapsClassNative = $root . '/upstream-html-smallcaps-class.native';
        $checkboxListHtml = $root . '/upstream-html-checkbox-list.html';
        $checkboxListNative = $root . '/upstream-html-checkbox-list.native';
        $styleScriptInlineHtml = $root . '/upstream-html-style-script-inline.html';
        $styleScriptInlineNative = $root . '/upstream-html-style-script-inline.native';
        $citeWbrRawInlineHtml = $root . '/upstream-html-cite-wbr-raw-inline.html';
        $citeWbrRawInlineNative = $root . '/upstream-html-cite-wbr-raw-inline.native';
        $definitionListHtml = $root . '/upstream-html-definition-list.html';
        $definitionListNative = $root . '/upstream-html-definition-list.native';
        $detailsSummaryRawBlockHtml = $root . '/upstream-html-details-summary-raw-block.html';
        $detailsSummaryRawBlockNative = $root . '/upstream-html-details-summary-raw-block.native';
        $genericRawInlineHtml = $root . '/upstream-html-generic-raw-inline.html';
        $genericRawInlineNative = $root . '/upstream-html-generic-raw-inline.native';
        $standaloneObjectEmbedHtml = $root . '/upstream-html-standalone-object-embed-inline.html';
        $standaloneObjectEmbedNative = $root . '/upstream-html-standalone-object-embed-inline.native';
        $svgDisabledRawHtml = $root . '/upstream-html-svg-disabled-raw-html.html';
        $svgDisabledRawNative = $root . '/upstream-html-svg-disabled-raw-html.native';
        $svgRawHtml = $root . '/upstream-html-svg-raw-html.html';
        $svgRawNative = $root . '/upstream-html-svg-raw-html.native';
        $tableFootHtml = $root . '/upstream-html-table-foot.html';
        $tableFootNative = $root . '/upstream-html-table-foot.native';
        $textareaRawBlockHtml = $root . '/upstream-html-textarea-raw-block.html';
        $textareaRawBlockNative = $root . '/upstream-html-textarea-raw-block.native';
        $thematicBreakHtml = $root . '/upstream-html-thematic-break.html';
        $thematicBreakNative = $root . '/upstream-html-thematic-break.native';
        $rubyAnnotationHtml = $root . '/upstream-html-ruby-annotation.html';
        $rubyAnnotationNative = $root . '/upstream-html-ruby-annotation.native';
        $expectedUnpairedHtmlFixtureNames = [];

        $t->true(is_file($anchorImageHtml), 'HTML anchor/image fixture must be checked in');
        $t->true(is_file($anchorImageNative), 'Native anchor/image fixture must be checked in');
        $t->true(is_file($baseAbsoluteImageHtml), 'HTML base absolute image fixture must be checked in');
        $t->true(is_file($baseAbsoluteImageNative), 'Native base absolute image fixture must be checked in');
        $t->true(is_file($baseMediaHtml), 'HTML base-media fixture must be checked in');
        $t->true(is_file($baseMediaNative), 'Native base-media fixture must be checked in');
        $t->true(is_file($bdoDirectionHtml), 'HTML bdo-direction fixture must be checked in');
        $t->true(is_file($bdoDirectionNative), 'Native bdo-direction fixture must be checked in');
        $t->true(is_file($blockquoteHtml), 'HTML blockquote fixture must be checked in');
        $t->true(is_file($blockquoteNative), 'Native blockquote fixture must be checked in');
        $t->true(is_file($rowHeaderHtml), 'HTML row-header fixture must be checked in');
        $t->true(is_file($rowHeaderNative), 'Native row-header fixture must be checked in');
        $t->true(is_file($noterefHtml), 'HTML doc-noteref fixture must be checked in');
        $t->true(is_file($noterefNative), 'Native doc-noteref fixture must be checked in');
        $t->true(is_file($tablePlacementHtml), 'HTML doc-noteref table placement fixture must be checked in');
        $t->true(is_file($tablePlacementNative), 'Native doc-noteref table placement fixture must be checked in');
        $t->true(is_file($figureCaptionHtml), 'HTML figure-caption fixture must be checked in');
        $t->true(is_file($figureCaptionNative), 'Native figure-caption fixture must be checked in');
        $t->true(is_file($lineBlockHtml), 'HTML line-block fixture must be checked in');
        $t->true(is_file($lineBlockNative), 'Native line-block fixture must be checked in');
        $t->true(is_file($preCodeHtml), 'HTML pre-code attributes fixture must be checked in');
        $t->true(is_file($preCodeNative), 'Native pre-code attributes fixture must be checked in');
        $t->true(is_file($preCodeBreakHtml), 'HTML pre-code break fixture must be checked in');
        $t->true(is_file($preCodeBreakNative), 'Native pre-code break fixture must be checked in');
        $t->true(is_file($rawDisabledHtml), 'HTML raw-disabled fixture must be checked in');
        $t->true(is_file($rawDisabledNative), 'Native raw-disabled fixture must be checked in');
        $t->true(is_file($inlineCodeHtml), 'HTML inline-code fixture must be checked in');
        $t->true(is_file($inlineCodeNative), 'Native inline-code fixture must be checked in');
        $t->true(is_file($inlineQuoteCiteBaseHtml), 'HTML inline quote cite base fixture must be checked in');
        $t->true(is_file($inlineQuoteCiteBaseNative), 'Native inline quote cite base fixture must be checked in');
        $t->true(is_file($langMetadataHtml), 'HTML lang-metadata fixture must be checked in');
        $t->true(is_file($langMetadataNative), 'Native lang-metadata fixture must be checked in');
        $t->true(is_file($xmlLangMetadataHtml), 'HTML xml-lang-metadata fixture must be checked in');
        $t->true(is_file($xmlLangMetadataNative), 'Native xml-lang-metadata fixture must be checked in');
        $t->true(is_file($listItemIdHtml), 'HTML list item id fixture must be checked in');
        $t->true(is_file($listItemIdNative), 'Native list item id fixture must be checked in');
        $t->true(is_file($headerNativeDivsHtml), 'HTML header native-divs fixture must be checked in');
        $t->true(is_file($headerNativeDivsNative), 'Native header native-divs fixture must be checked in');
        $t->true(is_file($iframeLocalResourceHtml), 'HTML iframe local resource fixture must be checked in');
        $t->true(is_file($iframeLocalResourceNative), 'Native iframe local resource fixture must be checked in');
        $t->true(is_file($mainNativeDivsHtml), 'HTML main native-divs fixture must be checked in');
        $t->true(is_file($mainNativeDivsNative), 'Native main native-divs fixture must be checked in');
        $t->true(is_file($sectionAsideNativeDivsHtml), 'HTML section-aside native-divs fixture must be checked in');
        $t->true(is_file($sectionAsideNativeDivsNative), 'Native section-aside native-divs fixture must be checked in');
        $t->true(is_file($mathRendererSpansHtml), 'HTML math renderer spans fixture must be checked in');
        $t->true(is_file($mathRendererSpansNative), 'Native math renderer spans fixture must be checked in');
        $t->true(is_file($mathmlAnnotationHtml), 'HTML mathml annotation fixture must be checked in');
        $t->true(is_file($mathmlAnnotationNative), 'Native mathml annotation fixture must be checked in');
        $t->true(is_file($orphanListBlocksHtml), 'HTML orphan-list-blocks fixture must be checked in');
        $t->true(is_file($orphanListBlocksNative), 'Native orphan-list-blocks fixture must be checked in');
        $t->true(is_file($spanStrikeoutHtml), 'HTML span-strikeout fixture must be checked in');
        $t->true(is_file($spanStrikeoutNative), 'Native span-strikeout fixture must be checked in');
        $t->true(is_file($spanlikeHtml), 'HTML spanlike-inline fixture must be checked in');
        $t->true(is_file($spanlikeNative), 'Native spanlike-inline fixture must be checked in');
        $t->true(is_file($styleRawHtml), 'HTML style raw-block fixture must be checked in');
        $t->true(is_file($styleRawNative), 'Native style raw-block fixture must be checked in');
        $t->true(is_file($scriptRawHtml), 'HTML script raw-block fixture must be checked in');
        $t->true(is_file($scriptRawNative), 'Native script raw-block fixture must be checked in');
        $t->true(is_file($smallInlineHtml), 'HTML small-inline fixture must be checked in');
        $t->true(is_file($smallInlineNative), 'Native small-inline fixture must be checked in');
        $t->true(is_file($standaloneLinebreakHtml), 'HTML standalone linebreak fixture must be checked in');
        $t->true(is_file($standaloneLinebreakNative), 'Native standalone linebreak fixture must be checked in');
        $t->true(is_file($standaloneNoscriptHtml), 'HTML standalone noscript fixture must be checked in');
        $t->true(is_file($standaloneNoscriptNative), 'Native standalone noscript fixture must be checked in');
        $t->true(is_file($standaloneInsHtml), 'HTML standalone ins fixture must be checked in');
        $t->true(is_file($standaloneInsNative), 'Native standalone ins fixture must be checked in');
        $t->true(is_file($standaloneDelHtml), 'HTML standalone del fixture must be checked in');
        $t->true(is_file($standaloneDelNative), 'Native standalone del fixture must be checked in');
        $t->true(is_file($standaloneInlineFlowHtml), 'HTML standalone inline-flow fixture must be checked in');
        $t->true(is_file($standaloneInlineFlowNative), 'Native standalone inline-flow fixture must be checked in');
        $t->true(is_file($standaloneButtonHtml), 'HTML standalone button fixture must be checked in');
        $t->true(is_file($standaloneButtonNative), 'Native standalone button fixture must be checked in');
        $t->true(is_file($standaloneProgressHtml), 'HTML standalone progress fixture must be checked in');
        $t->true(is_file($standaloneProgressNative), 'Native standalone progress fixture must be checked in');
        $t->true(is_file($standaloneMapHtml), 'HTML standalone map fixture must be checked in');
        $t->true(is_file($standaloneMapNative), 'Native standalone map fixture must be checked in');
        $t->true(is_file($standaloneAppletHtml), 'HTML standalone applet fixture must be checked in');
        $t->true(is_file($standaloneAppletNative), 'Native standalone applet fixture must be checked in');
        $t->true(is_file($standaloneAudioHtml), 'HTML standalone audio fixture must be checked in');
        $t->true(is_file($standaloneAudioNative), 'Native standalone audio fixture must be checked in');
        $t->true(is_file($standaloneVideoHtml), 'HTML standalone video fixture must be checked in');
        $t->true(is_file($standaloneVideoNative), 'Native standalone video fixture must be checked in');
        $t->true(is_file($standaloneSvgHtml), 'HTML standalone svg fixture must be checked in');
        $t->true(is_file($standaloneSvgNative), 'Native standalone svg fixture must be checked in');
        $t->true(is_file($standaloneVoidHtml), 'HTML standalone void fixture must be checked in');
        $t->true(is_file($standaloneVoidNative), 'Native standalone void fixture must be checked in');
        $t->true(is_file($supSubHtml), 'HTML sup/sub inline fixture must be checked in');
        $t->true(is_file($supSubNative), 'Native sup/sub inline fixture must be checked in');
        $t->true(is_file($smallcapsClassHtml), 'HTML smallcaps class fixture must be checked in');
        $t->true(is_file($smallcapsClassNative), 'Native smallcaps class fixture must be checked in');
        $t->true(is_file($checkboxListHtml), 'HTML checkbox-list fixture must be checked in');
        $t->true(is_file($checkboxListNative), 'Native checkbox-list fixture must be checked in');
        $t->true(is_file($styleScriptInlineHtml), 'HTML style/script inline fixture must be checked in');
        $t->true(is_file($styleScriptInlineNative), 'Native style/script inline fixture must be checked in');
        $t->true(is_file($citeWbrRawInlineHtml), 'HTML cite/wbr raw inline fixture must be checked in');
        $t->true(is_file($citeWbrRawInlineNative), 'Native cite/wbr raw inline fixture must be checked in');
        $t->true(is_file($definitionListHtml), 'HTML definition-list fixture must be checked in');
        $t->true(is_file($definitionListNative), 'Native definition-list fixture must be checked in');
        $t->true(is_file($detailsSummaryRawBlockHtml), 'HTML details summary raw-block fixture must be checked in');
        $t->true(is_file($detailsSummaryRawBlockNative), 'Native details summary raw-block fixture must be checked in');
        $t->true(is_file($genericRawInlineHtml), 'HTML generic raw inline fixture must be checked in');
        $t->true(is_file($genericRawInlineNative), 'Native generic raw inline fixture must be checked in');
        $t->true(is_file($standaloneObjectEmbedHtml), 'HTML standalone object/embed fixture must be checked in');
        $t->true(is_file($standaloneObjectEmbedNative), 'Native standalone object/embed fixture must be checked in');
        $t->true(is_file($svgDisabledRawHtml), 'HTML svg disabled raw fixture must be checked in');
        $t->true(is_file($svgDisabledRawNative), 'Native svg disabled raw fixture must be checked in');
        $t->true(is_file($svgRawHtml), 'HTML svg raw fixture must be checked in');
        $t->true(is_file($svgRawNative), 'Native svg raw fixture must be checked in');
        $t->true(is_file($tableFootHtml), 'HTML table foot fixture must be checked in');
        $t->true(is_file($tableFootNative), 'Native table foot fixture must be checked in');
        $t->true(is_file($textareaRawBlockHtml), 'HTML textarea raw-block fixture must be checked in');
        $t->true(is_file($textareaRawBlockNative), 'Native textarea raw-block fixture must be checked in');
        $t->true(is_file($thematicBreakHtml), 'HTML thematic-break fixture must be checked in');
        $t->true(is_file($thematicBreakNative), 'Native thematic-break fixture must be checked in');
        $t->true(is_file($rubyAnnotationHtml), 'HTML ruby annotation fixture must be checked in');
        $t->true(is_file($rubyAnnotationNative), 'Native ruby annotation fixture must be checked in');

        $harness = new HtmlNativeAstComparisonHarness();
        $report = $harness->run($root);
        $text = $harness->formatReport($report);

        $t->same('completed', $report['status']);
        $t->same(58, $report['htmlFixtureCount']);
        $t->same(58, $report['nativeFixtureCount']);
        $t->same(58, $report['pairedFixtureCount']);
        $t->same(0, $report['unpairedHtmlFixtureCount']);
        $t->same(0, $report['unpairedNativeFixtureCount']);
        $t->same($expectedUnpairedHtmlFixtureNames, $report['unpairedHtmlFixtureNames']);
        $t->same([], $report['unpairedNativeFixtureNames']);
        $t->same([], $report['unpairedHtmlFixtureExamples']);
        $t->same(58, $report['totalPairCount']);
        $t->same(58, $report['comparedPairCount']);
        $t->same(58, $report['htmlParsedCount']);
        $t->same(58, $report['nativeParsedCount']);
        $t->same(58, $report['bothParsedCount']);
        $t->same(0, $report['parseFailureCount']);
        $t->same(58, $report['normalizedAstMatchCount']);
        $t->same(0, $report['normalizedAstMismatchCount']);
        $t->same('normalized-ast-equality-observed-not-runner-parity', $report['astParityStatus']);
        $t->same(true, HtmlNativeAstComparisonHarness::hasRequiredMappedParity($report, 58));
        $t->same(['htmlRawHtml' => false], $report['htmlReaderFixtureOptionOverrides']['upstream-html-raw-disabled-skip.html'] ?? null);
        $t->same('covered-by-current-normalized-ast-evidence', $report['orderedRemainingGaps'][0]['status']);
        $t->same('checked-in-html-fixtures-without-native-pairs', $report['orderedRemainingGaps'][1]['id']);
        $t->same('covered-by-current-normalized-ast-evidence', $report['orderedRemainingGaps'][1]['status']);
        $t->same('HTML fixtures=58; native fixtures=58; same-basename pairs=58; HTML fixtures without native pairs=0', $report['orderedRemainingGaps'][1]['currentEvidence']);
        $t->same('The current checked-in gate covers 58 paired fixture(s) out of 58 HTML fixture(s).', $report['orderedRemainingGaps'][3]['currentEvidence']);
        $t->contains('fixtureInventory: html=58 native=58 paired=58 unpairedHtml=0 unpairedNative=0', $text);
        $t->contains('pairs: total=58 compared=58 parsedBoth=58 parseFailures=0', $text);
        $t->contains('normalizedAst: matches=58 (100.00%) mismatches=0', $text);

        $command = escapeshellarg(PHP_BINARY)
            . ' '
            . escapeshellarg(dirname(__DIR__, 3) . '/tools/pandoc-html-native-ast.php')
            . ' --html-dir=' . escapeshellarg($root)
            . ' --json'
            . ' summary'
            . ' --require-mapped-parity=58';
        $output = [];
        $exitCode = 0;
        exec($command, $output, $exitCode);
        $decoded = json_decode(implode("\n", $output), true, 512, JSON_THROW_ON_ERROR);

        $t->same(0, $exitCode);
        $t->same(58, $decoded['htmlFixtureCount']);
        $t->same(0, $decoded['unpairedHtmlFixtureCount']);
        $t->same($expectedUnpairedHtmlFixtureNames, $decoded['unpairedHtmlFixtureNames']);
        $t->same([], $decoded['unpairedNativeFixtureNames']);
        $t->same(['htmlRawHtml' => false], $decoded['htmlReaderFixtureOptionOverrides']['upstream-html-raw-disabled-skip.html'] ?? null);
        $t->same(58, $decoded['normalizedAstMatchCount']);
        $t->same(0, $decoded['normalizedAstMismatchCount']);
    },
];
