<?php

declare(strict_types=1);

require __DIR__ . '/../../../tools/bootstrap.php';

$fixture = require __DIR__ . '/../fixtures/wordpress-config-include-conditional.php';

return [
    'activeBranch' => $fixture['activeBranch'],
    'remoteUrl' => $fixture['remoteUrl'],
    'preview' => $fixture['preview'],
    'conflictStyle' => $fixture['conflictStyle'],
    'httpExtraHeader' => $fixture['httpExtraHeader'],
    'transferFsckObjects' => $fixture['transferFsckObjects'],
    'escapedGitdirPolicy' => $fixture['escapedGitdirPolicy'],
    'recursiveGitdirPolicy' => $fixture['recursiveGitdirPolicy'],
    'slashClassRejectedPolicy' => $fixture['slashClassRejectedPolicy'],
    'bracketUrlPolicy' => $fixture['bracketUrlPolicy'],
    'legacyDotRemotePolicy' => $fixture['legacyDotRemotePolicy'],
    'posixUrlPolicy' => $fixture['posixUrlPolicy'],
    'escapedHyphenUrlPolicy' => $fixture['escapedHyphenUrlPolicy'],
    'reversedRangeStartUrlPolicy' => $fixture['reversedRangeStartUrlPolicy'],
    'reversedRangeMiddleUrlPolicy' => $fixture['reversedRangeMiddleUrlPolicy'],
    'legacyBytePolicy' => $fixture['legacyBytePolicy'],
    'blankTabUrlPolicy' => $fixture['blankTabUrlPolicy'],
    'blankVerticalTabUrlPolicy' => $fixture['blankVerticalTabUrlPolicy'],
    'controlVerticalTabUrlPolicy' => $fixture['controlVerticalTabUrlPolicy'],
    'literalTildePathPolicy' => $fixture['literalTildePathPolicy'],
    'installPrefixPathPolicy' => $fixture['installPrefixPathPolicy'],
    'literalPrefixPathPolicy' => $fixture['literalPrefixPathPolicy'],
    'backslashUrlSlashPolicy' => $fixture['backslashUrlSlashPolicy'],
    'backslashUrlLiteralPolicy' => $fixture['backslashUrlLiteralPolicy'],
    'unboundedDoubleStarRejectedPolicy' => $fixture['unboundedDoubleStarRejectedPolicy'],
    'invalidPosixPolicy' => $fixture['invalidPosixPolicy'],
    'unclosedBracketPolicy' => $fixture['unclosedBracketPolicy'],
    'trailingBackslashUrlPolicy' => $fixture['trailingBackslashUrlPolicy'],
    'optionalPrefixPolicy' => $fixture['optionalPrefixPolicy'],
    'tildeAloneGitdirPolicy' => $fixture['tildeAloneGitdirPolicy'],
    'doubleSlashGitdirPolicy' => $fixture['doubleSlashGitdirPolicy'],
    'dotDotGitdirPolicy' => $fixture['dotDotGitdirPolicy'],
    'dotSlashRootPolicy' => $fixture['dotSlashRootPolicy'],
    'dotSlashMissPolicy' => $fixture['dotSlashMissPolicy'],
    'absoluteWorktreePolicy' => $fixture['absoluteWorktreePolicy'],
    'absoluteGitdirPolicy' => $fixture['absoluteGitdirPolicy'],
    'absoluteWorktreeGlobPolicy' => $fixture['absoluteWorktreeGlobPolicy'],
    'backslashGitdirSlashPolicy' => $fixture['backslashGitdirSlashPolicy'],
    'backslashGitdirWildcardPolicy' => $fixture['backslashGitdirWildcardPolicy'],
    'drivePrefixSupported' => $fixture['drivePrefixSupported'],
    'drivePrefixGitdirPolicy' => $fixture['drivePrefixGitdirPolicy'],
    'symlinkGitdirSupported' => $fixture['symlinkGitdirSupported'],
    'symlinkRealpathPolicy' => $fixture['symlinkRealpathPolicy'],
    'symlinkLiteralPolicy' => $fixture['symlinkLiteralPolicy'],
    'symlinkIcasePolicy' => $fixture['symlinkIcasePolicy'],
    'environmentBranchPolicy' => $fixture['environmentBranchPolicy'],
    'environmentBranchBoundaryPolicy' => $fixture['environmentBranchBoundaryPolicy'],
    'environmentRemotePolicy' => $fixture['environmentRemotePolicy'],
    'environmentNamedUserPolicy' => $fixture['environmentNamedUserPolicy'],
    'namedUserPathPolicy' => $fixture['namedUserPathPolicy'],
    'namedUserGitdirPolicy' => $fixture['namedUserGitdirPolicy'],
    'sectionsLoaded' => $fixture['sectionsLoaded'],
];
