<?php

declare(strict_types=1);

require __DIR__ . '/../../../tools/bootstrap.php';

$fixture = require __DIR__ . '/../fixtures/wordpress-receive-pack-transport.php';

return [
    'oldCommit' => $fixture['oldCommit'],
    'newCommit' => $fixture['newCommit'],
    'acceptedRefs' => $fixture['acceptedRefs'],
    'progressMessages' => $fixture['progressMessages'],
    'requestByteLength' => strlen($fixture['requestBytes']),
    'responseSuccessful' => $fixture['responseSuccessful'],
    'sshTarget' => $fixture['sshTarget'],
    'sshIpv6Target' => $fixture['sshIpv6Target'],
    'sshScpIpv6Target' => $fixture['sshScpIpv6Target'],
    'sshLegacySchemeTarget' => $fixture['sshLegacySchemeTarget'],
    'sshLegacyGitSchemeTarget' => $fixture['sshLegacyGitSchemeTarget'],
    'sshScpLikeHomeTarget' => $fixture['sshScpLikeHomeTarget'],
    'sshOptionLikeHostWithUserTarget' => $fixture['sshOptionLikeHostWithUserTarget'],
    'sshScpLikeAtUserTarget' => $fixture['sshScpLikeAtUserTarget'],
    'sshCommand' => $fixture['sshCommand'],
    'sshHomeCommand' => $fixture['sshHomeCommand'],
    'sshProtocolV2Environment' => $fixture['sshProtocolV2Context']['environment'],
    'sshProtocolV2Arguments' => $fixture['sshProtocolV2Context']['sshArguments'],
    'sshOptionLikeHostWithUserArguments' => $fixture['sshOptionLikeHostWithUserContext']['sshArguments'],
    'sshScpLikeAtUserArguments' => $fixture['sshScpLikeAtUserContext']['sshArguments'],
    'sshPlinkArguments' => $fixture['sshPlinkContext']['sshArguments'],
    'sshTortoisePlinkArguments' => $fixture['sshTortoisePlinkContext']['sshArguments'],
    'sshSimpleArguments' => $fixture['sshSimpleContext']['sshArguments'],
    'sshShellScriptUsesShell' => $fixture['sshShellScriptContext']['useShell'],
    'sshDisallowShellUsesShell' => $fixture['sshDisallowShellContext']['useShell'],
    'sshSimplePortRejected' => $fixture['sshSimplePortRejected'],
    'sshCredentialContext' => $fixture['sshProtocolV2Context']['redactedCredentialContext'],
    'sshAuthenticationBoundary' => $fixture['sshProtocolV2Context']['authenticationBoundary'],
    'sshErrorClassifications' => $fixture['sshErrorClassifications'],
    'gitDaemonServiceRequestPayload' => substr($fixture['gitDaemonServiceRequest'], 4),
    'gitDaemonUrlServiceRequestPayload' => substr($fixture['gitDaemonUrlServiceRequest'], 4),
    'gitDaemonValueOnlyExtraServiceRequestPayload' => substr($fixture['gitDaemonValueOnlyExtraServiceRequest'], 4),
    'gitDaemonProtocolV2HomeServiceRequestPayload' => substr($fixture['gitDaemonProtocolV2HomeServiceRequest'], 4),
    'gitDaemonProtocolV2NamedHomeUrlServiceRequestPayload' => substr($fixture['gitDaemonProtocolV2NamedHomeUrlServiceRequest'], 4),
    'gitDaemonEncodedUrlServiceRequestPayload' => substr($fixture['gitDaemonEncodedUrlServiceRequest'], 4),
    'gitDaemonIpv6ServiceRequestPayload' => substr($fixture['gitDaemonIpv6ServiceRequest'], 4),
    'unsafeGitDaemonPathRejected' => $fixture['unsafeGitDaemonPathRejected'],
    'unsafeGitDaemonControlByteRejected' => $fixture['unsafeGitDaemonControlByteRejected'],
    'unsafeGitDaemonUrlRejected' => $fixture['unsafeGitDaemonUrlRejected'],
    'unsafeGitDaemonEncodedControlByteRejected' => $fixture['unsafeGitDaemonEncodedControlByteRejected'],
    'unsafeGitDaemonEncodedHostDelimiterRejected' => $fixture['unsafeGitDaemonEncodedHostDelimiterRejected'],
    'unsafeGitDaemonExtraParameterRejected' => $fixture['unsafeGitDaemonExtraParameterRejected'],
    'unsafeGitDaemonProtocolVersionRejected' => $fixture['unsafeGitDaemonProtocolVersionRejected'],
    'unsafeSmartHttpCredentialControlByteRejected' => $fixture['unsafeSmartHttpCredentialControlByteRejected'],
    'unsafeSmartHttpCredentialTabRejected' => $fixture['unsafeSmartHttpCredentialTabRejected'],
    'unsafeSmartHttpHostDelimiterRejected' => $fixture['unsafeSmartHttpHostDelimiterRejected'],
    'unsafeSmartHttpProxyHostDelimiterRejected' => $fixture['unsafeSmartHttpProxyHostDelimiterRejected'],
    'unsafeSmartHttpEncodedPathControlByteRejected' => $fixture['unsafeSmartHttpEncodedPathControlByteRejected'],
    'unsafeSmartHttpExtraParameterTabRejected' => $fixture['unsafeSmartHttpExtraParameterTabRejected'],
    'unsafeSmartHttpHeaderTabRejected' => $fixture['unsafeSmartHttpHeaderTabRejected'],
    'unsafeSmartHttpNoProxyDelimiterRejected' => $fixture['unsafeSmartHttpNoProxyDelimiterRejected'],
    'unsafeSmartHttpRawUrlControlByteRejected' => $fixture['unsafeSmartHttpRawUrlControlByteRejected'],
    'unsafeSmartHttpRawProxyControlByteRejected' => $fixture['unsafeSmartHttpRawProxyControlByteRejected'],
    'smartHttpAdvertisementWithoutServiceHeaderAccepted' => $fixture['smartHttpAdvertisementWithoutServiceHeaderAccepted'],
    'streamWatchdogTimeoutReported' => $fixture['streamWatchdogTimeoutReported'],
    'advertisementErrorReported' => $fixture['advertisementErrorReported'],
    'oversizeAdvertisementRejected' => $fixture['oversizeAdvertisementRejected'],
    'unsafeSshTargetRejected' => $fixture['unsafeSshTargetRejected'],
    'unsafeSshHostDelimiterRejected' => $fixture['unsafeSshHostDelimiterRejected'],
    'unsafeSshUserDelimiterRejected' => $fixture['unsafeSshUserDelimiterRejected'],
    'unsafeSshScpIpv6UserRejected' => $fixture['unsafeSshScpIpv6UserRejected'],
    'unsafeSshEncodedUserDelimiterRejected' => $fixture['unsafeSshEncodedUserDelimiterRejected'],
    'unsafeSshPasswordRejected' => $fixture['unsafeSshPasswordRejected'],
    'unsafeSshLegacyHostRejected' => $fixture['unsafeSshLegacyHostRejected'],
];
