<?php

declare(strict_types=1);

require __DIR__ . '/../../../tools/bootstrap.php';

$fixture = require __DIR__ . '/../fixtures/wordpress-receive-pack-transport.php';

return [
    'oldCommit' => $fixture['oldCommit'],
    'newCommit' => $fixture['newCommit'],
    'acceptedRefs' => $fixture['acceptedRefs'],
    'progressMessages' => $fixture['progressMessages'],
    'requestByteLength' => strlen($fixture['requestBytes']),
    'responseSuccessful' => $fixture['responseSuccessful'],
    'responseTerminator' => $fixture['responseTerminator'],
    'requestPacketLineMaxPayloadLength' => $fixture['requestPacketLineMaxPayloadLength'],
    'maxRequestCommandPacketHeader' => $fixture['maxRequestCommandPacketHeader'],
    'oversizeRequestCommandRejected' => $fixture['oversizeRequestCommandRejected'],
    'oversizePushOptionRejected' => $fixture['oversizePushOptionRejected'],
    'sshTarget' => $fixture['sshTarget'],
    'sshIpv6Target' => $fixture['sshIpv6Target'],
    'sshIpv6Arguments' => $fixture['sshIpv6Context']['sshArguments'],
    'sshScpIpv6Target' => $fixture['sshScpIpv6Target'],
    'sshScpIpv6Arguments' => $fixture['sshScpIpv6Context']['sshArguments'],
    'sshLegacySchemeTarget' => $fixture['sshLegacySchemeTarget'],
    'sshLegacyGitSchemeTarget' => $fixture['sshLegacyGitSchemeTarget'],
    'sshScpLikeHomeTarget' => $fixture['sshScpLikeHomeTarget'],
    'sshNonNumericPortTarget' => $fixture['sshNonNumericPortTarget'],
    'sshNonNumericPortArguments' => $fixture['sshNonNumericPortContext']['sshArguments'],
    'sshRootPathTarget' => $fixture['sshRootPathTarget'],
    'sshRootPathCommand' => $fixture['sshRootPathContext']['command'],
    'sshRootPathArguments' => $fixture['sshRootPathContext']['sshArguments'],
    'sshOptionLikeHostWithUserTarget' => $fixture['sshOptionLikeHostWithUserTarget'],
    'sshScpLikeAtUserTarget' => $fixture['sshScpLikeAtUserTarget'],
    'sshCommand' => $fixture['sshCommand'],
    'sshHomeCommand' => $fixture['sshHomeCommand'],
    'sshBangPathCommand' => $fixture['sshBangPathCommand'],
    'sshProtocolV2Environment' => $fixture['sshProtocolV2Context']['environment'],
    'sshProtocolV2Arguments' => $fixture['sshProtocolV2Context']['sshArguments'],
    'sshProtocolV2InvocationArguments' => $fixture['sshProtocolV2Context']['sshInvocationArguments'],
    'sshOptionLikeHostWithUserArguments' => $fixture['sshOptionLikeHostWithUserContext']['sshArguments'],
    'sshScpLikeAtUserArguments' => $fixture['sshScpLikeAtUserContext']['sshArguments'],
    'sshPlinkArguments' => $fixture['sshPlinkContext']['sshArguments'],
    'sshExtensionStemKinds' => array_map(
        static fn (array $context): string => $context['programKind'],
        $fixture['sshExtensionStemContexts'],
    ),
    'sshExtensionStemArguments' => array_map(
        static fn (array $context): array => $context['sshArguments'],
        $fixture['sshExtensionStemContexts'],
    ),
    'sshIdentityArguments' => $fixture['sshIdentityContext']['sshArguments'],
    'sshIdentityCredentialContext' => $fixture['sshIdentityContext']['redactedCredentialContext'],
    'sshIdentityClearedArguments' => $fixture['sshIdentityClearedContext']['sshArguments'],
    'sshTortoisePlinkArguments' => $fixture['sshTortoisePlinkContext']['sshArguments'],
    'sshSimpleArguments' => $fixture['sshSimpleContext']['sshArguments'],
    'sshShellScriptUsesShell' => $fixture['sshShellScriptContext']['useShell'],
    'sshShellScriptFeatureProbe' => $fixture['sshShellScriptContext']['sshFeatureProbe'],
    'sshDisallowShellUsesShell' => $fixture['sshDisallowShellContext']['useShell'],
    'sshDisallowShellFeatureProbe' => $fixture['sshDisallowShellContext']['sshFeatureProbe'],
    'sshFallbackCommand' => $fixture['sshFallbackContext']['sshCommand'],
    'sshFallbackDisallowShell' => $fixture['sshFallbackContext']['disallowShell'],
    'sshFallbackUsesShell' => $fixture['sshFallbackContext']['useShell'],
    'sshFallbackArguments' => $fixture['sshFallbackContext']['sshArguments'],
    'sshFallbackFeatureProbe' => $fixture['sshFallbackFeatureProbeContext']['sshFeatureProbe'],
    'sshCommandPrecedenceUsesShell' => $fixture['sshCommandPrecedenceContext']['useShell'],
    'sshExplicitSimpleFeatureProbe' => $fixture['sshExplicitSimpleNoFeatureProbeContext']['sshFeatureProbe'],
    'sshExplicitKindOptionLikeHostArguments' => $fixture['sshExplicitKindOptionLikeHostContext']['sshArguments'],
    'sshSimplePortRejected' => $fixture['sshSimplePortRejected'],
    'sshCredentialContext' => $fixture['sshProtocolV2Context']['redactedCredentialContext'],
    'sshAuthenticationBoundary' => $fixture['sshProtocolV2Context']['authenticationBoundary'],
    'sshEnvironmentRemovals' => $fixture['sshProtocolV2Context']['environmentRemovals'],
    'sshErrorClassifications' => $fixture['sshErrorClassifications'],
    'gitDaemonServiceRequestPayload' => substr($fixture['gitDaemonServiceRequest'], 4),
    'gitDaemonUrlServiceRequestPayload' => substr($fixture['gitDaemonUrlServiceRequest'], 4),
    'gitDaemonValueOnlyExtraServiceRequestPayload' => substr($fixture['gitDaemonValueOnlyExtraServiceRequest'], 4),
    'gitDaemonProtocolV2HomeServiceRequestPayload' => substr($fixture['gitDaemonProtocolV2HomeServiceRequest'], 4),
    'gitDaemonProtocolV2NamedHomeUrlServiceRequestPayload' => substr($fixture['gitDaemonProtocolV2NamedHomeUrlServiceRequest'], 4),
    'gitDaemonEncodedUrlServiceRequestPayload' => substr($fixture['gitDaemonEncodedUrlServiceRequest'], 4),
    'gitDaemonIpv6ServiceRequestPayload' => substr($fixture['gitDaemonIpv6ServiceRequest'], 4),
    'gitDaemonVirtualHostServiceRequestPayload' => substr($fixture['gitDaemonVirtualHostServiceRequest'], 4),
    'unsafeGitDaemonPathRejected' => $fixture['unsafeGitDaemonPathRejected'],
    'unsafeGitDaemonControlByteRejected' => $fixture['unsafeGitDaemonControlByteRejected'],
    'unsafeGitDaemonUrlRejected' => $fixture['unsafeGitDaemonUrlRejected'],
    'unsafeGitDaemonEncodedControlByteRejected' => $fixture['unsafeGitDaemonEncodedControlByteRejected'],
    'unsafeGitDaemonEncodedHostDelimiterRejected' => $fixture['unsafeGitDaemonEncodedHostDelimiterRejected'],
    'unsafeGitDaemonExtraParameterRejected' => $fixture['unsafeGitDaemonExtraParameterRejected'],
    'unsafeGitDaemonProtocolVersionRejected' => $fixture['unsafeGitDaemonProtocolVersionRejected'],
    'unsafeGitDaemonVirtualHostRejected' => $fixture['unsafeGitDaemonVirtualHostRejected'],
    'unsafeGitDaemonVirtualPortRejected' => $fixture['unsafeGitDaemonVirtualPortRejected'],
    'unsafeSmartHttpCredentialControlByteRejected' => $fixture['unsafeSmartHttpCredentialControlByteRejected'],
    'unsafeSmartHttpCredentialTabRejected' => $fixture['unsafeSmartHttpCredentialTabRejected'],
    'unsafeSmartHttpHostDelimiterRejected' => $fixture['unsafeSmartHttpHostDelimiterRejected'],
    'unsafeSmartHttpProxyHostDelimiterRejected' => $fixture['unsafeSmartHttpProxyHostDelimiterRejected'],
    'unsafeSmartHttpEncodedPathControlByteRejected' => $fixture['unsafeSmartHttpEncodedPathControlByteRejected'],
    'unsafeSmartHttpExtraParameterTabRejected' => $fixture['unsafeSmartHttpExtraParameterTabRejected'],
    'unsafeSmartHttpHeaderTabRejected' => $fixture['unsafeSmartHttpHeaderTabRejected'],
    'unsafeSmartHttpNoProxyDelimiterRejected' => $fixture['unsafeSmartHttpNoProxyDelimiterRejected'],
    'unsafeSmartHttpRawUrlControlByteRejected' => $fixture['unsafeSmartHttpRawUrlControlByteRejected'],
    'unsafeSmartHttpRawProxyControlByteRejected' => $fixture['unsafeSmartHttpRawProxyControlByteRejected'],
    'smartHttpAdvertisementWithoutServiceHeaderAccepted' => $fixture['smartHttpAdvertisementWithoutServiceHeaderAccepted'],
    'smartHttpDuplicateContentTypeAccepted' => $fixture['smartHttpDuplicateContentTypeAccepted'],
    'smartHttpDefaultUserAgent' => $fixture['smartHttpHeaderBoundary']['defaultGetUserAgent'],
    'smartHttpDefaultGetExpectHeader' => $fixture['smartHttpHeaderBoundary']['defaultGetExpectHeader'],
    'smartHttpOverrideUserAgent' => $fixture['smartHttpHeaderBoundary']['overridePostUserAgent'],
    'smartHttpPostExpectSuppressed' => $fixture['smartHttpHeaderBoundary']['overridePostExpectHeader'] === '',
    'smartHttpHeaderBoundaryPostBodyPreserved' => $fixture['smartHttpHeaderBoundary']['overridePostBodyPreserved'],
    'smartHttpTransportOptionMethods' => $fixture['smartHttpTransportOptionsBoundary']['requestMethods'],
    'smartHttpConnectTimeout' => $fixture['smartHttpTransportOptionsBoundary']['getConnectTimeout'],
    'smartHttpLowSpeedBoundary' => [
        'limit' => $fixture['smartHttpTransportOptionsBoundary']['lowSpeedLimit'],
        'time' => $fixture['smartHttpTransportOptionsBoundary']['lowSpeedTime'],
    ],
    'smartHttpVersion' => $fixture['smartHttpTransportOptionsBoundary']['httpVersion'],
    'smartHttpVerboseEnabled' => $fixture['smartHttpTransportOptionsBoundary']['verbose'],
    'smartHttpTransportOptionsPostBodyPreserved' => $fixture['smartHttpTransportOptionsBoundary']['postBodyPreserved'],
    'smartHttpProtocolV2DiscoveryHeader' => $fixture['smartHttpProtocolHeaderBoundary']['v2DiscoveryGitProtocol'],
    'smartHttpProtocolV2PostHeader' => $fixture['smartHttpProtocolHeaderBoundary']['v2PostGitProtocol'],
    'smartHttpProtocolDowngradePostHeader' => $fixture['smartHttpProtocolHeaderBoundary']['downgradePostGitProtocol'],
    'smartHttpProtocolPostBodyPreserved' => $fixture['smartHttpProtocolHeaderBoundary']['v2PostBodyPreserved']
        && $fixture['smartHttpProtocolHeaderBoundary']['downgradePostBodyPreserved'],
    'smartHttpSamePortRedirectUrls' => $fixture['smartHttpSamePortRedirectBoundary']['requestUrls'],
    'smartHttpSamePortRedirectPostCookie' => $fixture['smartHttpSamePortRedirectBoundary']['postCookie'],
    'smartHttpSamePortRedirectPostBodyPreserved' => $fixture['smartHttpSamePortRedirectBoundary']['postBodyPreserved'],
    'smartHttpDifferentPortUpgradeRejected' => $fixture['smartHttpSamePortRedirectBoundary']['differentPortUpgradeRejected'],
    'smartHttpUnauthorizedStatusKind' => $fixture['smartHttpStatusBoundary']['unauthorized']['kind'],
    'smartHttpNotFoundStatusKind' => $fixture['smartHttpStatusBoundary']['notFound']['kind'],
    'smartHttpServerStatusRetryable' => $fixture['smartHttpStatusBoundary']['serverError']['retryable'],
    'smartHttpPostStatusKind' => $fixture['smartHttpStatusBoundary']['postServerError']['kind'],
    'streamWatchdogTimeoutReported' => $fixture['streamWatchdogTimeoutReported'],
    'advertisementErrorReported' => $fixture['advertisementErrorReported'],
    'oversizeAdvertisementRejected' => $fixture['oversizeAdvertisementRejected'],
    'unsafeSshTargetRejected' => $fixture['unsafeSshTargetRejected'],
    'unsafeSshHostDelimiterRejected' => $fixture['unsafeSshHostDelimiterRejected'],
    'unsafeSshUserDelimiterRejected' => $fixture['unsafeSshUserDelimiterRejected'],
    'unsafeSshScpIpv6UserRejected' => $fixture['unsafeSshScpIpv6UserRejected'],
    'unsafeSshEncodedUserDelimiterRejected' => $fixture['unsafeSshEncodedUserDelimiterRejected'],
    'unsafeSshPasswordRejected' => $fixture['unsafeSshPasswordRejected'],
    'unsafeSshLegacyHostRejected' => $fixture['unsafeSshLegacyHostRejected'],
    'unsafeSshNumericPortOverflowRejected' => $fixture['unsafeSshNumericPortOverflowRejected'],
    'unsafeSshAuthorityTooLongRejected' => $fixture['unsafeSshAuthorityTooLongRejected'],
    'unsafeSshFeatureProbeHostRejected' => $fixture['unsafeSshFeatureProbeHostRejected'],
    'unsafeSshFallbackCommandRejected' => $fixture['unsafeSshFallbackCommandRejected'],
    'unsafeSshIdentityUsernameRejected' => $fixture['unsafeSshIdentityUsernameRejected'],
    'unsafeSshIdentityClearedOptionHostRejected' => $fixture['unsafeSshIdentityClearedOptionHostRejected'],
];
