<?php

declare(strict_types=1);

require dirname(__DIR__, 3) . '/tools/bootstrap.php';

use PortLibs\Pandoc\MarkdownReader;
use PortLibs\Pandoc\PdfEngineHandoff;
use PortLibs\Pandoc\GzipStream;

$markdown = <<<'MARKDOWN'
---
title: "PDF Review Packet"
author: [Migration Desk]
date: 2026-06-04
---

Reviewer formula $E = mc^2$ and source cite \cite{migration-log}.

![Review chart](media/review-chart.png "Review chart")

![Remote reviewer media](https://example.test/media/remote-chart.png)
MARKDOWN;

$document = (new MarkdownReader())->read($markdown);
$handoff = new PdfEngineHandoff();
$plan = $handoff->plan($document, [
    'engine' => 'xelatex',
    'outputPath' => 'handoff/pdf-review-packet.pdf',
    'templatePath' => 'templates/review-packet.tex',
    'includeInHeader' => 'templates/review-header.tex',
    'resourcePaths' => ['media', 'review assets'],
    'resourceFiles' => ['refs/migration-log.bib', 'media/review-chart.png'],
    'variables' => [
        'documentclass' => 'scrartcl',
        'geometry' => ['margin=1in', 'includeheadfoot'],
        'colorlinks' => true,
        'mainfont' => 'Source Serif 4',
    ],
    'engineOptions' => ['-file-line-error', '-recorder', '-synctex=1'],
]);
$fakeXmpMetadata = implode("\n", [
    '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>',
    '<x:xmpmeta xmlns:x="adobe:ns:meta/">',
    '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">',
    '<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/">',
    '<dc:title><rdf:Alt><rdf:li xml:lang="x-default">PDF Review Packet</rdf:li></rdf:Alt></dc:title>',
    '<dc:creator><rdf:Seq><rdf:li>Migration Desk</rdf:li><rdf:li>Content Reviewer</rdf:li></rdf:Seq></dc:creator>',
    '<dc:description><rdf:Alt><rdf:li xml:lang="x-default">Migration review metadata</rdf:li></rdf:Alt></dc:description>',
    '<dc:format>application/pdf</dc:format>',
    '<xmp:CreatorTool>Pandoc native handoff</xmp:CreatorTool>',
    '<xmp:CreateDate>2026-06-05T07:41:23Z</xmp:CreateDate>',
    '<xmp:ModifyDate>2026-06-05T07:42:00Z</xmp:ModifyDate>',
    '<xmp:MetadataDate>2026-06-05T07:42:10Z</xmp:MetadataDate>',
    '<xmpMM:DocumentID>uuid:pdf-review-packet</xmpMM:DocumentID>',
    '<xmpMM:InstanceID>uuid:pdf-review-packet-v2</xmpMM:InstanceID>',
    '<pdfaid:part>2</pdfaid:part>',
    '<pdfaid:conformance>B</pdfaid:conformance>',
    '</rdf:Description>',
    '</rdf:RDF>',
    '</x:xmpmeta>',
    '<?xpacket end="w"?>',
]);
$fakeIccProfile = "fake sRGB ICC profile bytes\n";
$fakeEmbeddedAttachmentBytes = "fake embedded review assets\n";
$fakeEmbeddedFontBytes = "fake Source Serif PDF font bytes\n";
$fakeCatalogJavaScript = 'app.alert("Review packet requires active-content review")';
$fakePageJavaScript = 'this.print({bUI:false});';
$fakePdfBytes = implode("\n", [
    '%PDF-1.7',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R /Outlines 5 0 R /Lang (en-US) /Metadata 15 0 R /OutputIntents [17 0 R] /PageLayout /TwoPageRight /PageMode /UseOutlines /OpenAction [3 0 R /FitH 720] /ViewerPreferences << /DisplayDocTitle true /HideToolbar true /Direction /L2R /PrintScaling /None /NumCopies 2 >> /Names << /EmbeddedFiles << /Names [(review-assets.zip) 10 0 R] >> /JavaScript << /Names [(ReviewOpen) 19 0 R] >> /Dests << /Names [(review-start) [3 0 R /Fit] (import-checklist) [4 0 R /FitH 720]] >> >> /Dests << /packet-summary [3 0 R /FitH 720] >> /MarkInfo << /Marked true /UserProperties true /Suspects false >> /StructTreeRoot 22 0 R /PageLabels 27 0 R /AA << /WC 20 0 R >> /AcroForm 14 0 R >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Count 2 /MediaBox [0 0 612 792] /CropBox [18 18 594 774] /Rotate 0 /Kids [3 0 R 4 0 R] >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R /TrimBox [36 36 576 756] /BleedBox [9 9 603 783] /ArtBox [72 72 540 720] /Rotate 90 /Resources << /Font << /FReview 28 0 R /FBase 30 0 R >> >> /AA << /O 21 0 R >> /Annots [8 0 R 9 0 R 13 0 R] >>',
    'endobj',
    '4 0 obj',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /CropBox [24 24 768 588] /Rotate -90 >>',
    'endobj',
    '5 0 obj',
    '<< /Type /Outlines /First 6 0 R /Last 7 0 R /Count 2 >>',
    'endobj',
    '6 0 obj',
    '<< /Title (Review packet) /Parent 5 0 R /Dest [3 0 R /Fit] /Next 7 0 R >>',
    'endobj',
    '7 0 obj',
    '<< /Title <FEFF0049006D0070006F0072007400200063006800650063006B006C006900730074> /Parent 5 0 R /Dest [4 0 R /Fit] /Prev 6 0 R >>',
    'endobj',
    '8 0 obj',
    '<< /Type /Annot /Subtype /Link /A << /S /URI /URI (https://example.test/review/pdf-review-packet) >> >>',
    'endobj',
    '9 0 obj',
    '<< /Type /Annot /Subtype /FileAttachment /FS 10 0 R >>',
    'endobj',
    '10 0 obj',
    '<< /Type /Filespec /F (review-assets.zip) /UF <FEFF007200650076006900650077002D006100730073006500740073002E007A00690070> /Desc (Review source package) /AFRelationship /Data /EF << /F 11 0 R >> >>',
    'endobj',
    '11 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fzip /Params << /Size ' . strlen($fakeEmbeddedAttachmentBytes) . ' /ModDate (D:20260605120500Z) /CheckSum <00112233445566778899aabbccddeeff> >> /Length ' . strlen($fakeEmbeddedAttachmentBytes) . ' >>',
    'stream',
    $fakeEmbeddedAttachmentBytes,
    'endstream',
    'endobj',
    '12 0 obj',
    '<< /Title (PDF Review Packet) /Author <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Subject (Migration review) /Keywords (wordpress, migration) /Creator (Pandoc native handoff) /Producer (XeTeX fake runner) /CreationDate (D:20260605050300Z) /ModDate (D:20260605050400Z) /Trapped /False >>',
    'endobj',
    '13 0 obj',
    '<< /Type /Annot /Subtype /Widget /FT /Tx /T (reviewer.name) /TU (Reviewer name) /TM (reviewer_name) /V <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Ff 4098 >>',
    'endobj',
    '14 0 obj',
    '<< /Fields [13 0 R] /NeedAppearances true >>',
    'endobj',
    '15 0 obj',
    '<< /Type /Metadata /Subtype /XML /Length ' . strlen($fakeXmpMetadata) . ' >>',
    'stream',
    $fakeXmpMetadata,
    'endstream',
    'endobj',
    '17 0 obj',
    '<< /Type /OutputIntent /S /GTS_PDFA1 /OutputConditionIdentifier (sRGB IEC61966-2.1) /OutputCondition (sRGB display profile) /RegistryName (http://www.color.org) /Info (sRGB review profile) /DestOutputProfile 18 0 R >>',
    'endobj',
    '18 0 obj',
    '<< /N 3 /Alternate /DeviceRGB /Length ' . strlen($fakeIccProfile) . ' >>',
    'stream',
    $fakeIccProfile,
    'endstream',
    'endobj',
    '19 0 obj',
    '<< /S /JavaScript /JS (' . str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $fakeCatalogJavaScript) . ') >>',
    'endobj',
    '20 0 obj',
    '<< /S /Launch /F (review-helper.exe) >>',
    'endobj',
    '21 0 obj',
    '<< /S /JavaScript /JS <' . strtoupper(bin2hex($fakePageJavaScript)) . '> >>',
    'endobj',
    '22 0 obj',
    '<< /Type /StructTreeRoot /K [23 0 R 24 0 R] /RoleMap << /H1 /H /Aside /Sect /Figure /Figure >> /ParentTree 25 0 R /ParentTreeNextKey 5 /IDTree 26 0 R >>',
    'endobj',
    '23 0 obj',
    '<< /Type /StructElem /S /H1 /P 22 0 R /K 0 >>',
    'endobj',
    '24 0 obj',
    '<< /Type /StructElem /S /P /P 22 0 R /K 1 >>',
    'endobj',
    '25 0 obj',
    '<< /Nums [0 [23 0 R] 1 [24 0 R]] >>',
    'endobj',
    '26 0 obj',
    '<< /Names [(intro) 23 0 R (body) 24 0 R] >>',
    'endobj',
    '27 0 obj',
    '<< /Nums [0 << /S /r /P (front-) /St 3 >> 1 << /S /D /P (packet-) /St 1 >>] >>',
    'endobj',
    '28 0 obj',
    '<< /Type /Font /Subtype /Type0 /BaseFont /ABCDEE+SourceSerif4-Regular /Encoding /Identity-H /DescendantFonts [29 0 R] /ToUnicode 31 0 R >>',
    'endobj',
    '29 0 obj',
    '<< /Type /Font /Subtype /CIDFontType2 /BaseFont /ABCDEE+SourceSerif4-Regular /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor 32 0 R >>',
    'endobj',
    '30 0 obj',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
    'endobj',
    '31 0 obj',
    '<< /Length 24 >>',
    'stream',
    '/CIDInit /ProcSet findresource',
    'endstream',
    'endobj',
    '32 0 obj',
    '<< /Type /FontDescriptor /FontName /ABCDEE+SourceSerif4-Regular /FontFamily (Source Serif 4) /Flags 4 /FontWeight 400 /ItalicAngle 0 /FontFile2 33 0 R >>',
    'endobj',
    '33 0 obj',
    '<< /Length ' . strlen($fakeEmbeddedFontBytes) . ' >>',
    'stream',
    $fakeEmbeddedFontBytes,
    'endstream',
    'endobj',
    'trailer',
    '<< /Size 34 /Root 1 0 R /Info 12 0 R /ID [<00112233445566778899aabbccddeeff> <00112233445566778899aabbccddeeff>] >>',
    'startxref',
    '512',
    '%%EOF',
    '16 0 obj',
    '<< /Title (PDF Review Packet Appended) /Producer (WordPress review appender) >>',
    'endobj',
    'trailer',
    '<< /Size 34 /Root 1 0 R /Info 16 0 R /Prev 512 /ID [<00112233445566778899aabbccddeeff> <ffeeddccbbaa99887766554433221100>] >>',
    'startxref',
    '1024',
    '%%EOF',
    '',
]);
$fakeLog = implode("\n", [
    'This is XeTeX, Version 3.141592653',
    '(./handoff/pdf-review-packet.tex',
    '(./templates/review-packet.tex',
    '(./templates/review-header.tex',
    '(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls)',
    '(./media/review-chart.png)',
    "LaTeX Warning: Citation `migration-log' on page 1 undefined on input line 4.",
    'LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.',
    'Output written on handoff/pdf-review-packet.pdf (2 pages, ' . strlen($fakePdfBytes) . ' bytes).',
    '',
]);
$fakeRecorderFile = implode("\n", [
    'PWD /tmp/pandoc-pdf-review',
    'INPUT handoff/pdf-review-packet.tex',
    'INPUT templates/review-packet.tex',
    'INPUT templates/review-header.tex',
    'INPUT media/review-chart.png',
    'INPUT refs/migration-log.bib',
    'INPUT /usr/share/texlive/texmf-dist/tex/latex/base/article.cls',
    'OUTPUT handoff/pdf-review-packet.aux',
    'OUTPUT handoff/pdf-review-packet.bcf',
    'OUTPUT handoff/pdf-review-packet.log',
    'OUTPUT handoff/pdf-review-packet.out',
    'OUTPUT handoff/pdf-review-packet.pdf',
    'OUTPUT handoff/pdf-review-packet.run.xml',
    'OUTPUT handoff/pdf-review-packet.synctex.gz',
    '',
]);
$fakeSourceMap = implode("\n", [
    'SyncTeX Version:1',
    'Input:1:handoff/pdf-review-packet.tex',
    'Input:2:templates/review-header.tex',
    'Output:pdf',
    'Content:',
    '[1,4:100,200:300,400',
    '(2,1:120,240',
    '',
]);
$fakeSourceMapBytes = GzipStream::build($fakeSourceMap, ['filename' => 'pdf-review-packet.synctex']);
$fakeBibliographyLog = implode("\n", [
    'This is Biber 2.19',
    'Biber warning: Entry migration-log not found in bibliography',
    'Package biblatex Warning: Please (re)run Biber on the file: pdf-review-packet and rerun LaTeX afterwards.',
    '',
]);
$fakeFirstRun = [
    'stdout' => 'fake xelatex runner accepted the planned argv',
    'files' => [
        $plan['sourceFile'] => (string) $plan['sourceBytes'],
        'templates/review-packet.tex' => '\documentclass{$documentclass$}' . "\n" . '$for(include-in-header)$$include-in-header$$endfor$' . "\n" . '\begin{document}$body$\end{document}',
        'templates/review-header.tex' => '\usepackage{fontspec}',
        'media/review-chart.png' => 'fake review chart bytes',
        'refs/migration-log.bib' => '@book{migration-log,title={Migration Log}}',
        'handoff/pdf-review-packet.aux' => "\\relax\n",
        'handoff/pdf-review-packet.bcf' => '<bcf:controlfile />',
        'handoff/pdf-review-packet.run.xml' => '<requests />',
        'handoff/pdf-review-packet.blg' => $fakeBibliographyLog,
        'handoff/pdf-review-packet.out' => "\n",
        'handoff/pdf-review-packet.fls' => $fakeRecorderFile,
        'handoff/pdf-review-packet.synctex.gz' => $fakeSourceMapBytes,
        'handoff/pdf-review-packet.log' => $fakeLog,
        $plan['outputFile'] => $fakePdfBytes,
    ],
];
$fakeResult = $handoff->fakeRun($plan, $fakeFirstRun);
$fakeProtectedPdfBytes = implode("\n", [
    '%PDF-1.7',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Count 1 /Kids [3 0 R] >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R >>',
    'endobj',
    '12 0 obj',
    '<< /Filter /Standard /V 4 /R 4 /Length 128 /P -44 /EncryptMetadata false >>',
    'endobj',
    'trailer',
    '<< /Root 1 0 R /Encrypt 12 0 R >>',
    '%%EOF',
    '',
]);
$fakeProtectedPdf = $handoff->fakeRun($plan, [
    'files' => [
        $plan['sourceFile'] => (string) $plan['sourceBytes'],
        'templates/review-packet.tex' => '\documentclass{$documentclass$}' . "\n" . '$body$',
        'templates/review-header.tex' => '\usepackage{fontspec}',
        'media/review-chart.png' => 'fake review chart bytes',
        'refs/migration-log.bib' => '@book{migration-log,title={Migration Log}}',
        $plan['outputFile'] => $fakeProtectedPdfBytes,
    ],
]);
$fakeMissingProgram = $handoff->fakeRun($plan, [
    'exitCode' => 127,
    'stderr' => "xelatex: command not found\n",
]);
$fakeFinalPdfBytes = implode("\n", [
    '%PDF-1.7',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R /Outlines 5 0 R /Lang (en-US) /Metadata 15 0 R /OutputIntents [17 0 R] /PageLayout /TwoPageRight /PageMode /UseOutlines /OpenAction [3 0 R /FitH 720] /ViewerPreferences << /DisplayDocTitle true /HideToolbar true /Direction /L2R /PrintScaling /None /NumCopies 2 >> /Names << /EmbeddedFiles << /Names [(review-assets.zip) 10 0 R] >> /JavaScript << /Names [(ReviewOpen) 19 0 R] >> /Dests << /Names [(review-start) [3 0 R /Fit] (import-checklist) [4 0 R /FitH 720]] >> >> /Dests << /packet-summary [3 0 R /FitH 720] >> /MarkInfo << /Marked true /UserProperties true /Suspects false >> /StructTreeRoot 22 0 R /PageLabels 27 0 R /AA << /WC 20 0 R >> /AcroForm 14 0 R >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Count 2 /MediaBox [0 0 612 792] /CropBox [18 18 594 774] /Rotate 0 /Kids [3 0 R 4 0 R] >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R /TrimBox [36 36 576 756] /BleedBox [9 9 603 783] /ArtBox [72 72 540 720] /Rotate 90 /AA << /O 21 0 R >> /Annots [8 0 R 9 0 R 13 0 R] >>',
    'endobj',
    '4 0 obj',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /CropBox [24 24 768 588] /Rotate -90 >>',
    'endobj',
    '5 0 obj',
    '<< /Type /Outlines /First 6 0 R /Last 7 0 R /Count 2 >>',
    'endobj',
    '6 0 obj',
    '<< /Title (Review packet) /Parent 5 0 R /Dest [3 0 R /Fit] /Next 7 0 R >>',
    'endobj',
    '7 0 obj',
    '<< /Title <FEFF0049006D0070006F0072007400200063006800650063006B006C006900730074> /Parent 5 0 R /Dest [4 0 R /Fit] /Prev 6 0 R >>',
    'endobj',
    '8 0 obj',
    '<< /Type /Annot /Subtype /Link /A << /S /URI /URI (https://example.test/review/pdf-review-packet) >> >>',
    'endobj',
    '9 0 obj',
    '<< /Type /Annot /Subtype /FileAttachment /FS 10 0 R >>',
    'endobj',
    '10 0 obj',
    '<< /Type /Filespec /F (review-assets.zip) /UF <FEFF007200650076006900650077002D006100730073006500740073002E007A00690070> /Desc (Review source package) /AFRelationship /Data /EF << /F 11 0 R >> >>',
    'endobj',
    '11 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fzip /Params << /Size ' . strlen($fakeEmbeddedAttachmentBytes) . ' /ModDate (D:20260605120500Z) /CheckSum <00112233445566778899aabbccddeeff> >> /Length ' . strlen($fakeEmbeddedAttachmentBytes) . ' >>',
    'stream',
    $fakeEmbeddedAttachmentBytes,
    'endstream',
    'endobj',
    '12 0 obj',
    '<< /Title (PDF Review Packet) /Author <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Subject (Migration review) /Keywords (wordpress, migration) /Creator (Pandoc native handoff) /Producer (XeTeX fake runner) /CreationDate (D:20260605050300Z) /ModDate (D:20260605050400Z) /Trapped /False >>',
    'endobj',
    '13 0 obj',
    '<< /Type /Annot /Subtype /Widget /FT /Tx /T (reviewer.name) /TU (Reviewer name) /TM (reviewer_name) /V <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Ff 4098 >>',
    'endobj',
    '14 0 obj',
    '<< /Fields [13 0 R] /NeedAppearances true >>',
    'endobj',
    '15 0 obj',
    '<< /Type /Metadata /Subtype /XML /Length ' . strlen($fakeXmpMetadata) . ' >>',
    'stream',
    $fakeXmpMetadata,
    'endstream',
    'endobj',
    '17 0 obj',
    '<< /Type /OutputIntent /S /GTS_PDFA1 /OutputConditionIdentifier (sRGB IEC61966-2.1) /OutputCondition (sRGB display profile) /RegistryName (http://www.color.org) /Info (sRGB review profile) /DestOutputProfile 18 0 R >>',
    'endobj',
    '18 0 obj',
    '<< /N 3 /Alternate /DeviceRGB /Length ' . strlen($fakeIccProfile) . ' >>',
    'stream',
    $fakeIccProfile,
    'endstream',
    'endobj',
    '19 0 obj',
    '<< /S /JavaScript /JS (' . str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $fakeCatalogJavaScript) . ') >>',
    'endobj',
    '20 0 obj',
    '<< /S /Launch /F (review-helper.exe) >>',
    'endobj',
    '21 0 obj',
    '<< /S /JavaScript /JS <' . strtoupper(bin2hex($fakePageJavaScript)) . '> >>',
    'endobj',
    '22 0 obj',
    '<< /Type /StructTreeRoot /K [23 0 R 24 0 R] /RoleMap << /H1 /H /Aside /Sect /Figure /Figure >> /ParentTree 25 0 R /ParentTreeNextKey 5 /IDTree 26 0 R >>',
    'endobj',
    '23 0 obj',
    '<< /Type /StructElem /S /H1 /P 22 0 R /K 0 >>',
    'endobj',
    '24 0 obj',
    '<< /Type /StructElem /S /P /P 22 0 R /K 1 >>',
    'endobj',
    '25 0 obj',
    '<< /Nums [0 [23 0 R] 1 [24 0 R]] >>',
    'endobj',
    '26 0 obj',
    '<< /Names [(intro) 23 0 R (body) 24 0 R] >>',
    'endobj',
    '27 0 obj',
    '<< /Nums [0 << /S /r /P (front-) /St 3 >> 1 << /S /D /P (packet-) /St 1 >>] >>',
    'endobj',
    'trailer',
    '<< /Size 28 /Root 1 0 R /Info 12 0 R /ID [<00112233445566778899aabbccddeeff> <00112233445566778899aabbccddeeff>] >>',
    'startxref',
    '512',
    '%%EOF',
    '16 0 obj',
    '<< /Title (PDF Review Packet Appended) /Producer (WordPress review appender) >>',
    'endobj',
    'trailer',
    '<< /Size 28 /Root 1 0 R /Info 16 0 R /Prev 512 /ID [<00112233445566778899aabbccddeeff> <ffeeddccbbaa99887766554433221100>] >>',
    'startxref',
    '1024',
    '%%EOF',
    '',
]);
$fakeFinalLog = implode("\n", [
    'This is XeTeX, Version 3.141592653',
    '(./handoff/pdf-review-packet.tex',
    '(./templates/review-packet.tex',
    '(./templates/review-header.tex',
    '(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls)',
    '(./media/review-chart.png)',
    'Output written on handoff/pdf-review-packet.pdf (2 pages, ' . strlen($fakeFinalPdfBytes) . ' bytes).',
    '',
]);
$fakeSequence = $handoff->fakeRunSequence($plan, [
    $fakeFirstRun,
    [
        'stdout' => 'fake xelatex runner accepted the final planned argv',
        'files' => [
            $plan['sourceFile'] => (string) $plan['sourceBytes'],
            'templates/review-packet.tex' => '\documentclass{$documentclass$}' . "\n" . '$for(include-in-header)$$include-in-header$$endfor$' . "\n" . '\begin{document}$body$\end{document}',
            'templates/review-header.tex' => '\usepackage{fontspec}',
            'media/review-chart.png' => 'fake review chart bytes',
            'refs/migration-log.bib' => '@book{migration-log,title={Migration Log}}',
            'handoff/pdf-review-packet.aux' => "\\relax\n\\citation{migration-log}\n",
            'handoff/pdf-review-packet.bbl' => "\\begin{thebibliography}{1}\n\\end{thebibliography}\n",
            'handoff/pdf-review-packet.blg' => "This is Biber 2.19\n",
            'handoff/pdf-review-packet.out' => "\n",
            'handoff/pdf-review-packet.fls' => $fakeRecorderFile,
            'handoff/pdf-review-packet.synctex.gz' => $fakeSourceMapBytes,
            'handoff/pdf-review-packet.log' => $fakeFinalLog,
            $plan['outputFile'] => $fakeFinalPdfBytes,
        ],
    ],
]);

$summary = [
    'engine' => $plan['engine'],
    'intermediateFormat' => $plan['intermediateFormat'],
    'sourceFile' => $plan['sourceFile'],
    'outputFile' => $plan['outputFile'],
    'argv' => $plan['argv'],
    'writerArguments' => $plan['writerArguments'],
    'templateFile' => $plan['templateFile'],
    'includeInHeaderFiles' => $plan['includeInHeaderFiles'],
    'resourcePaths' => $plan['resourcePaths'],
    'resourceFiles' => $plan['resourceFiles'],
    'resourceFileManifest' => $plan['resourceFileManifest'],
    'remoteResourceReferences' => $plan['remoteResourceReferences'],
    'skippedResourceReferences' => $plan['skippedResourceReferences'],
    'sourceArtifacts' => $plan['sourceArtifacts'],
    'engineLogFile' => $plan['engineLogFile'],
    'expectedEngineArtifacts' => $plan['expectedEngineArtifacts'],
    'templateVariables' => $plan['templateVariables'],
    'metadata' => $plan['metadata'],
    'sourceSha256' => $plan['sourceSha256'],
    'fakeRun' => [
        'ok' => $fakeResult['ok'],
        'reason' => $fakeResult['reason'],
        'bytes' => $fakeResult['bytes'],
        'sourceArtifactsSha256' => $fakeResult['sourceArtifactsSha256'],
        'resourceArtifactsSha256' => $fakeResult['resourceArtifactsSha256'],
        'missingResourceFiles' => $fakeResult['missingResourceFiles'],
        'producedArtifactsSha256' => $fakeResult['producedArtifactsSha256'],
        'engineDependencyArtifactsSha256' => $fakeResult['engineDependencyArtifactsSha256'],
        'engineInputFiles' => $fakeResult['engineInputFiles'],
        'engineExternalInputFiles' => $fakeResult['engineExternalInputFiles'],
        'engineOutputFiles' => $fakeResult['engineOutputFiles'],
        'engineTranscriptInputFiles' => $fakeResult['engineTranscriptInputFiles'],
        'engineTranscriptExternalInputFiles' => $fakeResult['engineTranscriptExternalInputFiles'],
        'missingEngineInputFiles' => $fakeResult['missingEngineInputFiles'],
        'missingEngineTranscriptInputFiles' => $fakeResult['missingEngineTranscriptInputFiles'],
        'bibliographyArtifactsSha256' => $fakeResult['bibliographyArtifactsSha256'],
        'bibliographyLogFiles' => $fakeResult['bibliographyLogFiles'],
        'sourceMapArtifactsSha256' => $fakeResult['sourceMapArtifactsSha256'],
        'sourceMapFiles' => $fakeResult['sourceMapFiles'],
        'sourceMapInputs' => $fakeResult['sourceMapInputs'],
        'sourceMapInputFiles' => $fakeResult['sourceMapInputFiles'],
        'sourceMapExternalInputs' => $fakeResult['sourceMapExternalInputs'],
        'sourceMapLineRanges' => $fakeResult['sourceMapLineRanges'],
        'engineLogFiles' => $fakeResult['engineLogFiles'],
        'engineWarnings' => $fakeResult['engineWarnings'],
        'engineErrors' => $fakeResult['engineErrors'],
        'bibliographyWarnings' => $fakeResult['bibliographyWarnings'],
        'bibliographyErrors' => $fakeResult['bibliographyErrors'],
        'bibliographyNeeded' => $fakeResult['bibliographyNeeded'],
        'rerunNeeded' => $fakeResult['rerunNeeded'],
        'declaredOutputFile' => $fakeResult['declaredOutputFile'],
        'declaredOutputPages' => $fakeResult['declaredOutputPages'],
        'declaredOutputBytes' => $fakeResult['declaredOutputBytes'],
        'pdfTrailerComplete' => $fakeResult['pdfTrailerComplete'],
        'pdfTrailerCount' => $fakeResult['pdfTrailerCount'],
        'pdfTrailerRevisions' => $fakeResult['pdfTrailerRevisions'],
        'pdfStartXrefOffsets' => $fakeResult['pdfStartXrefOffsets'],
        'pdfIncrementalUpdates' => $fakeResult['pdfIncrementalUpdates'],
        'pdfPageCount' => $fakeResult['pdfPageCount'],
        'pdfPageBoxes' => $fakeResult['pdfPageBoxes'],
        'pdfPageRotations' => $fakeResult['pdfPageRotations'],
        'pdfPageLabels' => $fakeResult['pdfPageLabels'],
        'pdfFonts' => $fakeResult['pdfFonts'],
        'pdfFontSubtypes' => $fakeResult['pdfFontSubtypes'],
        'pdfOutlineTitles' => $fakeResult['pdfOutlineTitles'],
        'pdfDocumentInfo' => $fakeResult['pdfDocumentInfo'],
        'pdfXmpMetadata' => $fakeResult['pdfXmpMetadata'],
        'pdfOutputIntents' => $fakeResult['pdfOutputIntents'],
        'pdfLanguage' => $fakeResult['pdfLanguage'],
        'pdfPageLayout' => $fakeResult['pdfPageLayout'],
        'pdfPageMode' => $fakeResult['pdfPageMode'],
        'pdfOpenAction' => $fakeResult['pdfOpenAction'],
        'pdfNamedDestinations' => $fakeResult['pdfNamedDestinations'],
        'pdfViewerPreferences' => $fakeResult['pdfViewerPreferences'],
        'pdfTaggingMetadata' => $fakeResult['pdfTaggingMetadata'],
        'pdfActiveActions' => $fakeResult['pdfActiveActions'],
        'pdfActiveActionTypes' => $fakeResult['pdfActiveActionTypes'],
        'pdfAnnotationTypes' => $fakeResult['pdfAnnotationTypes'],
        'pdfLinkTargets' => $fakeResult['pdfLinkTargets'],
        'pdfEmbeddedFileNames' => $fakeResult['pdfEmbeddedFileNames'],
        'pdfEmbeddedFiles' => $fakeResult['pdfEmbeddedFiles'],
        'pdfFormFields' => $fakeResult['pdfFormFields'],
        'pdfFormFieldTypes' => $fakeResult['pdfFormFieldTypes'],
        'pdfEncrypted' => $fakeResult['pdfEncrypted'],
        'pdfEncryptionFilter' => $fakeResult['pdfEncryptionFilter'],
        'pdfEncryptionVersion' => $fakeResult['pdfEncryptionVersion'],
        'pdfEncryptionRevision' => $fakeResult['pdfEncryptionRevision'],
        'pdfEncryptionLength' => $fakeResult['pdfEncryptionLength'],
        'pdfPermissionInteger' => $fakeResult['pdfPermissionInteger'],
        'pdfPermissionFlags' => $fakeResult['pdfPermissionFlags'],
        'pdfEncryptMetadata' => $fakeResult['pdfEncryptMetadata'],
        'diagnostics' => $fakeResult['diagnostics'],
    ],
    'fakeProtectedPdf' => [
        'ok' => $fakeProtectedPdf['ok'],
        'reason' => $fakeProtectedPdf['reason'],
        'pdfEncrypted' => $fakeProtectedPdf['pdfEncrypted'],
        'pdfEncryptionFilter' => $fakeProtectedPdf['pdfEncryptionFilter'],
        'pdfEncryptionVersion' => $fakeProtectedPdf['pdfEncryptionVersion'],
        'pdfEncryptionRevision' => $fakeProtectedPdf['pdfEncryptionRevision'],
        'pdfEncryptionLength' => $fakeProtectedPdf['pdfEncryptionLength'],
        'pdfPermissionInteger' => $fakeProtectedPdf['pdfPermissionInteger'],
        'pdfPermissionFlags' => $fakeProtectedPdf['pdfPermissionFlags'],
        'pdfEncryptMetadata' => $fakeProtectedPdf['pdfEncryptMetadata'],
        'diagnostics' => $fakeProtectedPdf['diagnostics'],
    ],
    'fakeMissingProgram' => [
        'ok' => $fakeMissingProgram['ok'],
        'reason' => $fakeMissingProgram['reason'],
        'engineMissingProgram' => $fakeMissingProgram['engineMissingProgram'],
        'engineMissingProgramName' => $fakeMissingProgram['engineMissingProgramName'],
        'diagnostics' => $fakeMissingProgram['diagnostics'],
    ],
    'fakeRunSequence' => [
        'ok' => $fakeSequence['ok'],
        'reason' => $fakeSequence['reason'],
        'attempts' => $fakeSequence['attempts'],
        'successfulAttempts' => $fakeSequence['successfulAttempts'],
        'finalRunIndex' => $fakeSequence['finalRunIndex'],
        'finalBytes' => $fakeSequence['finalBytes'],
        'finalPdfSha256' => $fakeSequence['finalPdfSha256'],
        'finalResourceArtifactsSha256' => $fakeSequence['finalResourceArtifactsSha256'],
        'finalEngineDependencyArtifactsSha256' => $fakeSequence['finalEngineDependencyArtifactsSha256'],
        'finalEngineInputFiles' => $fakeSequence['finalEngineInputFiles'],
        'finalEngineExternalInputFiles' => $fakeSequence['finalEngineExternalInputFiles'],
        'finalEngineOutputFiles' => $fakeSequence['finalEngineOutputFiles'],
        'finalEngineTranscriptInputFiles' => $fakeSequence['finalEngineTranscriptInputFiles'],
        'finalEngineTranscriptExternalInputFiles' => $fakeSequence['finalEngineTranscriptExternalInputFiles'],
        'finalBibliographyArtifactsSha256' => $fakeSequence['finalBibliographyArtifactsSha256'],
        'finalSourceMapArtifactsSha256' => $fakeSequence['finalSourceMapArtifactsSha256'],
        'finalSourceMapFiles' => $fakeSequence['finalSourceMapFiles'],
        'finalSourceMapInputs' => $fakeSequence['finalSourceMapInputs'],
        'finalSourceMapLineRanges' => $fakeSequence['finalSourceMapLineRanges'],
        'missingResourceFiles' => $fakeSequence['missingResourceFiles'],
        'finalDeclaredOutputPages' => $fakeSequence['finalDeclaredOutputPages'],
        'finalPdfPageCount' => $fakeSequence['finalPdfPageCount'],
        'finalPdfTrailerCount' => $fakeSequence['finalPdfTrailerCount'],
        'finalPdfTrailerRevisions' => $fakeSequence['finalPdfTrailerRevisions'],
        'finalPdfStartXrefOffsets' => $fakeSequence['finalPdfStartXrefOffsets'],
        'finalPdfIncrementalUpdates' => $fakeSequence['finalPdfIncrementalUpdates'],
        'finalPdfPageBoxes' => $fakeSequence['finalPdfPageBoxes'],
        'finalPdfPageRotations' => $fakeSequence['finalPdfPageRotations'],
        'finalPdfPageLabels' => $fakeSequence['finalPdfPageLabels'],
        'finalPdfFonts' => $fakeSequence['finalPdfFonts'],
        'finalPdfFontSubtypes' => $fakeSequence['finalPdfFontSubtypes'],
        'finalPdfOutlineTitles' => $fakeSequence['finalPdfOutlineTitles'],
        'finalPdfDocumentInfo' => $fakeSequence['finalPdfDocumentInfo'],
        'finalPdfXmpMetadata' => $fakeSequence['finalPdfXmpMetadata'],
        'finalPdfOutputIntents' => $fakeSequence['finalPdfOutputIntents'],
        'finalPdfLanguage' => $fakeSequence['finalPdfLanguage'],
        'finalPdfPageLayout' => $fakeSequence['finalPdfPageLayout'],
        'finalPdfPageMode' => $fakeSequence['finalPdfPageMode'],
        'finalPdfOpenAction' => $fakeSequence['finalPdfOpenAction'],
        'finalPdfNamedDestinations' => $fakeSequence['finalPdfNamedDestinations'],
        'finalPdfViewerPreferences' => $fakeSequence['finalPdfViewerPreferences'],
        'finalPdfTaggingMetadata' => $fakeSequence['finalPdfTaggingMetadata'],
        'finalPdfActiveActions' => $fakeSequence['finalPdfActiveActions'],
        'finalPdfActiveActionTypes' => $fakeSequence['finalPdfActiveActionTypes'],
        'finalPdfAnnotationTypes' => $fakeSequence['finalPdfAnnotationTypes'],
        'finalPdfLinkTargets' => $fakeSequence['finalPdfLinkTargets'],
        'finalPdfEmbeddedFileNames' => $fakeSequence['finalPdfEmbeddedFileNames'],
        'finalPdfEmbeddedFiles' => $fakeSequence['finalPdfEmbeddedFiles'],
        'finalPdfFormFields' => $fakeSequence['finalPdfFormFields'],
        'finalPdfFormFieldTypes' => $fakeSequence['finalPdfFormFieldTypes'],
        'finalPdfEncrypted' => $fakeSequence['finalPdfEncrypted'],
        'finalPdfEncryptionFilter' => $fakeSequence['finalPdfEncryptionFilter'],
        'finalPdfEncryptionVersion' => $fakeSequence['finalPdfEncryptionVersion'],
        'finalPdfEncryptionRevision' => $fakeSequence['finalPdfEncryptionRevision'],
        'finalPdfEncryptionLength' => $fakeSequence['finalPdfEncryptionLength'],
        'finalPdfPermissionInteger' => $fakeSequence['finalPdfPermissionInteger'],
        'finalPdfPermissionFlags' => $fakeSequence['finalPdfPermissionFlags'],
        'finalPdfEncryptMetadata' => $fakeSequence['finalPdfEncryptMetadata'],
        'bibliographyWarnings' => $fakeSequence['bibliographyWarnings'],
        'bibliographyErrors' => $fakeSequence['bibliographyErrors'],
        'bibliographyNeeded' => $fakeSequence['bibliographyNeeded'],
        'rerunNeeded' => $fakeSequence['rerunNeeded'],
        'engineWarnings' => $fakeSequence['engineWarnings'],
        'diagnostics' => $fakeSequence['diagnostics'],
    ],
];

if (in_array('--self-test', $argv, true)) {
    foreach ([
        'xelatex',
        'latex',
        'handoff/pdf-review-packet.tex',
        'handoff/pdf-review-packet.pdf',
        'PDF Review Packet',
        'templates/review-packet.tex',
        'templates/review-header.tex',
        'media/review-chart.png',
        'refs/migration-log.bib',
        'https://example.test/media/remote-chart.png',
        'handoff/pdf-review-packet.log',
        'handoff/pdf-review-packet.aux',
        'handoff/pdf-review-packet.bcf',
        'handoff/pdf-review-packet.bbl',
        'handoff/pdf-review-packet.blg',
        'handoff/pdf-review-packet.run.xml',
        'handoff/pdf-review-packet.fls',
        'handoff/pdf-review-packet.synctex.gz',
        'documentclass=scrartcl',
        '-recorder',
        '-synctex=1',
        '--resource-path=media:review assets',
        'Source Serif 4',
        'resourceFileManifest',
        'pdf-resource-files:2',
        'pdf-remote-resources:1',
        'source-artifacts-validated:2',
        'resource-files-validated:2',
        'resourceArtifactsSha256',
        'produced-engine-artifacts:8',
        'engineDependencyArtifactsSha256',
        'engineInputFiles',
        'engineExternalInputFiles',
        'engineOutputFiles',
        'engineTranscriptInputFiles',
        'engineTranscriptExternalInputFiles',
        'missingEngineTranscriptInputFiles',
        'engine-dependency-artifacts:1',
        'engine-dependency-files:5',
        'engine-external-input-files:1',
        'engine-output-files:7',
        'engine-transcript-input-files:4',
        'engine-transcript-external-input-files:1',
        'article.cls',
        'bibliography-sidecars:3',
        'bibliography-log-files:1',
        'source-map-files:1',
        'source-map-inputs:2',
        'source-map-line-ranges:2',
        'sourceMapArtifactsSha256',
        'sourceMapLineRanges',
        'bibliography-warnings:3',
        'bibliography-run-needed',
        'engine-log-warnings:2',
        'engine-rerun-needed',
        'engine-output-file:handoff/pdf-review-packet.pdf',
        'engine-output-pages:2',
        'pdfTrailerComplete',
        'pdfTrailerCount',
        '"pdfTrailerCount":2',
        'pdfTrailerRevisions',
        '"prev":512',
        '"startxref":1024',
        'pdfStartXrefOffsets',
        '"pdfStartXrefOffsets":[512,1024]',
        'pdfIncrementalUpdates',
        '"pdfIncrementalUpdates":true',
        'pdf-byte-trailers:2',
        'pdf-byte-startxref:2',
        'pdf-byte-incremental-updates',
        'pdfPageCount',
        '"pdfPageCount":2',
        'pdfPageBoxes',
        '"pageObject":"3 0 R"',
        '"mediaBox":[0,0,612,792]',
        '"cropBox":[18,18,594,774]',
        '"trimBox":[36,36,576,756]',
        '"artBox":[72,72,540,720]',
        '"rotation":90',
        '"inherited":["cropBox","mediaBox"]',
        'pdfPageRotations',
        '"pdfPageRotations":{"1":90,"2":270}',
        'pdfPageLabels',
        'finalPdfPageLabels',
        '"styleLabel":"lower-roman"',
        '"firstLabel":"front-iii"',
        '"styleLabel":"decimal"',
        '"firstLabel":"packet-1"',
        'pdf-byte-page-labels:2',
        'pdfFonts',
        'finalPdfFonts',
        '"resourceName":"FReview"',
        '"baseFont":"ABCDEE+SourceSerif4-Regular"',
        '"descriptorFontFamily":"Source Serif 4"',
        '"embeddedFileKind":"FontFile2"',
        '"embeddedFile":"33 0 R"',
        'pdfFontSubtypes',
        'finalPdfFontSubtypes',
        '"Type0":1',
        '"Type1":1',
        'pdf-byte-font-resources:2',
        'pdf-byte-font-subtypes:2',
        'pdf-byte-embedded-fonts:1',
        'pdf-byte-page-boxes:2',
        'pdf-byte-page-rotations:2',
        'pdfOutlineTitles',
        'Review packet',
        'Import checklist',
        'pdfDocumentInfo',
        '"Title":"PDF Review Packet"',
        '"Author":"Migration Desk"',
        '"Producer":"XeTeX fake runner"',
        'pdfXmpMetadata',
        '"packetSha256"',
        '"title":"PDF Review Packet"',
        '"description":"Migration review metadata"',
        '"format":"application/pdf"',
        '"creatorTool":"Pandoc native handoff"',
        '"createDate":"2026-06-05T07:41:23Z"',
        '"modifyDate":"2026-06-05T07:42:00Z"',
        '"metadataDate":"2026-06-05T07:42:10Z"',
        '"documentId":"uuid:pdf-review-packet"',
        '"instanceId":"uuid:pdf-review-packet-v2"',
        '"creators":["Migration Desk","Content Reviewer"]',
        '"pdfaIdentification":{"part":"2","conformance":"B"}',
        'pdf-byte-xmp-metadata:13',
        'pdf-byte-pdfa:2:B',
        'pdfOutputIntents',
        '"subtype":"GTS_PDFA1"',
        '"outputConditionIdentifier":"sRGB IEC61966-2.1"',
        '"outputCondition":"sRGB display profile"',
        '"registryName":"http://www.color.org"',
        '"info":"sRGB review profile"',
        '"destOutputProfile":"18 0 R"',
        '"profileComponents":3',
        '"profileAlternate":"DeviceRGB"',
        '"profileSha256"',
        'pdf-byte-output-intents:1',
        'pdf-byte-output-profiles:1',
        'pdfLanguage',
        '"pdfLanguage":"en-US"',
        'pdf-byte-document-info:9',
        'pdf-byte-language:en-US',
        'pdfPageLayout',
        '"pdfPageLayout":"TwoPageRight"',
        'pdfPageMode',
        '"pdfPageMode":"UseOutlines"',
        'pdfOpenAction',
        '"pageObject":"3 0 R"',
        '"fit":"FitH"',
        'pdfNamedDestinations',
        'finalPdfNamedDestinations',
        'catalog.Names.Dests',
        'catalog.Dests',
        'review-start',
        'import-checklist',
        'packet-summary',
        'pdf-byte-named-destinations:3',
        'pdfViewerPreferences',
        '"DisplayDocTitle":true',
        '"HideToolbar":true',
        '"Direction":"L2R"',
        '"PrintScaling":"None"',
        '"NumCopies":2',
        'pdf-byte-page-layout:TwoPageRight',
        'pdf-byte-page-mode:UseOutlines',
        'pdf-byte-open-action:destination',
        'pdf-byte-viewer-preferences:5',
        'pdfTaggingMetadata',
        'finalPdfTaggingMetadata',
        '"marked":true',
        '"userProperties":true',
        '"suspects":false',
        '"structTreeRoot":"22 0 R"',
        '"roleMap":{"Aside":"Sect","Figure":"Figure","H1":"H"}',
        '"structureChildren":2',
        '"parentTree":"25 0 R"',
        '"parentTreeNextKey":5',
        '"idTree":"26 0 R"',
        'pdf-byte-tagging-metadata:9',
        'pdf-byte-tagged',
        'pdf-byte-structure-root:22 0 R',
        'pdf-byte-structure-role-map:3',
        'pdf-byte-structure-children:2',
        'pdfActiveActions',
        'finalPdfActiveActions',
        'catalog.Names.JavaScript.ReviewOpen',
        'page:3 0 R.AA.O',
        'catalog.AA.WC',
        '"type":"JavaScript"',
        '"type":"Launch"',
        '"scriptSha256"',
        'pdfActiveActionTypes',
        'finalPdfActiveActionTypes',
        '"JavaScript":2',
        '"Launch":1',
        'pdf-byte-active-actions:3',
        'pdf-byte-active-action-types:2',
        'pdf-byte-active-action-type:JavaScript:2',
        'pdfAnnotationTypes',
        '"FileAttachment":1',
        '"Link":1',
        '"Widget":1',
        'pdfLinkTargets',
        'https://example.test/review/pdf-review-packet',
        'pdfEmbeddedFileNames',
        'pdfEmbeddedFiles',
        'review-assets.zip',
        '"description":"Review source package"',
        '"afRelationship":"Data"',
        '"subtype":"application/zip"',
        '"streamSha256"',
        '"checksum":"00112233445566778899AABBCCDDEEFF"',
        'pdfFormFields',
        '"name":"reviewer.name"',
        '"typeLabel":"text"',
        '"alternateName":"Reviewer name"',
        '"mappingName":"reviewer_name"',
        '"flagNames":["required","multiline"]',
        'pdfFormFieldTypes',
        '"text":1',
        'pdfEncrypted',
        'fakeProtectedPdf',
        '"pdfEncrypted":true',
        '"pdfEncryptionFilter":"Standard"',
        '"pdfEncryptionVersion":4',
        '"pdfEncryptionRevision":4',
        '"pdfEncryptionLength":128',
        '"pdfPermissionInteger":-44',
        '"pdfEncryptMetadata":false',
        'pdfPermissionFlags',
        '"copy":true',
        '"modify":false',
        'pdf-output-encrypted',
        'pdf-encryption-filter:Standard',
        'pdf-permission-flags:8',
        'pdf-byte-form-fields:1',
        'pdf-byte-form-field-types:1',
        'pdf-byte-annotations:3',
        'pdf-byte-link-targets:1',
        'pdf-byte-embedded-files:1',
        'pdf-byte-embedded-file-metadata:1',
        'pdf-byte-embedded-file-streams:1',
        'pdf-byte-page-count:2',
        'pdf-byte-outline-items:2',
        'migration-log',
        'fake-runner-no-execution',
        'fakeMissingProgram',
        'engine-program-missing:xelatex',
        '"engineMissingProgram":true',
        '"engineMissingProgramName":"xelatex"',
        'fakeRunSequence',
        'fake-runner-attempts:2',
        'fake-runner-attempt-rerun-needed:1',
        'fake-runner-attempt-bibliography-needed:1',
        'fake-runner-final-rerun-cleared',
        'fake-runner-final-bibliography-cleared',
        'finalResourceArtifactsSha256',
        'finalEngineDependencyArtifactsSha256',
        'finalEngineInputFiles',
        'finalEngineExternalInputFiles',
        'finalEngineOutputFiles',
        'finalEngineTranscriptInputFiles',
        'finalEngineTranscriptExternalInputFiles',
        'finalBibliographyArtifactsSha256',
        'finalSourceMapArtifactsSha256',
        'finalSourceMapLineRanges',
        'finalPdfPageCount',
        'finalPdfTrailerCount',
        'finalPdfTrailerRevisions',
        'finalPdfStartXrefOffsets',
        'finalPdfIncrementalUpdates',
        'finalPdfPageBoxes',
        'finalPdfPageRotations',
        'finalPdfOutlineTitles',
        'finalPdfDocumentInfo',
        'finalPdfXmpMetadata',
        'finalPdfOutputIntents',
        'finalPdfLanguage',
        'finalPdfPageLayout',
        'finalPdfPageMode',
        'finalPdfOpenAction',
        'finalPdfViewerPreferences',
        'finalPdfTaggingMetadata',
        'finalPdfActiveActions',
        'finalPdfActiveActionTypes',
        'finalPdfAnnotationTypes',
        'finalPdfLinkTargets',
        'finalPdfEmbeddedFileNames',
        'finalPdfEmbeddedFiles',
        'finalPdfFormFields',
        'finalPdfFormFieldTypes',
        'finalPdfEncrypted',
        'bibliographyWarnings',
        '"successfulAttempts":2',
        '"rerunNeeded":false',
    ] as $needle) {
        if (!str_contains(json_encode($summary, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES), $needle)) {
            throw new RuntimeException('PDF engine handoff self-test missing: ' . $needle);
        }
    }

    echo "pdf engine handoff self-test ok\n";
    return;
}

echo json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
