<?php

declare(strict_types=1);

require dirname(__DIR__, 3) . '/tools/bootstrap.php';

use PortLibs\Pandoc\MarkdownReader;
use PortLibs\Pandoc\PdfEngineHandoff;
use PortLibs\Pandoc\GzipStream;

$markdown = <<<'MARKDOWN'
---
title: "PDF Review Packet"
author: [Migration Desk]
date: 2026-06-04
---

Reviewer formula $E = mc^2$ and source cite \cite{migration-log}.

![Review chart](media/review-chart.png "Review chart")

![Remote reviewer media](https://example.test/media/remote-chart.png)
MARKDOWN;

$document = (new MarkdownReader())->read($markdown);
$handoff = new PdfEngineHandoff();
$plan = $handoff->plan($document, [
    'engine' => 'xelatex',
    'outputPath' => 'handoff/pdf-review-packet.pdf',
    'templatePath' => 'templates/review-packet.tex',
    'includeInHeader' => 'templates/review-header.tex',
    'resourcePaths' => ['media', 'review assets'],
    'resourceFiles' => ['refs/migration-log.bib', 'media/review-chart.png'],
    'variables' => [
        'documentclass' => 'scrartcl',
        'geometry' => ['margin=1in', 'includeheadfoot'],
        'colorlinks' => true,
        'mainfont' => 'Source Serif 4',
    ],
    'engineOptions' => ['-file-line-error', '-recorder', '-synctex=1'],
]);
$fakeXmpMetadata = implode("\n", [
    '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>',
    '<x:xmpmeta xmlns:x="adobe:ns:meta/">',
    '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">',
    '<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/">',
    '<dc:title><rdf:Alt><rdf:li xml:lang="x-default">PDF Review Packet</rdf:li></rdf:Alt></dc:title>',
    '<dc:creator><rdf:Seq><rdf:li>Migration Desk</rdf:li><rdf:li>Content Reviewer</rdf:li></rdf:Seq></dc:creator>',
    '<dc:description><rdf:Alt><rdf:li xml:lang="x-default">Migration review metadata</rdf:li></rdf:Alt></dc:description>',
    '<dc:format>application/pdf</dc:format>',
    '<xmp:CreatorTool>Pandoc native handoff</xmp:CreatorTool>',
    '<xmp:CreateDate>2026-06-05T07:41:23Z</xmp:CreateDate>',
    '<xmp:ModifyDate>2026-06-05T07:42:00Z</xmp:ModifyDate>',
    '<xmp:MetadataDate>2026-06-05T07:42:10Z</xmp:MetadataDate>',
    '<xmpMM:DocumentID>uuid:pdf-review-packet</xmpMM:DocumentID>',
    '<xmpMM:InstanceID>uuid:pdf-review-packet-v2</xmpMM:InstanceID>',
    '<pdfaid:part>2</pdfaid:part>',
    '<pdfaid:conformance>B</pdfaid:conformance>',
    '</rdf:Description>',
    '</rdf:RDF>',
    '</x:xmpmeta>',
    '<?xpacket end="w"?>',
]);
$fakeIccProfile = "fake sRGB ICC profile bytes\n";
$fakePageXmpMetadata = implode("\n", [
    '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>',
    '<x:xmpmeta xmlns:x="adobe:ns:meta/">',
    '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">',
    '<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/">',
    '<dc:title><rdf:Alt><rdf:li xml:lang="x-default">Review packet page 1</rdf:li></rdf:Alt></dc:title>',
    '<dc:description><rdf:Alt><rdf:li xml:lang="x-default">Page-level review provenance</rdf:li></rdf:Alt></dc:description>',
    '<xmp:CreatorTool>Pandoc page handoff</xmp:CreatorTool>',
    '</rdf:Description>',
    '</rdf:RDF>',
    '</x:xmpmeta>',
    '<?xpacket end="w"?>',
]);
$fakeEmbeddedAttachmentBytes = "fake embedded review assets\n";
$fakePageAssociatedAttachmentBytes = "page reviewer notes\n";
$fakeStructureAssociatedAttachmentBytes = '{"source":"chart"}';
$fakeMarkedContentAttachmentBytes = '{"marked":"figure-source"}';
$fakeEmbeddedFontBytes = "fake Source Serif PDF font bytes\n";
$fakeEmbeddedImageBytes = "fake compressed review chart image bytes\n";
$fakeFormXObjectBytes = "q /ImChart Do Q\n";
$fakePageContentBytes = implode("\n", [
    'q',
    '/Span << /MCID 12 >> BDC',
    'BT /FReview 12 Tf (PDF Review Packet) Tj ET',
    '/ImChart Do',
    '/FxOverlay Do',
    'EMC',
    'Q',
    '',
]);
$fakeFilteredPageContentBytes = "compressed final page content bytes\n";
$fakePieceInfoPrivateBytes = "review source path=handoff/pdf-review-packet.tex\n";
$fakeObjectStreamHeader = "80 0 81 24\n";
$fakeObjectStreamBytes = $fakeObjectStreamHeader
    . "<< /Title (Compressed outline) >>\n"
    . "<< /ReviewTarget (packet-summary) >>\n";
$fakeXrefStreamBytes = "fake compressed xref stream bytes\n";
$fakeCatalogJavaScript = 'app.alert("Review packet requires active-content review")';
$fakePageJavaScript = 'this.print({bUI:false});';
$fakeSignatureBytes = hex2bin('3082010A0282010100AABBCC') ?: '';
$fakePdfBytes = implode("\n", [
    '%PDF-1.5',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R /Version /1.7 /Extensions << /ADBE << /BaseVersion /1.7 /ExtensionLevel 8 >> >> /Outlines 5 0 R /Lang (en-US) /Metadata 15 0 R /OutputIntents [17 0 R] /PageLayout /TwoPageRight /PageMode /UseOutlines /OpenAction [3 0 R /FitH 720] /URI << /Base (https://example.test/review/) >> /ViewerPreferences << /DisplayDocTitle true /HideToolbar true /Direction /L2R /PrintScaling /None /NumCopies 2 >> /Names << /EmbeddedFiles << /Names [(review-assets.zip) 10 0 R] >> /JavaScript << /Names [(ReviewOpen) 19 0 R] >> /Dests << /Names [(review-start) [3 0 R /Fit] (import-checklist) [4 0 R /FitH 720]] >> >> /Dests << /packet-summary [3 0 R /FitH 720] >> /PieceInfo << /PandocHandoff << /LastModified (D:20260605123000Z) /Private << /Source (pandoc-native) /Pipeline /pdf-engine-handoff /Revision 2 /Imported true >> >> >> /MarkInfo << /Marked true /UserProperties true /Suspects false >> /StructTreeRoot 22 0 R /PageLabels 27 0 R /OCProperties 37 0 R /AA << /WC 20 0 R >> /AcroForm 14 0 R /Perms << /DocMDP 41 0 R >> /Collection 43 0 R /Threads [47 0 R] >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Count 2 /MediaBox [0 0 612 792] /CropBox [18 18 594 774] /Rotate 0 /Kids [3 0 R 4 0 R] >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R /Metadata 54 0 R /TrimBox [36 36 576 756] /BleedBox [9 9 603 783] /ArtBox [72 72 540 720] /Rotate 90 /Dur 6.5 /Trans << /Type /Trans /S /Fade /D 1.25 >> /VP [68 0 R] /Resources << /Font << /FReview 28 0 R /FBase 30 0 R >> /XObject << /ImChart 34 0 R /FxOverlay 42 0 R >> /Properties << /MCFigure 56 0 R >> >> /Contents [66 0 R 67 0 R] /PieceInfo << /TeXSource << /LastModified (D:20260605123500Z) /Private 55 0 R >> >> /AA << /O 21 0 R >> /Annots [8 0 R 9 0 R 13 0 R 40 0 R 59 0 R] /AF [50 0 R] >>',
    'endobj',
    '4 0 obj',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /CropBox [24 24 768 588] /Rotate -90 /Trans << /Type /Trans /S /Wipe /D 0.75 /Di 90 /Dm /H /M /I /SS 0.8 /B true >> >>',
    'endobj',
    '5 0 obj',
    '<< /Type /Outlines /First 6 0 R /Last 7 0 R /Count 2 >>',
    'endobj',
    '6 0 obj',
    '<< /Title (Review packet) /Parent 5 0 R /Dest [3 0 R /Fit] /Next 7 0 R >>',
    'endobj',
    '7 0 obj',
    '<< /Title <FEFF0049006D0070006F0072007400200063006800650063006B006C006900730074> /Parent 5 0 R /Dest [4 0 R /Fit] /Prev 6 0 R >>',
    'endobj',
    '8 0 obj',
    '<< /Type /Annot /Subtype /Link /Rect [72 640 360 672] /Contents (Review packet link) /T (Migration Desk) /NM (review-link-1) /M (D:20260606051200Z) /F 4 /C [0 0 1] /Border [0 0 0] /A << /S /URI /URI (https://example.test/review/pdf-review-packet) >> >>',
    'endobj',
    '9 0 obj',
    '<< /Type /Annot /Subtype /FileAttachment /FS 10 0 R >>',
    'endobj',
    '10 0 obj',
    '<< /Type /Filespec /F (review-assets.zip) /UF <FEFF007200650076006900650077002D006100730073006500740073002E007A00690070> /Desc (Review source package) /AFRelationship /Data /EF << /F 11 0 R >> >>',
    'endobj',
    '11 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fzip /Params << /Size ' . strlen($fakeEmbeddedAttachmentBytes) . ' /ModDate (D:20260605120500Z) /CheckSum <00112233445566778899aabbccddeeff> >> /Length ' . strlen($fakeEmbeddedAttachmentBytes) . ' >>',
    'stream',
    $fakeEmbeddedAttachmentBytes,
    'endstream',
    'endobj',
    '12 0 obj',
    '<< /Title (PDF Review Packet) /Author <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Subject (Migration review) /Keywords (wordpress, migration) /Creator (Pandoc native handoff) /Producer (XeTeX fake runner) /CreationDate (D:20260605050300Z) /ModDate (D:20260605050400Z) /Trapped /False >>',
    'endobj',
    '13 0 obj',
    '<< /Type /Annot /Subtype /Widget /FT /Tx /T (reviewer.name) /TU (Reviewer name) /TM (reviewer_name) /V <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Ff 4098 >>',
    'endobj',
    '14 0 obj',
    '<< /Fields [13 0 R 40 0 R] /NeedAppearances true /SigFlags 3 /DR << /Font << /Helv 30 0 R >> >> /DA (/Helv 10 Tf 0 g) /Q 1 /CO [13 0 R] /XFA [(template) 45 0 R (datasets) 46 0 R] >>',
    'endobj',
    '15 0 obj',
    '<< /Type /Metadata /Subtype /XML /Length ' . strlen($fakeXmpMetadata) . ' >>',
    'stream',
    $fakeXmpMetadata,
    'endstream',
    'endobj',
    '17 0 obj',
    '<< /Type /OutputIntent /S /GTS_PDFA1 /OutputConditionIdentifier (sRGB IEC61966-2.1) /OutputCondition (sRGB display profile) /RegistryName (http://www.color.org) /Info (sRGB review profile) /DestOutputProfile 18 0 R >>',
    'endobj',
    '18 0 obj',
    '<< /N 3 /Alternate /DeviceRGB /Length ' . strlen($fakeIccProfile) . ' >>',
    'stream',
    $fakeIccProfile,
    'endstream',
    'endobj',
    '19 0 obj',
    '<< /S /JavaScript /JS (' . str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $fakeCatalogJavaScript) . ') >>',
    'endobj',
    '20 0 obj',
    '<< /S /Launch /F (review-helper.exe) >>',
    'endobj',
    '21 0 obj',
    '<< /S /JavaScript /JS <' . strtoupper(bin2hex($fakePageJavaScript)) . '> >>',
    'endobj',
    '22 0 obj',
    '<< /Type /StructTreeRoot /K [23 0 R 24 0 R] /RoleMap << /H1 /H /Aside /Sect /Figure /Figure >> /ParentTree 25 0 R /ParentTreeNextKey 5 /IDTree 26 0 R >>',
    'endobj',
    '23 0 obj',
    '<< /Type /StructElem /S /H1 /P 22 0 R /Pg 3 0 R /K 0 /Alt (Review packet heading) /ActualText (PDF Review Packet) /Lang (en-US) /T (packet-title) /AF [52 0 R] >>',
    'endobj',
    '24 0 obj',
    '<< /Type /StructElem /S /P /P 22 0 R /Pg 3 0 R /K 1 /ActualText (Reviewer formula and citation paragraph) /Lang (en-US) >>',
    'endobj',
    '25 0 obj',
    '<< /Nums [0 [23 0 R] 1 [24 0 R]] >>',
    'endobj',
    '26 0 obj',
    '<< /Names [(intro) 23 0 R (body) 24 0 R] >>',
    'endobj',
    '27 0 obj',
    '<< /Nums [0 << /S /r /P (front-) /St 3 >> 1 << /S /D /P (packet-) /St 1 >>] >>',
    'endobj',
    '28 0 obj',
    '<< /Type /Font /Subtype /Type0 /BaseFont /ABCDEE+SourceSerif4-Regular /Encoding /Identity-H /DescendantFonts [29 0 R] /ToUnicode 31 0 R >>',
    'endobj',
    '29 0 obj',
    '<< /Type /Font /Subtype /CIDFontType2 /BaseFont /ABCDEE+SourceSerif4-Regular /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor 32 0 R >>',
    'endobj',
    '30 0 obj',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
    'endobj',
    '31 0 obj',
    '<< /Length 24 >>',
    'stream',
    '/CIDInit /ProcSet findresource',
    'endstream',
    'endobj',
    '32 0 obj',
    '<< /Type /FontDescriptor /FontName /ABCDEE+SourceSerif4-Regular /FontFamily (Source Serif 4) /Flags 4 /FontWeight 400 /ItalicAngle 0 /FontFile2 33 0 R >>',
    'endobj',
    '33 0 obj',
    '<< /Length ' . strlen($fakeEmbeddedFontBytes) . ' >>',
    'stream',
    $fakeEmbeddedFontBytes,
    'endstream',
    'endobj',
    '34 0 obj',
    '<< /Type /XObject /Subtype /Image /Width 640 /Height 360 /BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter /DCTDecode /Interpolate true /Length ' . strlen($fakeEmbeddedImageBytes) . ' >>',
    'stream',
    $fakeEmbeddedImageBytes,
    'endstream',
    'endobj',
    '42 0 obj',
    '<< /Type /XObject /Subtype /Form /BBox [0 0 144 72] /Matrix [1 0 0 1 24 36] /Resources << /XObject << /ImChart 34 0 R >> >> /Group << /S /Transparency /CS /DeviceRGB /I true /K false >> /Length ' . strlen($fakeFormXObjectBytes) . ' >>',
    'stream',
    $fakeFormXObjectBytes,
    'endstream',
    'endobj',
    '37 0 obj',
    '<< /OCGs [38 0 R 39 0 R] /D << /Name (Review layer config) /Creator (Pandoc native handoff) /BaseState /ON /ON [38 0 R] /OFF [39 0 R] /Order [(Reviewer overlays) 38 0 R [39 0 R]] /ListMode /VisiblePages >> >>',
    'endobj',
    '38 0 obj',
    '<< /Type /OCG /Name (Reviewer notes) /Intent [/View /Design] /Usage << /View << /ViewState /ON >> /Print << /PrintState /OFF >> /Export << /ExportState /OFF >> /CreatorInfo << /Creator (layer package) /Subtype /Artwork >> /Language << /Lang (en-US) /Preferred true >> /Zoom << /min 0.5 /max 2.0 >> >> >>',
    'endobj',
    '39 0 obj',
    '<< /Type /OCG /Name <FEFF005000720069006E00740020006D00610072006B0073> /Intent /View /Usage << /Print << /PrintState /ON >> /Export << /ExportState /ON >> >> >>',
    'endobj',
    '40 0 obj',
    '<< /Type /Annot /Subtype /Widget /FT /Sig /T (review.signature) /TU (Reviewer signature) /V 41 0 R /Ff 3 >>',
    'endobj',
    '41 0 obj',
    '<< /Type /Sig /Filter /Adobe.PPKLite /SubFilter /ETSI.CAdES.detached /Name (Migration Desk) /Reason (Review packet approval) /Location <FEFF00520065006D006F007400650020007200650076006900650077> /ContactInfo (review@example.test) /M (D:20260605121500Z) /ByteRange [0 123 456 789] /Contents <3082010A0282010100AABBCC> /Reference [<< /TransformMethod /DocMDP /TransformParams << /Type /TransformParams /P 2 /V /1.2 >> >> << /TransformMethod /FieldMDP /TransformParams << /Action /Include /Fields [(reviewer.name) (approved)] >> >>] >>',
    'endobj',
    '43 0 obj',
    '<< /Type /Collection /View /T /D (review-assets.zip) /Schema << /Title 44 0 R /Size << /Type /CollectionField /Subtype /Size /N (Attachment size) /O 2 /V false /E false >> >> /Sort << /S [/Title /Size] /A [true false] >> >>',
    'endobj',
    '44 0 obj',
    '<< /Type /CollectionField /Subtype /S /N (Review title) /O 1 /V true /E true >>',
    'endobj',
    '47 0 obj',
    '<< /Type /Thread /F 48 0 R /I << /Title (Review reading order) /Author (Migration Desk) /Subject (PDF article thread) >> >>',
    'endobj',
    '48 0 obj',
    '<< /Type /Bead /T 47 0 R /P 3 0 R /R [72 648 540 720] /N 49 0 R /V 49 0 R >>',
    'endobj',
    '49 0 obj',
    '<< /Type /Bead /T 47 0 R /P 4 0 R /R [72 96 540 144] /N 48 0 R /V 48 0 R >>',
    'endobj',
    '50 0 obj',
    '<< /Type /Filespec /F (page-note.txt) /Desc (Page review note) /AFRelationship /Supplement /EF << /F 51 0 R >> >>',
    'endobj',
    '51 0 obj',
    '<< /Type /EmbeddedFile /Subtype /text#2Fplain /Params << /Size ' . strlen($fakePageAssociatedAttachmentBytes) . ' >> /Length ' . strlen($fakePageAssociatedAttachmentBytes) . ' >>',
    'stream',
    $fakePageAssociatedAttachmentBytes,
    'endstream',
    'endobj',
    '52 0 obj',
    '<< /Type /Filespec /F (figure-source.json) /Desc (Figure source data) /AFRelationship /Source /EF << /F 53 0 R >> >>',
    'endobj',
    '53 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fjson /Params << /Size ' . strlen($fakeStructureAssociatedAttachmentBytes) . ' /ModDate (D:20260605211500Z) >> /Length ' . strlen($fakeStructureAssociatedAttachmentBytes) . ' >>',
    'stream',
    $fakeStructureAssociatedAttachmentBytes,
    'endstream',
    'endobj',
    '54 0 obj',
    '<< /Type /Metadata /Subtype /XML /Length ' . strlen($fakePageXmpMetadata) . ' >>',
    'stream',
    $fakePageXmpMetadata,
    'endstream',
    'endobj',
    '55 0 obj',
    '<< /Producer (XeTeX) /SourceFile (handoff/pdf-review-packet.tex) /Review true /Pass 1 /Length ' . strlen($fakePieceInfoPrivateBytes) . ' >>',
    'stream',
    $fakePieceInfoPrivateBytes,
    'endstream',
    'endobj',
    '56 0 obj',
    '<< /MCID 12 /Lang (en-US) /Alt (Marked chart source) /ActualText (Chart data source) /E (Expanded chart data source) /AF [57 0 R] >>',
    'endobj',
    '57 0 obj',
    '<< /Type /Filespec /F (marked-figure-source.json) /Desc (Marked content source data) /AFRelationship /Source /EF << /F 58 0 R >> >>',
    'endobj',
    '58 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fjson /Params << /Size ' . strlen($fakeMarkedContentAttachmentBytes) . ' >> /Length ' . strlen($fakeMarkedContentAttachmentBytes) . ' >>',
    'stream',
    $fakeMarkedContentAttachmentBytes,
    'endstream',
    'endobj',
    '59 0 obj',
    '<< /Type /Annot /Subtype /RichMedia /Rect [72 320 540 560] /Contents (Reviewer walkthrough video) /RichMediaContent 60 0 R /RichMediaSettings 61 0 R >>',
    'endobj',
    '60 0 obj',
    '<< /Assets << /Names [(review-video.mp4) 62 0 R (captions.vtt) 63 0 R] >> /Configurations [64 0 R] >>',
    'endobj',
    '61 0 obj',
    '<< /Activation << /Condition /PO /Presentation << /Style /Embedded /Transparent true /Toolbar false /NavigationPane false /PassContextClick true >> >> /Deactivation << /Condition /PC >> >>',
    'endobj',
    '62 0 obj',
    '<< /Type /Filespec /F (review-video.mp4) >>',
    'endobj',
    '63 0 obj',
    '<< /Type /Filespec /F (captions.vtt) >>',
    'endobj',
    '64 0 obj',
    '<< /Subtype /Video /Name (Review video configuration) /Instances [65 0 R] >>',
    'endobj',
    '65 0 obj',
    '<< /Subtype /Video /Asset 62 0 R /Params << /Binding /Foreground /FlashVars (autoplay=false) >> >>',
    'endobj',
    '66 0 obj',
    '<< /Length ' . strlen($fakePageContentBytes) . ' >>',
    'stream',
    $fakePageContentBytes,
    'endstream',
    'endobj',
    '67 0 obj',
    '<< /Length ' . strlen($fakeFilteredPageContentBytes) . ' /Filter /FlateDecode >>',
    'stream',
    $fakeFilteredPageContentBytes,
    'endstream',
    'endobj',
    '68 0 obj',
    '<< /Type /Viewport /Name (Review crop measure) /BBox [72 72 540 720] /Measure 69 0 R >>',
    'endobj',
    '69 0 obj',
    '<< /Type /Measure /Subtype /RL /R (1 in = 12 pt) /X [<< /Type /NumberFormat /U (in) /C 1 /F /D >>] /Y [<< /U (pt) /C 12 >>] /D [<< /U (pt) /C 12 >>] >>',
    'endobj',
    '35 0 obj',
    '<< /Type /ObjStm /N 2 /First ' . strlen($fakeObjectStreamHeader) . ' /Length ' . strlen($fakeObjectStreamBytes) . ' >>',
    'stream',
    $fakeObjectStreamBytes,
    'endstream',
    'endobj',
    '36 0 obj',
    '<< /Type /XRef /Size 37 /Root 1 0 R /Info 12 0 R /Prev 512 /Index [0 35 35 2] /W [1 2 1] /Filter /FlateDecode /Length ' . strlen($fakeXrefStreamBytes) . ' >>',
    'stream',
    $fakeXrefStreamBytes,
    'endstream',
    'endobj',
    'trailer',
    '<< /Size 37 /Root 1 0 R /Info 12 0 R /ID [<00112233445566778899aabbccddeeff> <00112233445566778899aabbccddeeff>] >>',
    'startxref',
    '512',
    '%%EOF',
    '16 0 obj',
    '<< /Title (PDF Review Packet Appended) /Producer (WordPress review appender) >>',
    'endobj',
    'trailer',
    '<< /Size 37 /Root 1 0 R /Info 16 0 R /Prev 512 /ID [<00112233445566778899aabbccddeeff> <ffeeddccbbaa99887766554433221100>] >>',
    'startxref',
    '1024',
    '%%EOF',
    '',
]);
$fakeLog = implode("\n", [
    'This is XeTeX, Version 3.141592653',
    '(./handoff/pdf-review-packet.tex',
    '(./templates/review-packet.tex',
    '(./templates/review-header.tex',
    '(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls)',
    '(./media/review-chart.png)',
    "LaTeX Warning: Citation `migration-log' on page 1 undefined on input line 4.",
    'LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.',
    'Output written on handoff/pdf-review-packet.pdf (2 pages, ' . strlen($fakePdfBytes) . ' bytes).',
    '',
]);
$fakeRecorderFile = implode("\n", [
    'PWD /tmp/pandoc-pdf-review',
    'INPUT handoff/pdf-review-packet.tex',
    'INPUT templates/review-packet.tex',
    'INPUT templates/review-header.tex',
    'INPUT media/review-chart.png',
    'INPUT refs/migration-log.bib',
    'INPUT /usr/share/texlive/texmf-dist/tex/latex/base/article.cls',
    'OUTPUT handoff/pdf-review-packet.aux',
    'OUTPUT handoff/pdf-review-packet.bcf',
    'OUTPUT handoff/pdf-review-packet.log',
    'OUTPUT handoff/pdf-review-packet.out',
    'OUTPUT handoff/pdf-review-packet.pdf',
    'OUTPUT handoff/pdf-review-packet.run.xml',
    'OUTPUT handoff/pdf-review-packet.synctex.gz',
    '',
]);
$fakeSourceMap = implode("\n", [
    'SyncTeX Version:1',
    'Input:1:handoff/pdf-review-packet.tex',
    'Input:2:templates/review-header.tex',
    'Output:pdf',
    'Content:',
    '[1,4:100,200:300,400',
    '(2,1:120,240',
    '',
]);
$fakeSourceMapBytes = GzipStream::build($fakeSourceMap, ['filename' => 'pdf-review-packet.synctex']);
$fakeBibliographyLog = implode("\n", [
    'This is Biber 2.19',
    'Biber warning: Entry migration-log not found in bibliography',
    'Package biblatex Warning: Please (re)run Biber on the file: pdf-review-packet and rerun LaTeX afterwards.',
    '',
]);
$fakeFirstRun = [
    'stdout' => 'fake xelatex runner accepted the planned argv',
    'files' => [
        $plan['sourceFile'] => (string) $plan['sourceBytes'],
        'templates/review-packet.tex' => '\documentclass{$documentclass$}' . "\n" . '$for(include-in-header)$$include-in-header$$endfor$' . "\n" . '\begin{document}$body$\end{document}',
        'templates/review-header.tex' => '\usepackage{fontspec}',
        'media/review-chart.png' => 'fake review chart bytes',
        'refs/migration-log.bib' => '@book{migration-log,title={Migration Log}}',
        'handoff/pdf-review-packet.aux' => "\\relax\n",
        'handoff/pdf-review-packet.bcf' => '<bcf:controlfile />',
        'handoff/pdf-review-packet.run.xml' => '<requests />',
        'handoff/pdf-review-packet.blg' => $fakeBibliographyLog,
        'handoff/pdf-review-packet.out' => "\n",
        'handoff/pdf-review-packet.fls' => $fakeRecorderFile,
        'handoff/pdf-review-packet.synctex.gz' => $fakeSourceMapBytes,
        'handoff/pdf-review-packet.log' => $fakeLog,
        $plan['outputFile'] => $fakePdfBytes,
    ],
];
$fakeResult = $handoff->fakeRun($plan, $fakeFirstRun);
$fakeProtectedPdfBytes = implode("\n", [
    '%PDF-1.7',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Count 1 /Kids [3 0 R] >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R >>',
    'endobj',
    '12 0 obj',
    '<< /Filter /Standard /V 4 /R 4 /Length 128 /P -44 /EncryptMetadata false >>',
    'endobj',
    'trailer',
    '<< /Root 1 0 R /Encrypt 12 0 R >>',
    '%%EOF',
    '',
]);
$fakeProtectedPdf = $handoff->fakeRun($plan, [
    'files' => [
        $plan['sourceFile'] => (string) $plan['sourceBytes'],
        'templates/review-packet.tex' => '\documentclass{$documentclass$}' . "\n" . '$body$',
        'templates/review-header.tex' => '\usepackage{fontspec}',
        'media/review-chart.png' => 'fake review chart bytes',
        'refs/migration-log.bib' => '@book{migration-log,title={Migration Log}}',
        $plan['outputFile'] => $fakeProtectedPdfBytes,
    ],
]);
$fakeMissingProgram = $handoff->fakeRun($plan, [
    'exitCode' => 127,
    'stderr' => "xelatex: command not found\n",
]);
$fakeFinalPdfBytes = implode("\n", [
    '%PDF-1.5',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R /Version /1.7 /Extensions << /ADBE << /BaseVersion /1.7 /ExtensionLevel 8 >> >> /Outlines 5 0 R /Lang (en-US) /Metadata 15 0 R /OutputIntents [17 0 R] /PageLayout /TwoPageRight /PageMode /UseOutlines /OpenAction [3 0 R /FitH 720] /ViewerPreferences << /DisplayDocTitle true /HideToolbar true /Direction /L2R /PrintScaling /None /NumCopies 2 >> /Names << /EmbeddedFiles << /Names [(review-assets.zip) 10 0 R] >> /JavaScript << /Names [(ReviewOpen) 19 0 R] >> /Dests << /Names [(review-start) [3 0 R /Fit] (import-checklist) [4 0 R /FitH 720]] >> >> /Dests << /packet-summary [3 0 R /FitH 720] >> /PieceInfo << /PandocHandoff << /LastModified (D:20260605123000Z) /Private << /Source (pandoc-native) /Pipeline /pdf-engine-handoff /Revision 2 /Imported true >> >> >> /MarkInfo << /Marked true /UserProperties true /Suspects false >> /StructTreeRoot 22 0 R /PageLabels 27 0 R /OCProperties 37 0 R /AA << /WC 20 0 R >> /AcroForm 14 0 R /Perms << /DocMDP 41 0 R >> /Collection 43 0 R /Threads [47 0 R] >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Count 2 /MediaBox [0 0 612 792] /CropBox [18 18 594 774] /Rotate 0 /Kids [3 0 R 4 0 R] >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R /Metadata 54 0 R /TrimBox [36 36 576 756] /BleedBox [9 9 603 783] /ArtBox [72 72 540 720] /Rotate 90 /Dur 6.5 /Trans << /Type /Trans /S /Fade /D 1.25 >> /VP [68 0 R] /Resources << /XObject << /ImChart 34 0 R /FxOverlay 42 0 R >> /Properties << /MCFigure 56 0 R >> >> /Contents [66 0 R 67 0 R] /PieceInfo << /TeXSource << /LastModified (D:20260605123500Z) /Private 55 0 R >> >> /AA << /O 21 0 R >> /Annots [8 0 R 9 0 R 13 0 R 40 0 R] /AF [50 0 R] >>',
    'endobj',
    '4 0 obj',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /CropBox [24 24 768 588] /Rotate -90 /Trans << /Type /Trans /S /Wipe /D 0.75 /Di 90 /Dm /H /M /I /SS 0.8 /B true >> >>',
    'endobj',
    '5 0 obj',
    '<< /Type /Outlines /First 6 0 R /Last 7 0 R /Count 2 >>',
    'endobj',
    '6 0 obj',
    '<< /Title (Review packet) /Parent 5 0 R /Dest [3 0 R /Fit] /Next 7 0 R >>',
    'endobj',
    '7 0 obj',
    '<< /Title <FEFF0049006D0070006F0072007400200063006800650063006B006C006900730074> /Parent 5 0 R /Dest [4 0 R /Fit] /Prev 6 0 R >>',
    'endobj',
    '8 0 obj',
    '<< /Type /Annot /Subtype /Link /Rect [72 640 360 672] /Contents (Review packet link) /T (Migration Desk) /NM (review-link-1) /M (D:20260606051200Z) /F 4 /C [0 0 1] /Border [0 0 0] /A << /S /URI /URI (https://example.test/review/pdf-review-packet) >> >>',
    'endobj',
    '9 0 obj',
    '<< /Type /Annot /Subtype /FileAttachment /FS 10 0 R >>',
    'endobj',
    '10 0 obj',
    '<< /Type /Filespec /F (review-assets.zip) /UF <FEFF007200650076006900650077002D006100730073006500740073002E007A00690070> /Desc (Review source package) /AFRelationship /Data /EF << /F 11 0 R >> >>',
    'endobj',
    '11 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fzip /Params << /Size ' . strlen($fakeEmbeddedAttachmentBytes) . ' /ModDate (D:20260605120500Z) /CheckSum <00112233445566778899aabbccddeeff> >> /Length ' . strlen($fakeEmbeddedAttachmentBytes) . ' >>',
    'stream',
    $fakeEmbeddedAttachmentBytes,
    'endstream',
    'endobj',
    '12 0 obj',
    '<< /Title (PDF Review Packet) /Author <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Subject (Migration review) /Keywords (wordpress, migration) /Creator (Pandoc native handoff) /Producer (XeTeX fake runner) /CreationDate (D:20260605050300Z) /ModDate (D:20260605050400Z) /Trapped /False >>',
    'endobj',
    '13 0 obj',
    '<< /Type /Annot /Subtype /Widget /FT /Tx /T (reviewer.name) /TU (Reviewer name) /TM (reviewer_name) /V <FEFF004D006900670072006100740069006F006E0020004400650073006B> /Ff 4098 >>',
    'endobj',
    '14 0 obj',
    '<< /Fields [13 0 R 40 0 R] /NeedAppearances true /SigFlags 3 /DR << /Font << /Helv 30 0 R >> >> /DA (/Helv 10 Tf 0 g) /Q 1 /CO [13 0 R] /XFA [(template) 45 0 R (datasets) 46 0 R] >>',
    'endobj',
    '15 0 obj',
    '<< /Type /Metadata /Subtype /XML /Length ' . strlen($fakeXmpMetadata) . ' >>',
    'stream',
    $fakeXmpMetadata,
    'endstream',
    'endobj',
    '17 0 obj',
    '<< /Type /OutputIntent /S /GTS_PDFA1 /OutputConditionIdentifier (sRGB IEC61966-2.1) /OutputCondition (sRGB display profile) /RegistryName (http://www.color.org) /Info (sRGB review profile) /DestOutputProfile 18 0 R >>',
    'endobj',
    '18 0 obj',
    '<< /N 3 /Alternate /DeviceRGB /Length ' . strlen($fakeIccProfile) . ' >>',
    'stream',
    $fakeIccProfile,
    'endstream',
    'endobj',
    '19 0 obj',
    '<< /S /JavaScript /JS (' . str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $fakeCatalogJavaScript) . ') >>',
    'endobj',
    '20 0 obj',
    '<< /S /Launch /F (review-helper.exe) >>',
    'endobj',
    '21 0 obj',
    '<< /S /JavaScript /JS <' . strtoupper(bin2hex($fakePageJavaScript)) . '> >>',
    'endobj',
    '22 0 obj',
    '<< /Type /StructTreeRoot /K [23 0 R 24 0 R] /RoleMap << /H1 /H /Aside /Sect /Figure /Figure >> /ParentTree 25 0 R /ParentTreeNextKey 5 /IDTree 26 0 R >>',
    'endobj',
    '23 0 obj',
    '<< /Type /StructElem /S /H1 /P 22 0 R /Pg 3 0 R /K 0 /Alt (Review packet heading) /ActualText (PDF Review Packet) /Lang (en-US) /T (packet-title) /AF [52 0 R] >>',
    'endobj',
    '24 0 obj',
    '<< /Type /StructElem /S /P /P 22 0 R /Pg 3 0 R /K 1 /ActualText (Reviewer formula and citation paragraph) /Lang (en-US) >>',
    'endobj',
    '25 0 obj',
    '<< /Nums [0 [23 0 R] 1 [24 0 R]] >>',
    'endobj',
    '26 0 obj',
    '<< /Names [(intro) 23 0 R (body) 24 0 R] >>',
    'endobj',
    '27 0 obj',
    '<< /Nums [0 << /S /r /P (front-) /St 3 >> 1 << /S /D /P (packet-) /St 1 >>] >>',
    'endobj',
    '28 0 obj',
    '<< /Type /XObject /Subtype /Image /Width 640 /Height 360 /BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter /DCTDecode /Interpolate true /Length ' . strlen($fakeEmbeddedImageBytes) . ' >>',
    'stream',
    $fakeEmbeddedImageBytes,
    'endstream',
    'endobj',
    '42 0 obj',
    '<< /Type /XObject /Subtype /Form /BBox [0 0 144 72] /Matrix [1 0 0 1 24 36] /Resources << /XObject << /ImChart 28 0 R >> >> /Group << /S /Transparency /CS /DeviceRGB /I true /K false >> /Length ' . strlen($fakeFormXObjectBytes) . ' >>',
    'stream',
    $fakeFormXObjectBytes,
    'endstream',
    'endobj',
    '37 0 obj',
    '<< /OCGs [38 0 R 39 0 R] /D << /Name (Review layer config) /Creator (Pandoc native handoff) /BaseState /ON /ON [38 0 R] /OFF [39 0 R] /Order [(Reviewer overlays) 38 0 R [39 0 R]] /ListMode /VisiblePages >> >>',
    'endobj',
    '38 0 obj',
    '<< /Type /OCG /Name (Reviewer notes) /Intent [/View /Design] /Usage << /View << /ViewState /ON >> /Print << /PrintState /OFF >> /Export << /ExportState /OFF >> /CreatorInfo << /Creator (layer package) /Subtype /Artwork >> /Language << /Lang (en-US) /Preferred true >> /Zoom << /min 0.5 /max 2.0 >> >> >>',
    'endobj',
    '39 0 obj',
    '<< /Type /OCG /Name <FEFF005000720069006E00740020006D00610072006B0073> /Intent /View /Usage << /Print << /PrintState /ON >> /Export << /ExportState /ON >> >> >>',
    'endobj',
    '40 0 obj',
    '<< /Type /Annot /Subtype /Widget /FT /Sig /T (review.signature) /TU (Reviewer signature) /V 41 0 R /Ff 3 >>',
    'endobj',
    '41 0 obj',
    '<< /Type /Sig /Filter /Adobe.PPKLite /SubFilter /ETSI.CAdES.detached /Name (Migration Desk) /Reason (Review packet approval) /Location <FEFF00520065006D006F007400650020007200650076006900650077> /ContactInfo (review@example.test) /M (D:20260605121500Z) /ByteRange [0 123 456 789] /Contents <3082010A0282010100AABBCC> /Reference [<< /TransformMethod /DocMDP /TransformParams << /Type /TransformParams /P 2 /V /1.2 >> >> << /TransformMethod /FieldMDP /TransformParams << /Action /Include /Fields [(reviewer.name) (approved)] >> >>] >>',
    'endobj',
    '43 0 obj',
    '<< /Type /Collection /View /T /D (review-assets.zip) /Schema << /Title 44 0 R /Size << /Type /CollectionField /Subtype /Size /N (Attachment size) /O 2 /V false /E false >> >> /Sort << /S [/Title /Size] /A [true false] >> >>',
    'endobj',
    '44 0 obj',
    '<< /Type /CollectionField /Subtype /S /N (Review title) /O 1 /V true /E true >>',
    'endobj',
    '47 0 obj',
    '<< /Type /Thread /F 48 0 R /I << /Title (Review reading order) /Author (Migration Desk) /Subject (PDF article thread) >> >>',
    'endobj',
    '48 0 obj',
    '<< /Type /Bead /T 47 0 R /P 3 0 R /R [72 648 540 720] /N 49 0 R /V 49 0 R >>',
    'endobj',
    '49 0 obj',
    '<< /Type /Bead /T 47 0 R /P 4 0 R /R [72 96 540 144] /N 48 0 R /V 48 0 R >>',
    'endobj',
    '50 0 obj',
    '<< /Type /Filespec /F (page-note.txt) /Desc (Page review note) /AFRelationship /Supplement /EF << /F 51 0 R >> >>',
    'endobj',
    '51 0 obj',
    '<< /Type /EmbeddedFile /Subtype /text#2Fplain /Params << /Size ' . strlen($fakePageAssociatedAttachmentBytes) . ' >> /Length ' . strlen($fakePageAssociatedAttachmentBytes) . ' >>',
    'stream',
    $fakePageAssociatedAttachmentBytes,
    'endstream',
    'endobj',
    '52 0 obj',
    '<< /Type /Filespec /F (figure-source.json) /Desc (Figure source data) /AFRelationship /Source /EF << /F 53 0 R >> >>',
    'endobj',
    '53 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fjson /Params << /Size ' . strlen($fakeStructureAssociatedAttachmentBytes) . ' /ModDate (D:20260605211500Z) >> /Length ' . strlen($fakeStructureAssociatedAttachmentBytes) . ' >>',
    'stream',
    $fakeStructureAssociatedAttachmentBytes,
    'endstream',
    'endobj',
    '54 0 obj',
    '<< /Type /Metadata /Subtype /XML /Length ' . strlen($fakePageXmpMetadata) . ' >>',
    'stream',
    $fakePageXmpMetadata,
    'endstream',
    'endobj',
    '55 0 obj',
    '<< /Producer (XeTeX) /SourceFile (handoff/pdf-review-packet.tex) /Review true /Pass 2 /Length ' . strlen($fakePieceInfoPrivateBytes) . ' >>',
    'stream',
    $fakePieceInfoPrivateBytes,
    'endstream',
    'endobj',
    '56 0 obj',
    '<< /MCID 12 /Lang (en-US) /Alt (Marked chart source) /ActualText (Chart data source) /E (Expanded chart data source) /AF [57 0 R] >>',
    'endobj',
    '57 0 obj',
    '<< /Type /Filespec /F (marked-figure-source.json) /Desc (Marked content source data) /AFRelationship /Source /EF << /F 58 0 R >> >>',
    'endobj',
    '58 0 obj',
    '<< /Type /EmbeddedFile /Subtype /application#2Fjson /Params << /Size ' . strlen($fakeMarkedContentAttachmentBytes) . ' >> /Length ' . strlen($fakeMarkedContentAttachmentBytes) . ' >>',
    'stream',
    $fakeMarkedContentAttachmentBytes,
    'endstream',
    'endobj',
    '66 0 obj',
    '<< /Length ' . strlen($fakePageContentBytes) . ' >>',
    'stream',
    $fakePageContentBytes,
    'endstream',
    'endobj',
    '67 0 obj',
    '<< /Length ' . strlen($fakeFilteredPageContentBytes) . ' /Filter /FlateDecode >>',
    'stream',
    $fakeFilteredPageContentBytes,
    'endstream',
    'endobj',
    '68 0 obj',
    '<< /Type /Viewport /Name (Review crop measure) /BBox [72 72 540 720] /Measure 69 0 R >>',
    'endobj',
    '69 0 obj',
    '<< /Type /Measure /Subtype /RL /R (1 in = 12 pt) /X [<< /Type /NumberFormat /U (in) /C 1 /F /D >>] /Y [<< /U (pt) /C 12 >>] /D [<< /U (pt) /C 12 >>] >>',
    'endobj',
    '29 0 obj',
    '<< /Type /ObjStm /N 2 /First ' . strlen($fakeObjectStreamHeader) . ' /Length ' . strlen($fakeObjectStreamBytes) . ' >>',
    'stream',
    $fakeObjectStreamBytes,
    'endstream',
    'endobj',
    '30 0 obj',
    '<< /Type /XRef /Size 31 /Root 1 0 R /Info 12 0 R /Prev 512 /Index [0 29 29 2] /W [1 2 1] /Filter /FlateDecode /Length ' . strlen($fakeXrefStreamBytes) . ' >>',
    'stream',
    $fakeXrefStreamBytes,
    'endstream',
    'endobj',
    'trailer',
    '<< /Size 31 /Root 1 0 R /Info 12 0 R /ID [<00112233445566778899aabbccddeeff> <00112233445566778899aabbccddeeff>] >>',
    'startxref',
    '512',
    '%%EOF',
    '16 0 obj',
    '<< /Title (PDF Review Packet Appended) /Producer (WordPress review appender) >>',
    'endobj',
    'trailer',
    '<< /Size 31 /Root 1 0 R /Info 16 0 R /Prev 512 /ID [<00112233445566778899aabbccddeeff> <ffeeddccbbaa99887766554433221100>] >>',
    'startxref',
    '1024',
    '%%EOF',
    '',
]);
$fakeFinalLog = implode("\n", [
    'This is XeTeX, Version 3.141592653',
    '(./handoff/pdf-review-packet.tex',
    '(./templates/review-packet.tex',
    '(./templates/review-header.tex',
    '(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls)',
    '(./media/review-chart.png)',
    'Output written on handoff/pdf-review-packet.pdf (2 pages, ' . strlen($fakeFinalPdfBytes) . ' bytes).',
    '',
]);
$fakeSequence = $handoff->fakeRunSequence($plan, [
    $fakeFirstRun,
    [
        'stdout' => 'fake xelatex runner accepted the final planned argv',
        'files' => [
            $plan['sourceFile'] => (string) $plan['sourceBytes'],
            'templates/review-packet.tex' => '\documentclass{$documentclass$}' . "\n" . '$for(include-in-header)$$include-in-header$$endfor$' . "\n" . '\begin{document}$body$\end{document}',
            'templates/review-header.tex' => '\usepackage{fontspec}',
            'media/review-chart.png' => 'fake review chart bytes',
            'refs/migration-log.bib' => '@book{migration-log,title={Migration Log}}',
            'handoff/pdf-review-packet.aux' => "\\relax\n\\citation{migration-log}\n",
            'handoff/pdf-review-packet.bbl' => "\\begin{thebibliography}{1}\n\\end{thebibliography}\n",
            'handoff/pdf-review-packet.blg' => "This is Biber 2.19\n",
            'handoff/pdf-review-packet.out' => "\n",
            'handoff/pdf-review-packet.fls' => $fakeRecorderFile,
            'handoff/pdf-review-packet.synctex.gz' => $fakeSourceMapBytes,
            'handoff/pdf-review-packet.log' => $fakeFinalLog,
            $plan['outputFile'] => $fakeFinalPdfBytes,
        ],
    ],
]);

$summary = [
    'engine' => $plan['engine'],
    'intermediateFormat' => $plan['intermediateFormat'],
    'sourceFile' => $plan['sourceFile'],
    'outputFile' => $plan['outputFile'],
    'argv' => $plan['argv'],
    'writerArguments' => $plan['writerArguments'],
    'templateFile' => $plan['templateFile'],
    'includeInHeaderFiles' => $plan['includeInHeaderFiles'],
    'resourcePaths' => $plan['resourcePaths'],
    'resourceFiles' => $plan['resourceFiles'],
    'resourceFileManifest' => $plan['resourceFileManifest'],
    'remoteResourceReferences' => $plan['remoteResourceReferences'],
    'skippedResourceReferences' => $plan['skippedResourceReferences'],
    'sourceArtifacts' => $plan['sourceArtifacts'],
    'engineLogFile' => $plan['engineLogFile'],
    'expectedEngineArtifacts' => $plan['expectedEngineArtifacts'],
    'templateVariables' => $plan['templateVariables'],
    'metadata' => $plan['metadata'],
    'sourceSha256' => $plan['sourceSha256'],
    'fakeRun' => [
        'ok' => $fakeResult['ok'],
        'reason' => $fakeResult['reason'],
        'bytes' => $fakeResult['bytes'],
        'sourceArtifactsSha256' => $fakeResult['sourceArtifactsSha256'],
        'resourceArtifactsSha256' => $fakeResult['resourceArtifactsSha256'],
        'missingResourceFiles' => $fakeResult['missingResourceFiles'],
        'producedArtifactsSha256' => $fakeResult['producedArtifactsSha256'],
        'engineDependencyArtifactsSha256' => $fakeResult['engineDependencyArtifactsSha256'],
        'engineInputFiles' => $fakeResult['engineInputFiles'],
        'engineExternalInputFiles' => $fakeResult['engineExternalInputFiles'],
        'engineOutputFiles' => $fakeResult['engineOutputFiles'],
        'engineTranscriptInputFiles' => $fakeResult['engineTranscriptInputFiles'],
        'engineTranscriptExternalInputFiles' => $fakeResult['engineTranscriptExternalInputFiles'],
        'missingEngineInputFiles' => $fakeResult['missingEngineInputFiles'],
        'missingEngineTranscriptInputFiles' => $fakeResult['missingEngineTranscriptInputFiles'],
        'bibliographyArtifactsSha256' => $fakeResult['bibliographyArtifactsSha256'],
        'bibliographyLogFiles' => $fakeResult['bibliographyLogFiles'],
        'sourceMapArtifactsSha256' => $fakeResult['sourceMapArtifactsSha256'],
        'sourceMapFiles' => $fakeResult['sourceMapFiles'],
        'sourceMapInputs' => $fakeResult['sourceMapInputs'],
        'sourceMapInputFiles' => $fakeResult['sourceMapInputFiles'],
        'sourceMapExternalInputs' => $fakeResult['sourceMapExternalInputs'],
        'sourceMapLineRanges' => $fakeResult['sourceMapLineRanges'],
        'engineLogFiles' => $fakeResult['engineLogFiles'],
        'engineWarnings' => $fakeResult['engineWarnings'],
        'engineErrors' => $fakeResult['engineErrors'],
        'bibliographyWarnings' => $fakeResult['bibliographyWarnings'],
        'bibliographyErrors' => $fakeResult['bibliographyErrors'],
        'bibliographyNeeded' => $fakeResult['bibliographyNeeded'],
        'rerunNeeded' => $fakeResult['rerunNeeded'],
        'declaredOutputFile' => $fakeResult['declaredOutputFile'],
        'declaredOutputPages' => $fakeResult['declaredOutputPages'],
        'declaredOutputBytes' => $fakeResult['declaredOutputBytes'],
        'pdfTrailerComplete' => $fakeResult['pdfTrailerComplete'],
        'pdfTrailerCount' => $fakeResult['pdfTrailerCount'],
        'pdfTrailerRevisions' => $fakeResult['pdfTrailerRevisions'],
        'pdfStartXrefOffsets' => $fakeResult['pdfStartXrefOffsets'],
        'pdfIncrementalUpdates' => $fakeResult['pdfIncrementalUpdates'],
        'pdfHeaderVersion' => $fakeResult['pdfHeaderVersion'],
        'pdfCatalogVersion' => $fakeResult['pdfCatalogVersion'],
        'pdfEffectiveVersion' => $fakeResult['pdfEffectiveVersion'],
        'pdfExtensionMetadata' => $fakeResult['pdfExtensionMetadata'],
        'pdfXrefStreams' => $fakeResult['pdfXrefStreams'],
        'pdfXrefStreamFilters' => $fakeResult['pdfXrefStreamFilters'],
        'pdfObjectStreams' => $fakeResult['pdfObjectStreams'],
        'pdfObjectStreamFilters' => $fakeResult['pdfObjectStreamFilters'],
        'pdfPageCount' => $fakeResult['pdfPageCount'],
        'pdfPageBoxes' => $fakeResult['pdfPageBoxes'],
        'pdfPageRotations' => $fakeResult['pdfPageRotations'],
        'pdfPageLabels' => $fakeResult['pdfPageLabels'],
        'pdfPageTimings' => $fakeResult['pdfPageTimings'],
        'pdfPageViewports' => $fakeResult['pdfPageViewports'],
        'pdfPageContentStreams' => $fakeResult['pdfPageContentStreams'],
        'pdfPageContentResourceUsage' => $fakeResult['pdfPageContentResourceUsage'],
        'pdfFonts' => $fakeResult['pdfFonts'],
        'pdfFontSubtypes' => $fakeResult['pdfFontSubtypes'],
        'pdfImages' => $fakeResult['pdfImages'],
        'pdfImageColorSpaces' => $fakeResult['pdfImageColorSpaces'],
        'pdfImageFilters' => $fakeResult['pdfImageFilters'],
        'pdfFormXObjects' => $fakeResult['pdfFormXObjects'],
        'pdfFormXObjectFilters' => $fakeResult['pdfFormXObjectFilters'],
        'pdfOutlineTitles' => $fakeResult['pdfOutlineTitles'],
        'pdfOutlines' => $fakeResult['pdfOutlines'],
        'pdfDocumentInfo' => $fakeResult['pdfDocumentInfo'],
        'pdfXmpMetadata' => $fakeResult['pdfXmpMetadata'],
        'pdfPageMetadata' => $fakeResult['pdfPageMetadata'],
        'pdfPieceInfo' => $fakeResult['pdfPieceInfo'],
        'pdfOutputIntents' => $fakeResult['pdfOutputIntents'],
        'pdfLanguage' => $fakeResult['pdfLanguage'],
        'pdfPageLayout' => $fakeResult['pdfPageLayout'],
        'pdfPageMode' => $fakeResult['pdfPageMode'],
        'pdfOpenAction' => $fakeResult['pdfOpenAction'],
        'pdfNamedDestinations' => $fakeResult['pdfNamedDestinations'],
        'pdfUriBase' => $fakeResult['pdfUriBase'],
        'pdfViewerPreferences' => $fakeResult['pdfViewerPreferences'],
        'pdfTaggingMetadata' => $fakeResult['pdfTaggingMetadata'],
        'pdfStructureElements' => $fakeResult['pdfStructureElements'],
        'pdfMarkedContentProperties' => $fakeResult['pdfMarkedContentProperties'],
        'pdfOptionalContentGroups' => $fakeResult['pdfOptionalContentGroups'],
        'pdfOptionalContentConfig' => $fakeResult['pdfOptionalContentConfig'],
        'pdfCollectionMetadata' => $fakeResult['pdfCollectionMetadata'],
        'pdfAcroFormMetadata' => $fakeResult['pdfAcroFormMetadata'],
        'pdfThreads' => $fakeResult['pdfThreads'],
        'pdfCatalogPermissions' => $fakeResult['pdfCatalogPermissions'],
        'pdfSignatures' => $fakeResult['pdfSignatures'],
        'pdfSignatureSubFilters' => $fakeResult['pdfSignatureSubFilters'],
        'pdfActiveActions' => $fakeResult['pdfActiveActions'],
        'pdfActiveActionTypes' => $fakeResult['pdfActiveActionTypes'],
        'pdfRichMediaAnnotations' => $fakeResult['pdfRichMediaAnnotations'],
        'pdfRichMediaActivationModes' => $fakeResult['pdfRichMediaActivationModes'],
        'pdfAnnotations' => $fakeResult['pdfAnnotations'],
        'pdfAnnotationTypes' => $fakeResult['pdfAnnotationTypes'],
        'pdfLinkTargets' => $fakeResult['pdfLinkTargets'],
        'pdfEmbeddedFileNames' => $fakeResult['pdfEmbeddedFileNames'],
        'pdfEmbeddedFiles' => $fakeResult['pdfEmbeddedFiles'],
        'pdfFormFields' => $fakeResult['pdfFormFields'],
        'pdfFormFieldTypes' => $fakeResult['pdfFormFieldTypes'],
        'pdfEncrypted' => $fakeResult['pdfEncrypted'],
        'pdfEncryptionFilter' => $fakeResult['pdfEncryptionFilter'],
        'pdfEncryptionVersion' => $fakeResult['pdfEncryptionVersion'],
        'pdfEncryptionRevision' => $fakeResult['pdfEncryptionRevision'],
        'pdfEncryptionLength' => $fakeResult['pdfEncryptionLength'],
        'pdfPermissionInteger' => $fakeResult['pdfPermissionInteger'],
        'pdfPermissionFlags' => $fakeResult['pdfPermissionFlags'],
        'pdfEncryptMetadata' => $fakeResult['pdfEncryptMetadata'],
        'diagnostics' => $fakeResult['diagnostics'],
    ],
    'fakeProtectedPdf' => [
        'ok' => $fakeProtectedPdf['ok'],
        'reason' => $fakeProtectedPdf['reason'],
        'pdfEncrypted' => $fakeProtectedPdf['pdfEncrypted'],
        'pdfEncryptionFilter' => $fakeProtectedPdf['pdfEncryptionFilter'],
        'pdfEncryptionVersion' => $fakeProtectedPdf['pdfEncryptionVersion'],
        'pdfEncryptionRevision' => $fakeProtectedPdf['pdfEncryptionRevision'],
        'pdfEncryptionLength' => $fakeProtectedPdf['pdfEncryptionLength'],
        'pdfPermissionInteger' => $fakeProtectedPdf['pdfPermissionInteger'],
        'pdfPermissionFlags' => $fakeProtectedPdf['pdfPermissionFlags'],
        'pdfEncryptMetadata' => $fakeProtectedPdf['pdfEncryptMetadata'],
        'diagnostics' => $fakeProtectedPdf['diagnostics'],
    ],
    'fakeMissingProgram' => [
        'ok' => $fakeMissingProgram['ok'],
        'reason' => $fakeMissingProgram['reason'],
        'engineMissingProgram' => $fakeMissingProgram['engineMissingProgram'],
        'engineMissingProgramName' => $fakeMissingProgram['engineMissingProgramName'],
        'diagnostics' => $fakeMissingProgram['diagnostics'],
    ],
    'fakeRunSequence' => [
        'ok' => $fakeSequence['ok'],
        'reason' => $fakeSequence['reason'],
        'attempts' => $fakeSequence['attempts'],
        'successfulAttempts' => $fakeSequence['successfulAttempts'],
        'finalRunIndex' => $fakeSequence['finalRunIndex'],
        'finalBytes' => $fakeSequence['finalBytes'],
        'finalPdfSha256' => $fakeSequence['finalPdfSha256'],
        'finalResourceArtifactsSha256' => $fakeSequence['finalResourceArtifactsSha256'],
        'finalEngineDependencyArtifactsSha256' => $fakeSequence['finalEngineDependencyArtifactsSha256'],
        'finalEngineInputFiles' => $fakeSequence['finalEngineInputFiles'],
        'finalEngineExternalInputFiles' => $fakeSequence['finalEngineExternalInputFiles'],
        'finalEngineOutputFiles' => $fakeSequence['finalEngineOutputFiles'],
        'finalEngineTranscriptInputFiles' => $fakeSequence['finalEngineTranscriptInputFiles'],
        'finalEngineTranscriptExternalInputFiles' => $fakeSequence['finalEngineTranscriptExternalInputFiles'],
        'finalBibliographyArtifactsSha256' => $fakeSequence['finalBibliographyArtifactsSha256'],
        'finalSourceMapArtifactsSha256' => $fakeSequence['finalSourceMapArtifactsSha256'],
        'finalSourceMapFiles' => $fakeSequence['finalSourceMapFiles'],
        'finalSourceMapInputs' => $fakeSequence['finalSourceMapInputs'],
        'finalSourceMapLineRanges' => $fakeSequence['finalSourceMapLineRanges'],
        'missingResourceFiles' => $fakeSequence['missingResourceFiles'],
        'finalDeclaredOutputPages' => $fakeSequence['finalDeclaredOutputPages'],
        'finalPdfPageCount' => $fakeSequence['finalPdfPageCount'],
        'finalPdfTrailerCount' => $fakeSequence['finalPdfTrailerCount'],
        'finalPdfTrailerRevisions' => $fakeSequence['finalPdfTrailerRevisions'],
        'finalPdfStartXrefOffsets' => $fakeSequence['finalPdfStartXrefOffsets'],
        'finalPdfIncrementalUpdates' => $fakeSequence['finalPdfIncrementalUpdates'],
        'finalPdfHeaderVersion' => $fakeSequence['finalPdfHeaderVersion'],
        'finalPdfCatalogVersion' => $fakeSequence['finalPdfCatalogVersion'],
        'finalPdfEffectiveVersion' => $fakeSequence['finalPdfEffectiveVersion'],
        'finalPdfExtensionMetadata' => $fakeSequence['finalPdfExtensionMetadata'],
        'finalPdfXrefStreams' => $fakeSequence['finalPdfXrefStreams'],
        'finalPdfXrefStreamFilters' => $fakeSequence['finalPdfXrefStreamFilters'],
        'finalPdfObjectStreams' => $fakeSequence['finalPdfObjectStreams'],
        'finalPdfObjectStreamFilters' => $fakeSequence['finalPdfObjectStreamFilters'],
        'finalPdfPageBoxes' => $fakeSequence['finalPdfPageBoxes'],
        'finalPdfPageRotations' => $fakeSequence['finalPdfPageRotations'],
        'finalPdfPageLabels' => $fakeSequence['finalPdfPageLabels'],
        'finalPdfPageTimings' => $fakeSequence['finalPdfPageTimings'],
        'finalPdfPageViewports' => $fakeSequence['finalPdfPageViewports'],
        'finalPdfPageContentStreams' => $fakeSequence['finalPdfPageContentStreams'],
        'finalPdfPageContentResourceUsage' => $fakeSequence['finalPdfPageContentResourceUsage'],
        'finalPdfFonts' => $fakeSequence['finalPdfFonts'],
        'finalPdfFontSubtypes' => $fakeSequence['finalPdfFontSubtypes'],
        'finalPdfImages' => $fakeSequence['finalPdfImages'],
        'finalPdfImageColorSpaces' => $fakeSequence['finalPdfImageColorSpaces'],
        'finalPdfImageFilters' => $fakeSequence['finalPdfImageFilters'],
        'finalPdfFormXObjects' => $fakeSequence['finalPdfFormXObjects'],
        'finalPdfFormXObjectFilters' => $fakeSequence['finalPdfFormXObjectFilters'],
        'finalPdfOutlineTitles' => $fakeSequence['finalPdfOutlineTitles'],
        'finalPdfOutlines' => $fakeSequence['finalPdfOutlines'],
        'finalPdfDocumentInfo' => $fakeSequence['finalPdfDocumentInfo'],
        'finalPdfXmpMetadata' => $fakeSequence['finalPdfXmpMetadata'],
        'finalPdfPageMetadata' => $fakeSequence['finalPdfPageMetadata'],
        'finalPdfPieceInfo' => $fakeSequence['finalPdfPieceInfo'],
        'finalPdfOutputIntents' => $fakeSequence['finalPdfOutputIntents'],
        'finalPdfLanguage' => $fakeSequence['finalPdfLanguage'],
        'finalPdfPageLayout' => $fakeSequence['finalPdfPageLayout'],
        'finalPdfPageMode' => $fakeSequence['finalPdfPageMode'],
        'finalPdfOpenAction' => $fakeSequence['finalPdfOpenAction'],
        'finalPdfNamedDestinations' => $fakeSequence['finalPdfNamedDestinations'],
        'finalPdfUriBase' => $fakeSequence['finalPdfUriBase'],
        'finalPdfViewerPreferences' => $fakeSequence['finalPdfViewerPreferences'],
        'finalPdfTaggingMetadata' => $fakeSequence['finalPdfTaggingMetadata'],
        'finalPdfStructureElements' => $fakeSequence['finalPdfStructureElements'],
        'finalPdfMarkedContentProperties' => $fakeSequence['finalPdfMarkedContentProperties'],
        'finalPdfOptionalContentGroups' => $fakeSequence['finalPdfOptionalContentGroups'],
        'finalPdfOptionalContentConfig' => $fakeSequence['finalPdfOptionalContentConfig'],
        'finalPdfCollectionMetadata' => $fakeSequence['finalPdfCollectionMetadata'],
        'finalPdfAcroFormMetadata' => $fakeSequence['finalPdfAcroFormMetadata'],
        'finalPdfThreads' => $fakeSequence['finalPdfThreads'],
        'finalPdfCatalogPermissions' => $fakeSequence['finalPdfCatalogPermissions'],
        'finalPdfSignatures' => $fakeSequence['finalPdfSignatures'],
        'finalPdfSignatureSubFilters' => $fakeSequence['finalPdfSignatureSubFilters'],
        'finalPdfActiveActions' => $fakeSequence['finalPdfActiveActions'],
        'finalPdfActiveActionTypes' => $fakeSequence['finalPdfActiveActionTypes'],
        'finalPdfRichMediaAnnotations' => $fakeSequence['finalPdfRichMediaAnnotations'],
        'finalPdfRichMediaActivationModes' => $fakeSequence['finalPdfRichMediaActivationModes'],
        'finalPdfAnnotations' => $fakeSequence['finalPdfAnnotations'],
        'finalPdfAnnotationTypes' => $fakeSequence['finalPdfAnnotationTypes'],
        'finalPdfLinkTargets' => $fakeSequence['finalPdfLinkTargets'],
        'finalPdfEmbeddedFileNames' => $fakeSequence['finalPdfEmbeddedFileNames'],
        'finalPdfEmbeddedFiles' => $fakeSequence['finalPdfEmbeddedFiles'],
        'finalPdfFormFields' => $fakeSequence['finalPdfFormFields'],
        'finalPdfFormFieldTypes' => $fakeSequence['finalPdfFormFieldTypes'],
        'finalPdfEncrypted' => $fakeSequence['finalPdfEncrypted'],
        'finalPdfEncryptionFilter' => $fakeSequence['finalPdfEncryptionFilter'],
        'finalPdfEncryptionVersion' => $fakeSequence['finalPdfEncryptionVersion'],
        'finalPdfEncryptionRevision' => $fakeSequence['finalPdfEncryptionRevision'],
        'finalPdfEncryptionLength' => $fakeSequence['finalPdfEncryptionLength'],
        'finalPdfPermissionInteger' => $fakeSequence['finalPdfPermissionInteger'],
        'finalPdfPermissionFlags' => $fakeSequence['finalPdfPermissionFlags'],
        'finalPdfEncryptMetadata' => $fakeSequence['finalPdfEncryptMetadata'],
        'bibliographyWarnings' => $fakeSequence['bibliographyWarnings'],
        'bibliographyErrors' => $fakeSequence['bibliographyErrors'],
        'bibliographyNeeded' => $fakeSequence['bibliographyNeeded'],
        'rerunNeeded' => $fakeSequence['rerunNeeded'],
        'engineWarnings' => $fakeSequence['engineWarnings'],
        'diagnostics' => $fakeSequence['diagnostics'],
    ],
];

if (in_array('--self-test', $argv, true)) {
    foreach ([
        'xelatex',
        'latex',
        'handoff/pdf-review-packet.tex',
        'handoff/pdf-review-packet.pdf',
        'PDF Review Packet',
        'templates/review-packet.tex',
        'templates/review-header.tex',
        'media/review-chart.png',
        'refs/migration-log.bib',
        'https://example.test/media/remote-chart.png',
        'handoff/pdf-review-packet.log',
        'handoff/pdf-review-packet.aux',
        'handoff/pdf-review-packet.bcf',
        'handoff/pdf-review-packet.bbl',
        'handoff/pdf-review-packet.blg',
        'handoff/pdf-review-packet.run.xml',
        'handoff/pdf-review-packet.fls',
        'handoff/pdf-review-packet.synctex.gz',
        'documentclass=scrartcl',
        '-recorder',
        '-synctex=1',
        '--resource-path=media:review assets',
        'Source Serif 4',
        'resourceFileManifest',
        'pdf-resource-files:2',
        'pdf-remote-resources:1',
        'source-artifacts-validated:2',
        'resource-files-validated:2',
        'resourceArtifactsSha256',
        'produced-engine-artifacts:8',
        'engineDependencyArtifactsSha256',
        'engineInputFiles',
        'engineExternalInputFiles',
        'engineOutputFiles',
        'engineTranscriptInputFiles',
        'engineTranscriptExternalInputFiles',
        'missingEngineTranscriptInputFiles',
        'engine-dependency-artifacts:1',
        'engine-dependency-files:5',
        'engine-external-input-files:1',
        'engine-output-files:7',
        'engine-transcript-input-files:4',
        'engine-transcript-external-input-files:1',
        'article.cls',
        'bibliography-sidecars:3',
        'bibliography-log-files:1',
        'source-map-files:1',
        'source-map-inputs:2',
        'source-map-line-ranges:2',
        'sourceMapArtifactsSha256',
        'sourceMapLineRanges',
        'bibliography-warnings:3',
        'bibliography-run-needed',
        'engine-log-warnings:2',
        'engine-rerun-needed',
        'engine-output-file:handoff/pdf-review-packet.pdf',
        'engine-output-pages:2',
        'pdfTrailerComplete',
        'pdfTrailerCount',
        '"pdfTrailerCount":2',
        'pdfTrailerRevisions',
        '"prev":512',
        '"startxref":1024',
        'pdfStartXrefOffsets',
        '"pdfStartXrefOffsets":[512,1024]',
        'pdfIncrementalUpdates',
        '"pdfIncrementalUpdates":true',
        'pdfHeaderVersion',
        '"pdfHeaderVersion":"1.5"',
        'pdfCatalogVersion',
        '"pdfCatalogVersion":"1.7"',
        'pdfEffectiveVersion',
        '"pdfEffectiveVersion":"1.7"',
        'pdfExtensionMetadata',
        '"prefix":"ADBE"',
        '"baseVersion":"1.7"',
        '"extensionLevel":8',
        'pdf-byte-trailers:2',
        'pdf-byte-startxref:2',
        'pdf-byte-incremental-updates',
        'pdf-byte-header-version:1.5',
        'pdf-byte-catalog-version:1.7',
        'pdf-byte-effective-version:1.7',
        'pdf-byte-extension-metadata:1',
        'pdfPageCount',
        '"pdfPageCount":2',
        'pdfPageBoxes',
        '"pageObject":"3 0 R"',
        '"mediaBox":[0,0,612,792]',
        '"cropBox":[18,18,594,774]',
        '"trimBox":[36,36,576,756]',
        '"artBox":[72,72,540,720]',
        '"rotation":90',
        '"inherited":["cropBox","mediaBox"]',
        'pdfPageRotations',
        '"pdfPageRotations":{"1":90,"2":270}',
        'pdfPageLabels',
        'finalPdfPageLabels',
        '"styleLabel":"lower-roman"',
        '"firstLabel":"front-iii"',
        '"styleLabel":"decimal"',
        '"firstLabel":"packet-1"',
        'pdf-byte-page-labels:2',
        'pdfPageTimings',
        'finalPdfPageTimings',
        '"duration":6.5',
        '"transitionType":"Fade"',
        '"transitionDuration":1.25',
        '"transitionType":"Wipe"',
        '"direction":"90"',
        '"dimension":"H"',
        '"motion":"I"',
        '"scale":0.8',
        '"background":true',
        'pdf-byte-page-timings:2',
        'pdf-byte-page-durations:1',
        'pdf-byte-page-transitions:2',
        'pdf-byte-page-transition-type:Fade:1',
        'pdf-byte-page-transition-type:Wipe:1',
        'pdfPageViewports',
        'finalPdfPageViewports',
        '"viewportObject":"68 0 R"',
        '"source":"page:3 0 R.VP[0]"',
        '"name":"Review crop measure"',
        '"bbox":[72,72,540,720]',
        '"measureSubtype":"RL"',
        '"scaleRatio":"1 in = 12 pt"',
        '"xUnits":[{"unit":"in","conversionFactor":1,"fractionalDisplay":"D"}]',
        '"yUnits":[{"unit":"pt","conversionFactor":12,"fractionalDisplay":null}]',
        '"distanceUnits":[{"unit":"pt","conversionFactor":12,"fractionalDisplay":null}]',
        'pdf-byte-page-viewports:1',
        'pdf-byte-page-viewport-measures:1',
        'pdf-byte-page-viewport-unit-formats:3',
        'pdfPageContentStreams',
        'finalPdfPageContentStreams',
        '"contentObject":"66 0 R"',
        '"source":"page:3 0 R.Contents[0]"',
        '"textObjectCount":1',
        '"imagePaintCount":1',
        '"formPaintCount":1',
        '"markedContentBeginCount":1',
        '"markedContentEndCount":1',
        '"mcidValues":[12]',
        '"propertyNames":["Span"]',
        '"resourceNames":["ImChart","FxOverlay"]',
        '"contentObject":"67 0 R"',
        '"filters":["FlateDecode"]',
        '"streamSkipped":"filtered"',
        'pdfPageContentResourceUsage',
        'finalPdfPageContentResourceUsage',
        '"FxOverlay":1',
        '"ImChart":1',
        'pdf-byte-page-content-streams:2',
        'pdf-byte-page-content-text-objects:1',
        'pdf-byte-page-content-image-paints:1',
        'pdf-byte-page-content-form-paints:1',
        'pdf-byte-page-content-marked-begins:1',
        'pdf-byte-page-content-stream-skipped:filtered',
        'pdf-byte-page-content-resource:ImChart:1',
        'pdfFonts',
        'finalPdfFonts',
        '"resourceName":"FReview"',
        '"baseFont":"ABCDEE+SourceSerif4-Regular"',
        '"descriptorFontFamily":"Source Serif 4"',
        '"embeddedFileKind":"FontFile2"',
        '"embeddedFile":"33 0 R"',
        'pdfFontSubtypes',
        'finalPdfFontSubtypes',
        '"Type0":1',
        '"Type1":1',
        'pdf-byte-font-resources:2',
        'pdf-byte-font-subtypes:2',
        'pdf-byte-embedded-fonts:1',
        'pdfImages',
        'finalPdfImages',
        '"resourceName":"ImChart"',
        '"width":640',
        '"height":360',
        '"colorSpace":"DeviceRGB"',
        '"filters":["DCTDecode"]',
        'pdfImageColorSpaces',
        'finalPdfImageColorSpaces',
        'pdfImageFilters',
        'finalPdfImageFilters',
        'pdf-byte-image-xobjects:1',
        'pdf-byte-image-streams:1',
        'pdf-byte-image-color-spaces:1',
        'pdf-byte-image-filters:1',
        'pdf-byte-image-filter:DCTDecode:1',
        'pdfFormXObjects',
        'finalPdfFormXObjects',
        '"resourceName":"FxOverlay"',
        '"formObject":"42 0 R"',
        '"bbox":[0,0,144,72]',
        '"matrix":[1,0,0,1,24,36]',
        '"resourcesPresent":true',
        '"groupSubtype":"Transparency"',
        '"groupColorSpace":"DeviceRGB"',
        '"groupIsolated":true',
        '"groupKnockout":false',
        'pdfFormXObjectFilters',
        'finalPdfFormXObjectFilters',
        'pdf-byte-form-xobjects:1',
        'pdf-byte-form-xobject-streams:1',
        'pdf-byte-form-xobject-groups:1',
        'pdfXrefStreams',
        'finalPdfXrefStreams',
        '"object":"36 0 R"',
        '"size":37',
        '"index":[0,35,35,2]',
        '"w":[1,2,1]',
        'pdfXrefStreamFilters',
        'finalPdfXrefStreamFilters',
        'pdf-byte-xref-streams:1',
        'pdf-byte-xref-stream-filters:1',
        'pdf-byte-xref-stream-filter:FlateDecode:1',
        'pdf-byte-xref-stream-skipped:filtered',
        'pdfObjectStreams',
        'finalPdfObjectStreams',
        '"object":"35 0 R"',
        '"objectCount":2',
        '"objectNumbers":[80,81]',
        'pdfObjectStreamFilters',
        'finalPdfObjectStreamFilters',
        'pdf-byte-object-streams:1',
        'pdf-byte-object-stream-objects:2',
        'pdf-byte-page-boxes:2',
        'pdf-byte-page-rotations:2',
        'pdfOutlineTitles',
        'pdfOutlines',
        'Review packet',
        'Import checklist',
        '"object":"6 0 R"',
        '"destFit":"Fit"',
        'pdf-byte-outline-metadata:2',
        'pdf-byte-outline-destinations:2',
        'pdfDocumentInfo',
        '"Title":"PDF Review Packet"',
        '"Author":"Migration Desk"',
        '"Producer":"XeTeX fake runner"',
        'pdfXmpMetadata',
        '"packetSha256"',
        '"title":"PDF Review Packet"',
        '"description":"Migration review metadata"',
        '"format":"application/pdf"',
        '"creatorTool":"Pandoc native handoff"',
        '"createDate":"2026-06-05T07:41:23Z"',
        '"modifyDate":"2026-06-05T07:42:00Z"',
        '"metadataDate":"2026-06-05T07:42:10Z"',
        '"documentId":"uuid:pdf-review-packet"',
        '"instanceId":"uuid:pdf-review-packet-v2"',
        '"creators":["Migration Desk","Content Reviewer"]',
        '"pdfaIdentification":{"part":"2","conformance":"B"}',
        'pdf-byte-xmp-metadata:13',
        'pdf-byte-pdfa:2:B',
        'pdfPageMetadata',
        'finalPdfPageMetadata',
        '"metadataObject":"54 0 R"',
        '"title":"Review packet page 1"',
        '"description":"Page-level review provenance"',
        '"creatorTool":"Pandoc page handoff"',
        'pdf-byte-page-metadata:1',
        'pdf-byte-page-metadata-titles:1',
        'pdfPieceInfo',
        'finalPdfPieceInfo',
        'catalog.PieceInfo',
        'page:3 0 R.PieceInfo',
        '"application":"PandocHandoff"',
        '"application":"TeXSource"',
        '"privateObject":"inline"',
        '"privateObject":"55 0 R"',
        '"privateKeys":["Imported","Pipeline","Revision","Source"]',
        '"privateValues":{"Imported":true,"Pipeline":"pdf-engine-handoff","Revision":2,"Source":"pandoc-native"}',
        '"privateStreamBytes":49',
        '"privateStreamSha256"',
        'pdf-byte-piece-info:2',
        'pdf-byte-piece-info-pages:1',
        'pdf-byte-piece-info-private-streams:1',
        'pdfOutputIntents',
        '"subtype":"GTS_PDFA1"',
        '"outputConditionIdentifier":"sRGB IEC61966-2.1"',
        '"outputCondition":"sRGB display profile"',
        '"registryName":"http://www.color.org"',
        '"info":"sRGB review profile"',
        '"destOutputProfile":"18 0 R"',
        '"profileComponents":3',
        '"profileAlternate":"DeviceRGB"',
        '"profileSha256"',
        'pdf-byte-output-intents:1',
        'pdf-byte-output-profiles:1',
        'pdfLanguage',
        '"pdfLanguage":"en-US"',
        'pdf-byte-document-info:9',
        'pdf-byte-language:en-US',
        'pdfPageLayout',
        '"pdfPageLayout":"TwoPageRight"',
        'pdfPageMode',
        '"pdfPageMode":"UseOutlines"',
        'pdfOpenAction',
        '"pageObject":"3 0 R"',
        '"fit":"FitH"',
        'pdfNamedDestinations',
        'finalPdfNamedDestinations',
        'catalog.Names.Dests',
        'catalog.Dests',
        'review-start',
        'import-checklist',
        'packet-summary',
        'pdf-byte-named-destinations:3',
        'pdfUriBase',
        'finalPdfUriBase',
        '"pdfUriBase":"https://example.test/review/"',
        'pdf-byte-uri-base:https://example.test/review/',
        'pdfViewerPreferences',
        '"DisplayDocTitle":true',
        '"HideToolbar":true',
        '"Direction":"L2R"',
        '"PrintScaling":"None"',
        '"NumCopies":2',
        'pdf-byte-page-layout:TwoPageRight',
        'pdf-byte-page-mode:UseOutlines',
        'pdf-byte-open-action:destination',
        'pdf-byte-viewer-preferences:5',
        'pdfTaggingMetadata',
        'finalPdfTaggingMetadata',
        '"marked":true',
        '"userProperties":true',
        '"suspects":false',
        '"structTreeRoot":"22 0 R"',
        '"roleMap":{"Aside":"Sect","Figure":"Figure","H1":"H"}',
        '"structureChildren":2',
        '"parentTree":"25 0 R"',
        '"parentTreeNextKey":5',
        '"idTree":"26 0 R"',
        'pdf-byte-tagging-metadata:9',
        'pdf-byte-tagged',
        'pdf-byte-structure-root:22 0 R',
        'pdf-byte-structure-role-map:3',
        'pdf-byte-structure-children:2',
        'pdfStructureElements',
        'finalPdfStructureElements',
        '"object":"23 0 R"',
        '"type":"H1"',
        '"parent":"22 0 R"',
        '"alt":"Review packet heading"',
        '"actualText":"PDF Review Packet"',
        '"language":"en-US"',
        '"title":"packet-title"',
        '"childCount":1',
        'Reviewer formula and citation paragraph',
        'pdf-byte-structure-elements:2',
        'pdf-byte-structure-alt-text:1',
        'pdf-byte-structure-actual-text:2',
        'pdf-byte-structure-languages:2',
        'pdfMarkedContentProperties',
        'finalPdfMarkedContentProperties',
        '"propertyName":"MCFigure"',
        '"propertyObject":"56 0 R"',
        '"mcid":12',
        '"expanded":"Expanded chart data source"',
        '"associatedFiles":["57 0 R"]',
        'marked-content:3 0 R.Properties.MCFigure.AF',
        'pdf-byte-marked-content-properties:1',
        'pdf-byte-marked-content-associated-files:1',
        'pdfOptionalContentGroups',
        'finalPdfOptionalContentGroups',
        '"name":"Reviewer notes"',
        '"name":"Print marks"',
        '"intent":["View","Design"]',
        '"usagePrintState":"OFF"',
        '"usageExportState":"ON"',
        '"usageCreator":"layer package"',
        '"usageLanguage":"en-US"',
        '"usageZoomMin":0.5',
        'pdfOptionalContentConfig',
        'finalPdfOptionalContentConfig',
        '"baseState":"ON"',
        '"listMode":"VisiblePages"',
        '"on":["38 0 R"]',
        '"off":["39 0 R"]',
        '"orderLabels":["Reviewer overlays"]',
        'pdf-byte-optional-content-groups:2',
        'pdf-byte-optional-content-config',
        'pdf-byte-optional-content-off:1',
        'pdfCollectionMetadata',
        'finalPdfCollectionMetadata',
        '"view":"T"',
        '"defaultDocument":"review-assets.zip"',
        '"schemaFields"',
        '"name":"Title"',
        '"title":"Review title"',
        '"subtype":"Size"',
        '"ascending":[true,false]',
        'pdf-byte-collection',
        'pdf-byte-collection-schema-fields:2',
        'pdf-byte-collection-sort-fields:2',
        'pdfThreads',
        'finalPdfThreads',
        '"object":"47 0 R"',
        '"infoTitle":"Review reading order"',
        '"infoAuthor":"Migration Desk"',
        '"infoSubject":"PDF article thread"',
        '"firstBead":"48 0 R"',
        '"beadCount":2',
        '"object":"49 0 R"',
        '"pageObject":"4 0 R"',
        '"rect":[72,96,540,144]',
        'pdf-byte-threads:1',
        'pdf-byte-thread-beads:2',
        'pdf-byte-thread-info-titles:1',
        'pdfAcroFormMetadata',
        'finalPdfAcroFormMetadata',
        '"fieldReferences":["13 0 R","40 0 R"]',
        '"fieldCount":2',
        '"needAppearances":true',
        '"sigFlags":3',
        '"sigFlagNames":["signaturesExist","appendOnly"]',
        '"defaultResourcesPresent":true',
        '"defaultAppearance":"/Helv 10 Tf 0 g"',
        '"quadding":1',
        '"calculationOrder":["13 0 R"]',
        '"xfaPresent":true',
        '"xfaPacketNames":["template","datasets"]',
        'pdf-byte-acroform-fields:2',
        'pdf-byte-acroform-need-appearances',
        'pdf-byte-acroform-sigflags:3',
        'pdf-byte-acroform-xfa-packets:2',
        'pdfCatalogPermissions',
        'finalPdfCatalogPermissions',
        '"permission":"DocMDP"',
        'pdfSignatures',
        'finalPdfSignatures',
        '"fieldName":"review.signature"',
        '"signatureObject":"41 0 R"',
        '"filter":"Adobe.PPKLite"',
        '"subFilter":"ETSI.CAdES.detached"',
        '"reason":"Review packet approval"',
        '"location":"Remote review"',
        '"contactInfo":"review@example.test"',
        '"signingTime":"D:20260605121500Z"',
        '"byteRange":[0,123,456,789]',
        '"byteRangeSegmentCount":2',
        '"coveredBytes":912',
        '"contentsBytes":12',
        '"transformMethod":"DocMDP"',
        'pdf-byte-catalog-permissions:1',
        'pdf-byte-catalog-permission-byte-ranges:1',
        'pdf-byte-catalog-permission-reference-transforms:2',
        'pdf-byte-catalog-permission-subfilter:ETSI.CAdES.detached:1',
        '"transformMethod":"FieldMDP"',
        '"fields":["reviewer.name","approved"]',
        'pdfSignatureSubFilters',
        'finalPdfSignatureSubFilters',
        '"ETSI.CAdES.detached":1',
        'pdf-byte-signatures:1',
        'pdf-byte-signature-subfilters:1',
        'pdf-byte-signature-byte-ranges:1',
        'pdf-byte-signature-reference-transforms:2',
        'pdfActiveActions',
        'finalPdfActiveActions',
        'catalog.Names.JavaScript.ReviewOpen',
        'page:3 0 R.AA.O',
        'catalog.AA.WC',
        '"type":"JavaScript"',
        '"type":"Launch"',
        '"scriptSha256"',
        'pdfActiveActionTypes',
        'finalPdfActiveActionTypes',
        '"JavaScript":2',
        '"Launch":1',
        'pdf-byte-active-actions:3',
        'pdf-byte-active-action-types:2',
        'pdf-byte-active-action-type:JavaScript:2',
        'pdfRichMediaAnnotations',
        'finalPdfRichMediaAnnotations',
        '"annotationObject":"59 0 R"',
        '"contentObject":"60 0 R"',
        '"settingsObject":"61 0 R"',
        '"assetNames":["captions.vtt","review-video.mp4"]',
        '"activationCondition":"PO"',
        '"deactivationCondition":"PC"',
        '"presentationStyle":"Embedded"',
        '"presentationTransparent":true',
        '"presentationToolbar":false',
        '"presentationNavigationPane":false',
        '"presentationPassContextClick":true',
        '"name":"Review video configuration"',
        '"assetReferences":["62 0 R"]',
        'pdfRichMediaActivationModes',
        'finalPdfRichMediaActivationModes',
        '"PO":1',
        'pdf-byte-rich-media-annotations:1',
        'pdf-byte-rich-media-assets:2',
        'pdf-byte-rich-media-configurations:1',
        'pdf-byte-rich-media-activation:PO:1',
        'pdf-byte-rich-media-deactivation:PC:1',
        'pdfAnnotations',
        'finalPdfAnnotations',
        '"annotationObject":"8 0 R"',
        '"subtype":"Link"',
        '"subtype":"RichMedia"',
        '"rect":[72,640,360,672]',
        '"contents":"Review packet link"',
        '"title":"Migration Desk"',
        '"name":"review-link-1"',
        '"modified":"D:20260606051200Z"',
        '"flagNames":["print"]',
        'pdf-byte-annotation-metadata:5',
        'pdf-byte-annotation-contents:2',
        'pdf-byte-annotation-actions:1',
        'pdf-byte-annotation-flags:1',
        'pdfAnnotationTypes',
        '"FileAttachment":1',
        '"Link":1',
        '"RichMedia":1',
        '"Widget":2',
        'pdfLinkTargets',
        'https://example.test/review/pdf-review-packet',
        'pdfEmbeddedFileNames',
        'pdfEmbeddedFiles',
        'figure-source.json',
        'marked-figure-source.json',
        'page-note.txt',
        'review-assets.zip',
        '"source":"structure:23 0 R.AF"',
        '"source":"page:3 0 R.AF"',
        '"source":"marked-content:3 0 R.Properties.MCFigure.AF"',
        '"description":"Marked content source data"',
        '"description":"Figure source data"',
        '"description":"Page review note"',
        '"afRelationship":"Source"',
        '"afRelationship":"Supplement"',
        '"description":"Review source package"',
        '"afRelationship":"Data"',
        '"subtype":"application/json"',
        '"subtype":"text/plain"',
        '"subtype":"application/zip"',
        '"streamSha256"',
        '"checksum":"00112233445566778899AABBCCDDEEFF"',
        'pdfFormFields',
        '"name":"reviewer.name"',
        '"name":"review.signature"',
        '"typeLabel":"text"',
        '"typeLabel":"signature"',
        '"alternateName":"Reviewer name"',
        '"mappingName":"reviewer_name"',
        '"flagNames":["required","multiline"]',
        'pdfFormFieldTypes',
        '"text":1',
        '"signature":1',
        'pdfEncrypted',
        'fakeProtectedPdf',
        '"pdfEncrypted":true',
        '"pdfEncryptionFilter":"Standard"',
        '"pdfEncryptionVersion":4',
        '"pdfEncryptionRevision":4',
        '"pdfEncryptionLength":128',
        '"pdfPermissionInteger":-44',
        '"pdfEncryptMetadata":false',
        'pdfPermissionFlags',
        '"copy":true',
        '"modify":false',
        'pdf-output-encrypted',
        'pdf-encryption-filter:Standard',
        'pdf-permission-flags:8',
        'pdf-byte-form-fields:2',
        'pdf-byte-form-field-types:2',
        'pdf-byte-annotations:5',
        'pdf-byte-link-targets:1',
        'pdf-byte-embedded-files:6',
        'pdf-byte-embedded-file-metadata:6',
        'pdf-byte-embedded-file-streams:4',
        'pdf-byte-page-count:2',
        'pdf-byte-outline-items:2',
        'migration-log',
        'fake-runner-no-execution',
        'fakeMissingProgram',
        'engine-program-missing:xelatex',
        '"engineMissingProgram":true',
        '"engineMissingProgramName":"xelatex"',
        'fakeRunSequence',
        'fake-runner-attempts:2',
        'fake-runner-attempt-rerun-needed:1',
        'fake-runner-attempt-bibliography-needed:1',
        'fake-runner-final-rerun-cleared',
        'fake-runner-final-bibliography-cleared',
        'finalResourceArtifactsSha256',
        'finalEngineDependencyArtifactsSha256',
        'finalEngineInputFiles',
        'finalEngineExternalInputFiles',
        'finalEngineOutputFiles',
        'finalEngineTranscriptInputFiles',
        'finalEngineTranscriptExternalInputFiles',
        'finalBibliographyArtifactsSha256',
        'finalSourceMapArtifactsSha256',
        'finalSourceMapLineRanges',
        'finalPdfPageCount',
        'finalPdfTrailerCount',
        'finalPdfTrailerRevisions',
        'finalPdfStartXrefOffsets',
        'finalPdfIncrementalUpdates',
        'finalPdfHeaderVersion',
        'finalPdfCatalogVersion',
        'finalPdfEffectiveVersion',
        'finalPdfExtensionMetadata',
        'finalPdfPageBoxes',
        'finalPdfPageRotations',
        'finalPdfPageTimings',
        'finalPdfOutlineTitles',
        'finalPdfOutlines',
        'finalPdfDocumentInfo',
        'finalPdfXmpMetadata',
        'finalPdfOutputIntents',
        'finalPdfLanguage',
        'finalPdfPageLayout',
        'finalPdfPageMode',
        'finalPdfOpenAction',
        'finalPdfViewerPreferences',
        'finalPdfTaggingMetadata',
        'finalPdfStructureElements',
        'finalPdfMarkedContentProperties',
        'finalPdfOptionalContentGroups',
        'finalPdfOptionalContentConfig',
        'finalPdfThreads',
        'finalPdfCatalogPermissions',
        'finalPdfActiveActions',
        'finalPdfActiveActionTypes',
        'finalPdfAnnotationTypes',
        'finalPdfLinkTargets',
        'finalPdfEmbeddedFileNames',
        'finalPdfEmbeddedFiles',
        'finalPdfFormFields',
        'finalPdfFormFieldTypes',
        'finalPdfEncrypted',
        'bibliographyWarnings',
        '"successfulAttempts":2',
        '"rerunNeeded":false',
    ] as $needle) {
        if (!str_contains(json_encode($summary, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES), $needle)) {
            throw new RuntimeException('PDF engine handoff self-test missing: ' . $needle);
        }
    }

    echo "pdf engine handoff self-test ok\n";
    return;
}

echo json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
