<?php

declare(strict_types=1);

namespace PortLibs\Pandoc;

final class DocxWriterGoldenManifest
{
    public const DEFAULT_RELATIVE_DOCX_DIR = DocxParityCorpusAudit::DEFAULT_RELATIVE_DOCX_DIR;
    public const STATUS_REPORTED = 'reported_writer_golden_package_inventory_no_writer';
    public const STATUS_SKIPPED_MISSING_GOLDEN_DIRECTORY = 'skipped_missing_writer_golden_directory';
    public const STATUS_SKIPPED_UNREADABLE_GOLDEN_DIRECTORY = 'skipped_unreadable_writer_golden_directory';
    public const EVIDENCE_KIND = 'writer-golden-package-inventory-only';
    public const EXPECTED_WRITER_CLASS = 'PortLibs\\Pandoc\\DocxWriter';
    public const EXPECTED_WRITER_RELATIVE_PATH = 'lanes/pandoc/src/DocxWriter.php';
    public const OPEN_REASON = 'writer-unsupported-no-DocxWriter-implementation-and-docx-output-registry-unsupported';
    public const CLAIM = 'Inventories upstream golden DOCX packages and local writer support status only; no generated DOCX package comparison or writer parity is asserted.';

    private readonly string $repoRoot;
    private readonly string $docxDirectory;

    public function __construct(string $repoRoot, string $docxDirectory = self::DEFAULT_RELATIVE_DOCX_DIR, private readonly int $sampleLimit = 8)
    {
        if ($repoRoot === '') {
            throw new \InvalidArgumentException('Repository root must not be empty');
        }
        if ($docxDirectory === '') {
            throw new \InvalidArgumentException('DOCX directory must not be empty');
        }
        if ($sampleLimit < 0) {
            throw new \InvalidArgumentException('Sample limit must not be negative');
        }

        $this->repoRoot = rtrim($repoRoot, DIRECTORY_SEPARATOR);
        $this->docxDirectory = $docxDirectory;
    }

    /**
     * @return array<string, mixed>
     */
    public function report(): array
    {
        $goldenDir = $this->absoluteGoldenDirectory();
        $writer = $this->localWriterEvidence();

        if (!is_dir($goldenDir)) {
            return $this->skipReport(
                self::STATUS_SKIPPED_MISSING_GOLDEN_DIRECTORY,
                "Upstream DOCX writer golden directory does not exist: {$goldenDir}",
                $writer
            );
        }
        if (!is_readable($goldenDir)) {
            return $this->skipReport(
                self::STATUS_SKIPPED_UNREADABLE_GOLDEN_DIRECTORY,
                "Upstream DOCX writer golden directory is not readable: {$goldenDir}",
                $writer
            );
        }

        $packageRows = $this->packageRows($goldenDir);
        $packageCount = count($packageRows);
        $readablePackages = count(array_filter(
            $packageRows,
            static fn (array $row): bool => ($row['status'] ?? null) === 'readable'
        ));
        $partCount = array_sum(array_map(
            static fn (array $row): int => (int) ($row['partCount'] ?? 0),
            $packageRows
        ));
        $readablePartCount = array_sum(array_map(
            static fn (array $row): int => (int) ($row['readablePartCount'] ?? 0),
            $packageRows
        ));

        return [
            'schemaVersion' => 1,
            'tool' => 'pandoc-docx-writer-golden-audit',
            'status' => self::STATUS_REPORTED,
            'skipped' => false,
            'claim' => self::CLAIM,
            'evidenceKind' => self::EVIDENCE_KIND,
            'repoRoot' => $this->repoRoot,
            'upstreamDocxDirectory' => $this->absoluteDocxDirectory(),
            'upstreamDocxDirectoryDisplay' => $this->displayPath($this->absoluteDocxDirectory()),
            'goldenDirectory' => $goldenDir,
            'goldenDirectoryDisplay' => $this->displayPath($goldenDir),
            'goldenDirectoryPresent' => true,
            'expectedUpstreamWriterSourceReferences' => self::expectedUpstreamWriterSourceReferences(),
            'localWriter' => $writer,
            'packageComparison' => $this->packageComparisonEvidence($writer),
            'goldenPackageCount' => $packageCount,
            'readableGoldenPackageCount' => $readablePackages,
            'unreadableGoldenPackageCount' => $packageCount - $readablePackages,
            'packagePartCount' => $partCount,
            'readablePackagePartCount' => $readablePartCount,
            'packageRows' => $packageRows,
            'packageSamples' => array_slice($packageRows, 0, $this->sampleLimit),
            'notes' => [
                'Each part hash is the SHA-256 of the uncompressed package part bytes; raw package bytes are not emitted.',
                'These upstream golden DOCX files are expected writer outputs, not generated by the PHP lane.',
                'Writer parity remains open until a local DOCX writer generates packages and compares package parts, relationships, content types, and document XML semantics.',
            ],
        ];
    }

    /**
     * @param array<string, mixed> $report
     */
    public static function formatTextReport(array $report): string
    {
        $lines = [
            'Pandoc DOCX writer golden package manifest',
            'Status: ' . (string) ($report['status'] ?? 'unknown'),
            'Claim: ' . (string) ($report['claim'] ?? self::CLAIM),
            'Golden directory: ' . (string) ($report['goldenDirectoryDisplay'] ?? $report['goldenDirectory'] ?? ''),
        ];

        $writer = $report['localWriter'] ?? [];
        if (is_array($writer)) {
            $lines[] = 'DOCX writer implementation: '
                . (string) ($writer['status'] ?? 'unknown')
                . '; classExists='
                . self::boolText($writer['classExists'] ?? false)
                . '; fileExists='
                . self::boolText($writer['fileExists'] ?? false)
                . '; registryStatus='
                . (string) ($writer['registryStatus'] ?? 'unknown');
        }

        $comparison = $report['packageComparison'] ?? [];
        if (is_array($comparison)) {
            $lines[] = 'Generated package comparison: '
                . ((($comparison['run'] ?? false) === true) ? 'run' : 'not run')
                . '; reason='
                . (string) ($comparison['reason'] ?? 'unknown');
        }

        if (($report['skipped'] ?? false) === true) {
            $lines[] = 'Result: skipped';
            $lines[] = 'Reason: ' . (string) ($report['reason'] ?? 'golden directory unavailable');
            $lines[] = 'No DOCX writer parity is asserted.';

            return implode(PHP_EOL, $lines) . PHP_EOL;
        }

        $lines[] = 'Golden packages: '
            . (int) ($report['goldenPackageCount'] ?? 0)
            . '; readable packages: '
            . (int) ($report['readableGoldenPackageCount'] ?? 0)
            . '; package parts: '
            . (int) ($report['packagePartCount'] ?? 0)
            . '; readable parts: '
            . (int) ($report['readablePackagePartCount'] ?? 0);

        $samples = $report['packageSamples'] ?? [];
        if (is_array($samples) && $samples !== []) {
            $lines[] = 'Golden package samples:';
            foreach ($samples as $row) {
                if (!is_array($row)) {
                    continue;
                }
                $partNames = $row['partNames'] ?? [];
                $partSummary = is_array($partNames) && $partNames !== []
                    ? implode(', ', array_slice(array_map('strval', $partNames), 0, 6))
                    : 'none';
                $lines[] = '- '
                    . (string) ($row['fileName'] ?? 'unknown.docx')
                    . ': parts='
                    . (int) ($row['partCount'] ?? 0)
                    . '; packageSha256='
                    . (string) ($row['packageSha256'] ?? '')
                    . '; firstParts='
                    . $partSummary;
            }
        }

        $lines[] = 'No generated DOCX package parity is asserted.';

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @return list<array<string, string>>
     */
    public static function expectedUpstreamWriterSourceReferences(): array
    {
        return [
            [
                'kind' => 'writer-implementation',
                'path' => 'src/Text/Pandoc/Writers/Docx.hs',
                'role' => 'upstream DOCX writer implementation to port or compare against',
            ],
            [
                'kind' => 'writer-tests',
                'path' => 'test/Tests/Writers/Docx.hs',
                'role' => 'upstream DOCX writer golden-test definitions',
            ],
            [
                'kind' => 'writer-golden-packages',
                'path' => 'test/docx/golden/*.docx',
                'role' => 'expected upstream DOCX writer package outputs',
            ],
            [
                'kind' => 'reference-docx',
                'path' => 'data/default.docx',
                'role' => 'upstream reference DOCX template used by writer behavior',
            ],
        ];
    }

    /**
     * @param array<string, mixed> $writer
     * @return array<string, mixed>
     */
    private function skipReport(string $status, string $reason, array $writer): array
    {
        return [
            'schemaVersion' => 1,
            'tool' => 'pandoc-docx-writer-golden-audit',
            'status' => $status,
            'skipped' => true,
            'claim' => self::CLAIM,
            'evidenceKind' => self::EVIDENCE_KIND,
            'repoRoot' => $this->repoRoot,
            'upstreamDocxDirectory' => $this->absoluteDocxDirectory(),
            'upstreamDocxDirectoryDisplay' => $this->displayPath($this->absoluteDocxDirectory()),
            'goldenDirectory' => $this->absoluteGoldenDirectory(),
            'goldenDirectoryDisplay' => $this->displayPath($this->absoluteGoldenDirectory()),
            'goldenDirectoryPresent' => false,
            'reason' => $reason,
            'expectedUpstreamWriterSourceReferences' => self::expectedUpstreamWriterSourceReferences(),
            'localWriter' => $writer,
            'packageComparison' => $this->packageComparisonEvidence($writer),
            'goldenPackageCount' => 0,
            'readableGoldenPackageCount' => 0,
            'unreadableGoldenPackageCount' => 0,
            'packagePartCount' => 0,
            'readablePackagePartCount' => 0,
            'packageRows' => [],
            'packageSamples' => [],
            'notes' => [
                'The local upstream DOCX corpus cache is optional for CI.',
                'No writer golden package inventory or parity result is inferred when the golden directory is absent.',
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function localWriterEvidence(): array
    {
        $writerPath = $this->repoRoot . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, self::EXPECTED_WRITER_RELATIVE_PATH);
        $writerFileExists = is_file($writerPath);
        $writerClassExists = class_exists(self::EXPECTED_WRITER_CLASS);
        $registry = PandocFormatRegistry::phpOutputSupport()['docx'] ?? [
            'status' => 'unknown',
            'implementation' => '',
            'notes' => 'DOCX output format is missing from the registry.',
        ];
        $registryStatus = (string) ($registry['status'] ?? 'unknown');
        $unsupported = !$writerFileExists && !$writerClassExists && $registryStatus === 'unsupported';

        return [
            'status' => $unsupported ? 'unsupported' : 'implementation-present-or-registered',
            'expectedClass' => self::EXPECTED_WRITER_CLASS,
            'classExists' => $writerClassExists,
            'expectedPath' => self::EXPECTED_WRITER_RELATIVE_PATH,
            'absolutePath' => $writerPath,
            'fileExists' => $writerFileExists,
            'registryFormat' => 'docx',
            'registryStatus' => $registryStatus,
            'registryImplementation' => (string) ($registry['implementation'] ?? ''),
            'registryNotes' => (string) ($registry['notes'] ?? ''),
            'unsupportedReason' => $unsupported ? self::OPEN_REASON : 'docx-writer-comparison-still-not-recorded',
        ];
    }

    /**
     * @param array<string, mixed> $writer
     * @return array<string, mixed>
     */
    private function packageComparisonEvidence(array $writer): array
    {
        return [
            'run' => false,
            'generatedPackageCount' => 0,
            'comparedPackageCount' => 0,
            'reason' => (string) ($writer['unsupportedReason'] ?? self::OPEN_REASON),
            'requiredBeforeParityClaim' => 'Implement and register a native PHP DocxWriter, generate DOCX packages for the upstream writer golden cases, and compare package parts, relationships, content types, and document XML semantics.',
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function packageRows(string $goldenDir): array
    {
        $paths = [];
        foreach (new \DirectoryIterator($goldenDir) as $entry) {
            if (!$entry->isDot() && $entry->isFile() && strtolower($entry->getExtension()) === 'docx') {
                $paths[] = $entry->getPathname();
            }
        }
        sort($paths, SORT_STRING);

        $rows = [];
        foreach ($paths as $path) {
            $rows[] = $this->packageRow($path);
        }

        return $rows;
    }

    /**
     * @return array<string, mixed>
     */
    private function packageRow(string $path): array
    {
        $fileName = basename($path);
        $row = [
            'fileName' => $fileName,
            'file' => $this->displayPath($path),
            'expectedUpstreamGoldenReference' => 'test/docx/golden/' . $fileName,
            'status' => 'unreadable',
            'packageBytes' => 0,
            'packageSha256' => null,
            'partCount' => 0,
            'readablePartCount' => 0,
            'partNames' => [],
            'partRows' => [],
        ];

        try {
            $bytes = file_get_contents($path);
            if (!is_string($bytes)) {
                throw new \RuntimeException("Unable to read writer golden DOCX package: {$path}");
            }

            $package = ZipPackage::fromString($bytes);
            $partRows = $this->partRows($package);
            $partNames = array_map(
                static fn (array $partRow): string => (string) $partRow['name'],
                $partRows
            );

            return array_replace($row, [
                'status' => 'readable',
                'packageBytes' => strlen($bytes),
                'packageSha256' => hash('sha256', $bytes),
                'partCount' => count($partRows),
                'readablePartCount' => count(array_filter(
                    $partRows,
                    static fn (array $partRow): bool => ($partRow['status'] ?? null) === 'readable'
                )),
                'partNames' => $partNames,
                'partRows' => $partRows,
            ]);
        } catch (\Throwable $throwable) {
            return array_replace($row, [
                'status' => 'unreadable',
                'errorClass' => $throwable::class,
                'message' => self::oneLine($throwable->getMessage()),
            ]);
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function partRows(ZipPackage $package): array
    {
        $entries = $package->entries();
        usort(
            $entries,
            static fn (ZipPackageEntry $left, ZipPackageEntry $right): int => strcmp($left->name, $right->name)
        );

        $rows = [];
        foreach ($entries as $entry) {
            $row = [
                'name' => $entry->name,
                'status' => 'unreadable',
                'isDirectory' => $entry->isDirectory(),
                'compressionMethod' => $entry->compressionMethod,
                'compressedBytes' => $entry->compressedSize,
                'declaredUncompressedBytes' => $entry->uncompressedSize,
                'crc32' => $entry->crc32Hex(),
                'sha256' => null,
                'uncompressedBytes' => 0,
            ];

            try {
                $data = $entry->isDirectory() ? '' : $package->read($entry->name);
                $rows[] = array_replace($row, [
                    'status' => 'readable',
                    'sha256' => hash('sha256', $data),
                    'uncompressedBytes' => strlen($data),
                ]);
            } catch (\Throwable $throwable) {
                $rows[] = array_replace($row, [
                    'status' => 'unreadable',
                    'errorClass' => $throwable::class,
                    'message' => self::oneLine($throwable->getMessage()),
                ]);
            }
        }

        return $rows;
    }

    private function absoluteDocxDirectory(): string
    {
        if (str_starts_with($this->docxDirectory, DIRECTORY_SEPARATOR)) {
            return rtrim($this->docxDirectory, DIRECTORY_SEPARATOR);
        }

        return $this->repoRoot . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $this->docxDirectory);
    }

    private function absoluteGoldenDirectory(): string
    {
        return $this->absoluteDocxDirectory() . DIRECTORY_SEPARATOR . 'golden';
    }

    private function displayPath(string $path): string
    {
        $root = $this->repoRoot . DIRECTORY_SEPARATOR;
        if (str_starts_with($path, $root)) {
            return str_replace(DIRECTORY_SEPARATOR, '/', substr($path, strlen($root)));
        }

        return $path;
    }

    private static function boolText(mixed $value): string
    {
        return $value === true ? 'yes' : 'no';
    }

    private static function oneLine(string $message): string
    {
        $message = preg_replace('/\s+/', ' ', trim($message));
        if (!is_string($message)) {
            return '';
        }

        return strlen($message) > 240 ? substr($message, 0, 237) . '...' : $message;
    }
}
