<?php

declare(strict_types=1);

namespace PortLibs\Pandoc;

final class EpubExecutableNativeAstComparisonHarness
{
    private const DEFAULT_MAX_EXAMPLES = 12;
    private const VERDICT = 'pandoc-executable-normalized-ast-comparison-not-full-epub-parity';
    private const CLAIM = 'Compares local PHP EPUB reader output, native output generated by a local pandoc executable, and paired checked-in .native goldens using the EPUB normalized AST policy; this is executable golden-fixture evidence and does not assert that the upstream Haskell/Tasty process itself was run.';

    /**
     * @param array{limit?: int, maxExamples?: int, pandocBin?: string} $options
     * @return array<string, mixed>
     */
    public function run(string $epubDirectory, array $options = []): array
    {
        $limit = max(0, (int) ($options['limit'] ?? 0));
        $maxExamples = max(0, (int) ($options['maxExamples'] ?? self::DEFAULT_MAX_EXAMPLES));

        if (!is_dir($epubDirectory)) {
            return $this->skippedReport($epubDirectory, null, 'epub-directory-missing');
        }

        $pandoc = $this->resolvePandocBin(is_string($options['pandocBin'] ?? null) ? (string) $options['pandocBin'] : null);
        if ($pandoc === null) {
            return $this->skippedReport($epubDirectory, is_string($options['pandocBin'] ?? null) ? (string) $options['pandocBin'] : null, 'pandoc-executable-missing');
        }

        $epubFiles = $this->filesByBasename($epubDirectory, 'epub');
        $nativeFiles = $this->filesByBasename($epubDirectory, 'native');
        $fixtureNames = array_keys($epubFiles);
        sort($fixtureNames, SORT_STRING);
        $totalEpubCount = count($fixtureNames);
        if ($limit > 0) {
            $fixtureNames = array_slice($fixtureNames, 0, $limit);
        }

        $localParsedCount = 0;
        $pandocParsedCount = 0;
        $nativeFixtureParsedCount = 0;
        $bothParsedCount = 0;
        $matchCount = 0;
        $pandocNativeFixtureComparedCount = 0;
        $pandocNativeFixtureMatchCount = 0;
        $pandocNativeFixtureByteComparedCount = 0;
        $pandocNativeFixtureByteMatchCount = 0;
        $parseFailures = [];
        $mismatches = [];
        $nativeFixtureMismatches = [];
        $nativeFixtureByteMismatches = [];
        $categoryCounts = [];
        $normalizer = new EpubNativeAstPackageComparisonHarness();

        foreach ($fixtureNames as $fixtureName) {
            $localResult = $this->readLocalEpub($epubFiles[$fixtureName]);
            if ($localResult['ok']) {
                ++$localParsedCount;
            }

            $pandocResult = $this->readPandocNative($pandoc, $epubFiles[$fixtureName]);
            if ($pandocResult['ok']) {
                ++$pandocParsedCount;
            }

            $nativeFixtureResult = $this->readNativeFixture($nativeFiles[$fixtureName] ?? null);
            if ($nativeFixtureResult['ok']) {
                ++$nativeFixtureParsedCount;
            }

            if (!$localResult['ok'] || !$pandocResult['ok'] || !$nativeFixtureResult['ok']) {
                $parseFailures[] = [
                    'fixture' => $fixtureName,
                    'localError' => $localResult['error'],
                    'pandocError' => $pandocResult['error'],
                    'nativeFixtureError' => $nativeFixtureResult['error'],
                ];
                $this->addCategory($categoryCounts, 'parse-failure', $fixtureName, $maxExamples);
            }

            if ($localResult['ok'] && $pandocResult['ok']) {
                /** @var AstNode $localDocument */
                $localDocument = $localResult['document'];
                /** @var AstNode $pandocDocument */
                $pandocDocument = $pandocResult['document'];
                ++$bothParsedCount;

                $localAst = $normalizer->normalizedDocument($localDocument);
                $pandocAst = $normalizer->normalizedDocument($pandocDocument);
                if ($localAst === $pandocAst) {
                    ++$matchCount;
                } else {
                    $difference = $this->firstDifference($localAst, $pandocAst) ?? 'unknown-normalized-ast-difference';
                    $categories = $this->mismatchCategories($difference);
                    foreach ($categories as $category) {
                        $this->addCategory($categoryCounts, $category, $fixtureName, $maxExamples);
                    }

                    if (count($mismatches) < $maxExamples) {
                        $mismatches[] = [
                            'fixture' => $fixtureName,
                            'firstDifference' => $difference,
                            'categories' => $categories,
                            'localTopTypes' => $this->topTypeSequence($localDocument),
                            'pandocTopTypes' => $this->topTypeSequence($pandocDocument),
                        ];
                    }
                }
            }

            if ($nativeFixtureResult['ok'] && $pandocResult['ok']) {
                /** @var AstNode $nativeFixtureDocument */
                $nativeFixtureDocument = $nativeFixtureResult['document'];
                /** @var AstNode $pandocDocument */
                $pandocDocument = $pandocResult['document'];
                ++$pandocNativeFixtureComparedCount;

                $nativeFixtureAst = $normalizer->normalizedDocument($nativeFixtureDocument);
                $pandocAst = $normalizer->normalizedDocument($pandocDocument);
                if ($nativeFixtureAst === $pandocAst) {
                    ++$pandocNativeFixtureMatchCount;
                } else {
                    $difference = $this->firstDifference($nativeFixtureAst, $pandocAst) ?? 'unknown-checked-in-native-fixture-difference';
                    $categories = $this->mismatchCategories($difference);
                    $this->addCategory($categoryCounts, 'checked-in-native-fixture-drift', $fixtureName, $maxExamples);
                    foreach ($categories as $category) {
                        $this->addCategory($categoryCounts, $category, $fixtureName, $maxExamples);
                    }

                    if (count($nativeFixtureMismatches) < $maxExamples) {
                        $nativeFixtureMismatches[] = [
                            'fixture' => $fixtureName,
                            'firstDifference' => $difference,
                            'categories' => $categories,
                            'nativeFixtureTopTypes' => $this->topTypeSequence($nativeFixtureDocument),
                            'pandocTopTypes' => $this->topTypeSequence($pandocDocument),
                        ];
                    }
                }
            }

            if (is_string($nativeFixtureResult['native']) && is_string($pandocResult['native'])) {
                ++$pandocNativeFixtureByteComparedCount;

                if ($nativeFixtureResult['native'] === $pandocResult['native']) {
                    ++$pandocNativeFixtureByteMatchCount;
                } elseif (count($nativeFixtureByteMismatches) < $maxExamples) {
                    $nativeFixtureByteMismatches[] = [
                        'fixture' => $fixtureName,
                        'nativeFixtureSha256' => hash('sha256', $nativeFixtureResult['native']),
                        'pandocNativeSha256' => hash('sha256', $pandocResult['native']),
                        'nativeFixtureBytes' => strlen($nativeFixtureResult['native']),
                        'pandocNativeBytes' => strlen($pandocResult['native']),
                    ];
                }
            }
        }

        ksort($categoryCounts, SORT_STRING);
        $comparedEpubCount = count($fixtureNames);
        $mismatchCount = $bothParsedCount - $matchCount;
        $nativeFixtureMismatchCount = $pandocNativeFixtureComparedCount - $pandocNativeFixtureMatchCount;
        $nativeFixtureByteMismatchCount = $pandocNativeFixtureByteComparedCount - $pandocNativeFixtureByteMatchCount;

        return [
            'schemaVersion' => 1,
            'tool' => 'pandoc-epub-executable-native-ast',
            'status' => 'completed',
            'skipped' => false,
            'reason' => null,
            'verdict' => self::VERDICT,
            'claim' => self::CLAIM,
            'evidenceKind' => 'epub-pandoc-executable-normalized-ast-comparison',
            'epubDirectory' => $epubDirectory,
            'pandocExecutable' => $pandoc,
            'pandocVersion' => $this->pandocVersion($pandoc),
            'normalizationPolicy' => EpubNativeAstPackageComparisonHarness::class . '::normalizedDocument',
            'totalEpubCount' => $totalEpubCount,
            'comparedEpubCount' => $comparedEpubCount,
            'localParsedCount' => $localParsedCount,
            'pandocParsedCount' => $pandocParsedCount,
            'nativeFixtureParsedCount' => $nativeFixtureParsedCount,
            'bothParsedCount' => $bothParsedCount,
            'parseFailureCount' => count($parseFailures),
            'normalizedAstMatchCount' => $matchCount,
            'normalizedAstMismatchCount' => $mismatchCount,
            'normalizedAstMatchPercent' => self::percent($matchCount, $comparedEpubCount),
            'pandocNativeFixtureComparedCount' => $pandocNativeFixtureComparedCount,
            'pandocNativeFixtureMatchCount' => $pandocNativeFixtureMatchCount,
            'pandocNativeFixtureMismatchCount' => $nativeFixtureMismatchCount,
            'pandocNativeFixtureMatchPercent' => self::percent($pandocNativeFixtureMatchCount, $comparedEpubCount),
            'pandocNativeFixtureByteComparedCount' => $pandocNativeFixtureByteComparedCount,
            'pandocNativeFixtureByteMatchCount' => $pandocNativeFixtureByteMatchCount,
            'pandocNativeFixtureByteMismatchCount' => $nativeFixtureByteMismatchCount,
            'pandocNativeFixtureByteMatchPercent' => self::percent($pandocNativeFixtureByteMatchCount, $comparedEpubCount),
            'astParityStatus' => self::astParityStatus(count($parseFailures), $mismatchCount, $nativeFixtureMismatchCount, $comparedEpubCount),
            'parseFailures' => array_slice($parseFailures, 0, $maxExamples),
            'mismatchComparisons' => $mismatches,
            'pandocNativeFixtureMismatchComparisons' => $nativeFixtureMismatches,
            'pandocNativeFixtureByteMismatchComparisons' => $nativeFixtureByteMismatches,
            'mismatchCategories' => array_values($categoryCounts),
            'orderedRemainingGaps' => self::orderedRemainingGaps(
                true,
                true,
                $comparedEpubCount,
                count($parseFailures),
                $matchCount,
                $mismatchCount,
                $pandocNativeFixtureMatchCount,
                $nativeFixtureMismatchCount,
                $pandocNativeFixtureByteMatchCount,
                $nativeFixtureByteMismatchCount
            ),
        ];
    }

    /**
     * @param array<string, mixed> $report
     */
    public function formatReport(array $report): string
    {
        $lines = [
            'Pandoc EPUB executable/native AST comparison: ' . (string) ($report['status'] ?? 'unknown'),
            'Verdict: ' . (string) ($report['verdict'] ?? self::VERDICT),
            'Claim: ' . (string) ($report['claim'] ?? self::CLAIM),
            'epubDirectory=' . (string) ($report['epubDirectory'] ?? ''),
            'pandocExecutable=' . (string) ($report['pandocExecutable'] ?? ''),
        ];

        if (($report['skipped'] ?? false) === true) {
            $lines[] = 'reason=' . (string) ($report['reason'] ?? 'unknown');
            $lines = self::appendOrderedRemainingGaps($lines, $report);

            return implode(PHP_EOL, $lines) . PHP_EOL;
        }

        $lines[] = sprintf(
            'epub: total=%d compared=%d parsedBoth=%d parseFailures=%d nativeFixturesParsed=%d',
            (int) ($report['totalEpubCount'] ?? 0),
            (int) ($report['comparedEpubCount'] ?? 0),
            (int) ($report['bothParsedCount'] ?? 0),
            (int) ($report['parseFailureCount'] ?? 0),
            (int) ($report['nativeFixtureParsedCount'] ?? 0),
        );
        $lines[] = sprintf(
            'normalizedAst: matches=%d (%s) mismatches=%d status=%s',
            (int) ($report['normalizedAstMatchCount'] ?? 0),
            self::formatPercent($report['normalizedAstMatchPercent'] ?? null),
            (int) ($report['normalizedAstMismatchCount'] ?? 0),
            (string) ($report['astParityStatus'] ?? 'unknown'),
        );
        $lines[] = sprintf(
            'checkedInNativeFixture: pandocCompared=%d pandocMatches=%d (%s) pandocMismatches=%d',
            (int) ($report['pandocNativeFixtureComparedCount'] ?? 0),
            (int) ($report['pandocNativeFixtureMatchCount'] ?? 0),
            self::formatPercent($report['pandocNativeFixtureMatchPercent'] ?? null),
            (int) ($report['pandocNativeFixtureMismatchCount'] ?? 0),
        );
        $lines[] = sprintf(
            'checkedInNativeFixtureBytes: pandocCompared=%d pandocByteMatches=%d (%s) pandocByteMismatches=%d',
            (int) ($report['pandocNativeFixtureByteComparedCount'] ?? 0),
            (int) ($report['pandocNativeFixtureByteMatchCount'] ?? 0),
            self::formatPercent($report['pandocNativeFixtureByteMatchPercent'] ?? null),
            (int) ($report['pandocNativeFixtureByteMismatchCount'] ?? 0),
        );

        $mismatches = $report['mismatchComparisons'] ?? [];
        if (is_array($mismatches) && $mismatches !== []) {
            $lines[] = 'mismatchExamples:';
            foreach ($mismatches as $mismatch) {
                if (!is_array($mismatch)) {
                    continue;
                }
                $lines[] = '- ' . (string) ($mismatch['fixture'] ?? 'unknown')
                    . ': ' . (string) ($mismatch['firstDifference'] ?? 'unknown');
            }
        }
        $nativeFixtureMismatches = $report['pandocNativeFixtureMismatchComparisons'] ?? [];
        if (is_array($nativeFixtureMismatches) && $nativeFixtureMismatches !== []) {
            $lines[] = 'checkedInNativeFixtureMismatchExamples:';
            foreach ($nativeFixtureMismatches as $mismatch) {
                if (!is_array($mismatch)) {
                    continue;
                }
                $lines[] = '- ' . (string) ($mismatch['fixture'] ?? 'unknown')
                    . ': ' . (string) ($mismatch['firstDifference'] ?? 'unknown');
            }
        }
        $nativeFixtureByteMismatches = $report['pandocNativeFixtureByteMismatchComparisons'] ?? [];
        if (is_array($nativeFixtureByteMismatches) && $nativeFixtureByteMismatches !== []) {
            $lines[] = 'checkedInNativeFixtureByteMismatchExamples:';
            foreach ($nativeFixtureByteMismatches as $mismatch) {
                if (!is_array($mismatch)) {
                    continue;
                }
                $lines[] = sprintf(
                    '- %s: fixtureBytes=%d pandocBytes=%d fixtureSha256=%s pandocSha256=%s',
                    (string) ($mismatch['fixture'] ?? 'unknown'),
                    (int) ($mismatch['nativeFixtureBytes'] ?? 0),
                    (int) ($mismatch['pandocNativeBytes'] ?? 0),
                    (string) ($mismatch['nativeFixtureSha256'] ?? ''),
                    (string) ($mismatch['pandocNativeSha256'] ?? ''),
                );
            }
        }

        $lines = self::appendOrderedRemainingGaps($lines, $report);

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @param array<string, mixed> $report
     */
    public static function hasRequiredExecutableParity(array $report, int $requiredEpubCount): bool
    {
        if ($requiredEpubCount < 0) {
            throw new \InvalidArgumentException('Required EPUB count must not be negative');
        }

        return ($report['skipped'] ?? false) === false
            && ($report['status'] ?? null) === 'completed'
            && (int) ($report['totalEpubCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['comparedEpubCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['localParsedCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['pandocParsedCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['nativeFixtureParsedCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['bothParsedCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['parseFailureCount'] ?? -1) === 0
            && (int) ($report['normalizedAstMatchCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['normalizedAstMismatchCount'] ?? -1) === 0
            && (int) ($report['pandocNativeFixtureComparedCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['pandocNativeFixtureMatchCount'] ?? -1) === $requiredEpubCount
            && (int) ($report['pandocNativeFixtureMismatchCount'] ?? -1) === 0
            && ($report['astParityStatus'] ?? null) === 'normalized-ast-equality-observed-against-pandoc-executable';
    }

    /**
     * @param array<string, mixed> $report
     */
    public static function hasRequiredPandocVersion(array $report, string $requiredPandocVersion): bool
    {
        if ($requiredPandocVersion === '') {
            throw new \InvalidArgumentException('Required Pandoc version must not be empty');
        }

        return ($report['skipped'] ?? false) === false
            && ($report['status'] ?? null) === 'completed'
            && ($report['pandocVersion'] ?? null) === $requiredPandocVersion;
    }

    /**
     * @return array<string, mixed>
     */
    private function skippedReport(string $epubDirectory, ?string $pandocBin, string $reason): array
    {
        $directoryPresent = is_dir($epubDirectory);
        $executablePresent = $reason !== 'pandoc-executable-missing';
        $totalEpubCount = $directoryPresent ? count($this->filesByBasename($epubDirectory, 'epub')) : 0;

        return [
            'schemaVersion' => 1,
            'tool' => 'pandoc-epub-executable-native-ast',
            'status' => 'skipped',
            'skipped' => true,
            'reason' => $reason,
            'verdict' => self::VERDICT,
            'claim' => self::CLAIM,
            'evidenceKind' => 'epub-pandoc-executable-normalized-ast-comparison',
            'epubDirectory' => $epubDirectory,
            'pandocExecutable' => $pandocBin,
            'pandocVersion' => null,
            'normalizationPolicy' => EpubNativeAstPackageComparisonHarness::class . '::normalizedDocument',
            'totalEpubCount' => $totalEpubCount,
            'comparedEpubCount' => 0,
            'localParsedCount' => 0,
            'pandocParsedCount' => 0,
            'nativeFixtureParsedCount' => 0,
            'bothParsedCount' => 0,
            'parseFailureCount' => 0,
            'normalizedAstMatchCount' => 0,
            'normalizedAstMismatchCount' => 0,
            'normalizedAstMatchPercent' => null,
            'pandocNativeFixtureComparedCount' => 0,
            'pandocNativeFixtureMatchCount' => 0,
            'pandocNativeFixtureMismatchCount' => 0,
            'pandocNativeFixtureMatchPercent' => null,
            'pandocNativeFixtureByteComparedCount' => 0,
            'pandocNativeFixtureByteMatchCount' => 0,
            'pandocNativeFixtureByteMismatchCount' => 0,
            'pandocNativeFixtureByteMatchPercent' => null,
            'astParityStatus' => $reason === 'pandoc-executable-missing'
                ? 'not-evaluated-pandoc-executable-missing'
                : 'not-evaluated-epub-directory-missing',
            'parseFailures' => [],
            'mismatchComparisons' => [],
            'pandocNativeFixtureMismatchComparisons' => [],
            'pandocNativeFixtureByteMismatchComparisons' => [],
            'mismatchCategories' => [],
            'orderedRemainingGaps' => self::orderedRemainingGaps($directoryPresent, $executablePresent, 0, 0, 0, 0),
        ];
    }

    private function resolvePandocBin(?string $requested): ?string
    {
        $candidate = $requested;
        if ($candidate === null || $candidate === '') {
            $env = getenv('PANDOC_BIN');
            $candidate = is_string($env) && $env !== '' ? $env : 'pandoc';
        }

        if (str_contains($candidate, DIRECTORY_SEPARATOR)) {
            return is_file($candidate) && is_executable($candidate) ? $candidate : null;
        }

        $output = [];
        $exitCode = 0;
        exec('command -v ' . escapeshellarg($candidate) . ' 2>/dev/null', $output, $exitCode);
        if ($exitCode !== 0 || !is_string($output[0] ?? null) || trim($output[0]) === '') {
            return null;
        }

        return trim($output[0]);
    }

    /**
     * @return array<string, string>
     */
    private function filesByBasename(string $directory, string $extension): array
    {
        $files = [];
        foreach (glob(rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . '*.' . $extension) ?: [] as $path) {
            $files[basename($path, '.' . $extension)] = $path;
        }
        ksort($files, SORT_STRING);

        return $files;
    }

    /**
     * @return array{ok: bool, document: ?AstNode, error: ?string}
     */
    private function readLocalEpub(string $path): array
    {
        try {
            return ['ok' => true, 'document' => (new EpubReader())->readEpubFile($path), 'error' => null];
        } catch (\Throwable $exception) {
            return ['ok' => false, 'document' => null, 'error' => $exception::class . ': ' . $exception->getMessage()];
        }
    }

    /**
     * @return array{ok: bool, document: ?AstNode, native: ?string, error: ?string}
     */
    private function readNativeFixture(?string $path): array
    {
        if ($path === null) {
            return ['ok' => false, 'document' => null, 'native' => null, 'error' => 'missing paired .native fixture'];
        }

        try {
            $native = file_get_contents($path);
            if (!is_string($native)) {
                throw new \RuntimeException("Unable to read native fixture '{$path}'.");
            }

            return ['ok' => true, 'document' => (new NativeReader())->read($native), 'native' => $native, 'error' => null];
        } catch (\Throwable $exception) {
            return [
                'ok' => false,
                'document' => null,
                'native' => isset($native) && is_string($native) ? $native : null,
                'error' => $exception::class . ': ' . $exception->getMessage(),
            ];
        }
    }

    /**
     * @return array{ok: bool, document: ?AstNode, native: ?string, error: ?string}
     */
    private function readPandocNative(string $pandoc, string $epubPath): array
    {
        $result = $this->runProcess(
            escapeshellarg($pandoc)
            . ' -f epub -t native '
            . escapeshellarg($epubPath)
        );
        if ($result['exitCode'] !== 0) {
            return [
                'ok' => false,
                'document' => null,
                'native' => $result['stdout'] !== '' ? $result['stdout'] : null,
                'error' => 'pandoc exited ' . $result['exitCode'] . ': ' . trim($result['stderr']),
            ];
        }

        try {
            return ['ok' => true, 'document' => (new NativeReader())->read($result['stdout']), 'native' => $result['stdout'], 'error' => null];
        } catch (\Throwable $exception) {
            return ['ok' => false, 'document' => null, 'native' => $result['stdout'], 'error' => $exception::class . ': ' . $exception->getMessage()];
        }
    }

    private function pandocVersion(string $pandoc): ?string
    {
        $result = $this->runProcess(escapeshellarg($pandoc) . ' --version');
        if ($result['exitCode'] !== 0) {
            return null;
        }

        $lines = preg_split('/\R/', trim($result['stdout']));

        return is_array($lines) && is_string($lines[0] ?? null) && $lines[0] !== '' ? $lines[0] : null;
    }

    /**
     * @return array{exitCode: int, stdout: string, stderr: string}
     */
    private function runProcess(string $command): array
    {
        $process = proc_open($command, [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ], $pipes);
        if (!is_resource($process)) {
            return ['exitCode' => 127, 'stdout' => '', 'stderr' => 'Unable to start process'];
        }

        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        fclose($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[2]);
        $exitCode = proc_close($process);

        return [
            'exitCode' => is_int($exitCode) ? $exitCode : 1,
            'stdout' => is_string($stdout) ? $stdout : '',
            'stderr' => is_string($stderr) ? $stderr : '',
        ];
    }

    private function firstDifference(mixed $local, mixed $pandoc, string $path = 'root'): ?string
    {
        if (gettype($local) !== gettype($pandoc)) {
            return "{$path} type " . gettype($local) . ' vs ' . gettype($pandoc);
        }
        if (!is_array($local)) {
            return $local === $pandoc ? null : "{$path} value " . self::shortJson($local) . ' vs ' . self::shortJson($pandoc);
        }

        $localKeys = array_keys($local);
        $pandocKeys = array_keys($pandoc);
        if ($localKeys !== $pandocKeys) {
            return "{$path} keys " . self::shortJson($localKeys) . ' vs ' . self::shortJson($pandocKeys);
        }

        foreach ($localKeys as $key) {
            $difference = $this->firstDifference($local[$key], $pandoc[$key], $path . '.' . $key);
            if ($difference !== null) {
                return $difference;
            }
        }

        return null;
    }

    /**
     * @return list<string>
     */
    private function mismatchCategories(string $difference): array
    {
        $lower = strtolower($difference);
        $categories = [];
        if (str_contains($lower, '.children keys')) {
            $categories[] = 'child-count-or-inline-granularity';
        }
        if (str_contains($lower, '.attrs keys') || str_contains($lower, '.attrs.')) {
            $categories[] = 'attribute-shape';
        }
        if (str_contains($lower, 'table') || str_contains($lower, 'row') || str_contains($lower, 'cell')) {
            $categories[] = 'table-shape';
        }
        if (str_contains($lower, 'image') || str_contains($lower, 'url') || str_contains($lower, 'alt')) {
            $categories[] = 'image-shape';
        }
        if (str_contains($lower, 'link') || str_contains($lower, 'href')) {
            $categories[] = 'link-shape';
        }
        if (str_contains($lower, 'math')) {
            $categories[] = 'math-shape';
        }
        if (str_contains($lower, '.type')) {
            $categories[] = 'node-type';
        }
        if (str_contains($lower, ' value ')) {
            $categories[] = 'scalar-value';
        }
        if ($categories === []) {
            $categories[] = 'uncategorized-normalized-ast-drift';
        }

        return array_values(array_unique($categories));
    }

    /**
     * @return list<string>
     */
    private function topTypeSequence(AstNode $document): array
    {
        return array_map(static fn (AstNode $child): string => $child->type, $document->children);
    }

    /**
     * @param array<string, array{category: string, count: int, examples: list<string>}> $categoryCounts
     */
    private function addCategory(array &$categoryCounts, string $category, string $fixture, int $maxExamples): void
    {
        if (!isset($categoryCounts[$category])) {
            $categoryCounts[$category] = ['category' => $category, 'count' => 0, 'examples' => []];
        }

        ++$categoryCounts[$category]['count'];
        if (count($categoryCounts[$category]['examples']) < $maxExamples) {
            $categoryCounts[$category]['examples'][] = $fixture;
        }
    }

    private static function astParityStatus(
        int $parseFailureCount,
        int $mismatchCount,
        int $nativeFixtureMismatchCount,
        int $comparedEpubCount
    ): string {
        if ($comparedEpubCount === 0) {
            return 'not-evaluated-no-epub-files';
        }
        if ($parseFailureCount > 0) {
            return 'blocked-by-parse-failures';
        }
        if ($mismatchCount > 0 || $nativeFixtureMismatchCount > 0) {
            return 'normalized-ast-mismatches-observed';
        }

        return 'normalized-ast-equality-observed-against-pandoc-executable';
    }

    /**
     * @return list<array<string, mixed>>
     */
    private static function orderedRemainingGaps(
        bool $directoryPresent,
        bool $executablePresent,
        int $comparedEpubCount,
        int $parseFailureCount,
        int $matchCount,
        int $mismatchCount,
        int $nativeFixtureMatchCount = 0,
        int $nativeFixtureMismatchCount = 0,
        int $nativeFixtureByteMatchCount = 0,
        int $nativeFixtureByteMismatchCount = 0
    ): array {
        if (!$directoryPresent) {
            $sourceEvidence = 'EPUB directory absent; executable comparison did not run';
        } elseif (!$executablePresent) {
            $sourceEvidence = 'pandoc executable absent; executable comparison did not run';
        } else {
            $sourceEvidence = "compared epubs={$comparedEpubCount}; parse failures={$parseFailureCount}; local/executable normalized AST matches={$matchCount}; local/executable normalized AST mismatches={$mismatchCount}; executable/checked-in-native matches={$nativeFixtureMatchCount}; executable/checked-in-native mismatches={$nativeFixtureMismatchCount}; executable/checked-in-native byte matches={$nativeFixtureByteMatchCount}; executable/checked-in-native byte mismatches={$nativeFixtureByteMismatchCount}";
        }

        $executableEvidenceCovered = $parseFailureCount === 0
            && $mismatchCount === 0
            && $nativeFixtureMismatchCount === 0
            && $comparedEpubCount > 0
            && $matchCount === $comparedEpubCount
            && $nativeFixtureMatchCount === $comparedEpubCount;

        return [
            [
                'rank' => 1,
                'id' => 'pandoc-executable-epub-native-ast-equality',
                'status' => (!$directoryPresent || !$executablePresent)
                    ? 'not-evaluated'
                    : ($executableEvidenceCovered ? 'covered-by-current-executable-evidence' : 'open'),
                'currentEvidence' => $sourceEvidence,
                'evidenceRequired' => 'Run local PHP EPUB reader, a pandoc executable, and paired checked-in .native fixtures against the same EPUB files, keeping parse failures and normalized AST mismatches at zero.',
            ],
            [
                'rank' => 2,
                'id' => 'upstream-haskell-epub-reader-runner-results',
                'status' => 'open',
                'currentEvidence' => 'This harness invokes a pandoc executable and checks the same checked-in native fixtures, but it does not run the upstream Haskell/Tasty process itself.',
                'evidenceRequired' => 'Record reproducible upstream Tests.Readers.EPUB runner results when a Haskell runner is available.',
            ],
        ];
    }

    /**
     * @param list<string> $lines
     * @param array<string, mixed> $report
     * @return list<string>
     */
    private static function appendOrderedRemainingGaps(array $lines, array $report): array
    {
        $gaps = $report['orderedRemainingGaps'] ?? [];
        if (!is_array($gaps) || $gaps === []) {
            return $lines;
        }

        $lines[] = 'orderedRemainingGaps:';
        foreach ($gaps as $gap) {
            if (!is_array($gap)) {
                continue;
            }
            $lines[] = sprintf(
                '%d. %s [%s] current=%s required=%s',
                (int) ($gap['rank'] ?? 0),
                (string) ($gap['id'] ?? 'unknown-gap'),
                (string) ($gap['status'] ?? 'unknown'),
                (string) ($gap['currentEvidence'] ?? ''),
                (string) ($gap['evidenceRequired'] ?? '')
            );
        }

        return $lines;
    }

    private static function percent(int $numerator, int $denominator): ?float
    {
        if ($denominator === 0) {
            return null;
        }

        return round(($numerator / $denominator) * 100, 2);
    }

    private static function formatPercent(mixed $value): string
    {
        if (!is_int($value) && !is_float($value)) {
            return 'n/a';
        }

        return number_format((float) $value, 2) . '%';
    }

    private static function shortJson(mixed $value): string
    {
        try {
            $json = json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
        } catch (\JsonException) {
            return gettype($value);
        }

        return strlen($json) > 180 ? substr($json, 0, 177) . '...' : $json;
    }
}
