<?php

declare(strict_types=1);

namespace PortLibs\Pandoc;

final class MarkdownEmojiAliases
{
    private const ALIASES = [
        '+1' => "\u{1F44D}",
        '-1' => "\u{1F44E}",
        '100' => "\u{1F4AF}",
        '1234' => "\u{1F522}",
        '8ball' => "\u{1F3B1}",
        'a' => "\u{1F170}\u{FE0F}",
        'ab' => "\u{1F18E}",
        'abc' => "\u{1F524}",
        'abcd' => "\u{1F521}",
        'accept' => "\u{1F251}",
        'airplane' => "\u{2708}\u{FE0F}",
        'alarm_clock' => "\u{23F0}",
        'alien' => "\u{1F47D}",
        'ambulance' => "\u{1F691}",
        'anchor' => "\u{2693}",
        'anger' => "\u{1F4A2}",
        'angry' => "\u{1F620}",
        'anguished' => "\u{1F627}",
        'apple' => "\u{1F34E}",
        'art' => "\u{1F3A8}",
        'astonished' => "\u{1F632}",
        'baby' => "\u{1F476}",
        'balloon' => "\u{1F388}",
        'banana' => "\u{1F34C}",
        'bangbang' => "\u{203C}\u{FE0F}",
        'bar_chart' => "\u{1F4CA}",
        'basketball' => "\u{1F3C0}",
        'bell' => "\u{1F514}",
        'bike' => "\u{1F6B2}",
        'bird' => "\u{1F426}",
        'birthday' => "\u{1F382}",
        'blue_heart' => "\u{1F499}",
        'blush' => "\u{1F60A}",
        'book' => "\u{1F4D6}",
        'bookmark' => "\u{1F516}",
        'books' => "\u{1F4DA}",
        'boom' => "\u{1F4A5}",
        'bow' => "\u{1F647}",
        'briefcase' => "\u{1F4BC}",
        'bug' => "\u{1F41B}",
        'bulb' => "\u{1F4A1}",
        'calendar' => "\u{1F4C6}",
        'camera' => "\u{1F4F7}",
        'car' => "\u{1F697}",
        'cat' => "\u{1F431}",
        'chart_with_downwards_trend' => "\u{1F4C9}",
        'chart_with_upwards_trend' => "\u{1F4C8}",
        'checkered_flag' => "\u{1F3C1}",
        'cherry_blossom' => "\u{1F338}",
        'clap' => "\u{1F44F}",
        'clipboard' => "\u{1F4CB}",
        'clock1' => "\u{1F550}",
        'closed_book' => "\u{1F4D5}",
        'cloud' => "\u{2601}\u{FE0F}",
        'coffee' => "\u{2615}",
        'cold_sweat' => "\u{1F630}",
        'computer' => "\u{1F4BB}",
        'confounded' => "\u{1F616}",
        'confused' => "\u{1F615}",
        'construction' => "\u{1F6A7}",
        'construction_worker' => "\u{1F477}",
        'cool' => "\u{1F192}",
        'cowboy_hat_face' => "\u{1F920}",
        'cry' => "\u{1F622}",
        'cursing_face' => "\u{1F92C}",
        'dart' => "\u{1F3AF}",
        'date' => "\u{1F4C5}",
        'disappointed' => "\u{1F61E}",
        'disappointed_relieved' => "\u{1F625}",
        'dizzy_face' => "\u{1F635}",
        'eyes' => "\u{1F440}",
        'face_with_head_bandage' => "\u{1F915}",
        'face_with_thermometer' => "\u{1F912}",
        'fearful' => "\u{1F628}",
        'fire' => "\u{1F525}",
        'flushed' => "\u{1F633}",
        'frowning' => "\u{1F626}",
        'frowning_face' => "\u{2639}\u{FE0F}",
        'gear' => "\u{2699}\u{FE0F}",
        'grin' => "\u{1F601}",
        'grinning' => "\u{1F600}",
        'hammer' => "\u{1F528}",
        'heart' => "\u{2764}\u{FE0F}",
        'heart_eyes' => "\u{1F60D}",
        'heavy_check_mark' => "\u{2714}\u{FE0F}",
        'hugs' => "\u{1F917}",
        'hushed' => "\u{1F62F}",
        'information_source' => "\u{2139}\u{FE0F}",
        'innocent' => "\u{1F607}",
        'joy' => "\u{1F602}",
        'key' => "\u{1F511}",
        'keyboard' => "\u{2328}\u{FE0F}",
        'kissing' => "\u{1F617}",
        'kissing_closed_eyes' => "\u{1F61A}",
        'kissing_heart' => "\u{1F618}",
        'kissing_smiling_eyes' => "\u{1F619}",
        'laughing' => "\u{1F606}",
        'link' => "\u{1F517}",
        'lock' => "\u{1F512}",
        'mag' => "\u{1F50D}",
        'mag_right' => "\u{1F50E}",
        'mask' => "\u{1F637}",
        'memo' => "\u{1F4DD}",
        'money_mouth_face' => "\u{1F911}",
        'muscle' => "\u{1F4AA}",
        'nauseated_face' => "\u{1F922}",
        'nerd_face' => "\u{1F913}",
        'ok_hand' => "\u{1F44C}",
        'open_mouth' => "\u{1F62E}",
        'package' => "\u{1F4E6}",
        'page_facing_up' => "\u{1F4C4}",
        'paperclip' => "\u{1F4CE}",
        'partying_face' => "\u{1F973}",
        'pensive' => "\u{1F614}",
        'persevere' => "\u{1F623}",
        'pleading_face' => "\u{1F97A}",
        'point_down' => "\u{1F447}",
        'point_left' => "\u{1F448}",
        'point_right' => "\u{1F449}",
        'point_up' => "\u{261D}\u{FE0F}",
        'pray' => "\u{1F64F}",
        'printer' => "\u{1F5A8}\u{FE0F}",
        'pushpin' => "\u{1F4CC}",
        'rage' => "\u{1F621}",
        'raised_hands' => "\u{1F64C}",
        'relaxed' => "\u{263A}\u{FE0F}",
        'relieved' => "\u{1F60C}",
        'rocket' => "\u{1F680}",
        'rofl' => "\u{1F923}",
        'scream' => "\u{1F631}",
        'sleeping' => "\u{1F634}",
        'sleepy' => "\u{1F62A}",
        'slightly_frowning_face' => "\u{1F641}",
        'slightly_smiling_face' => "\u{1F642}",
        'smile' => "\u{1F604}",
        'smirk' => "\u{1F60F}",
        'sneezing_face' => "\u{1F927}",
        'sob' => "\u{1F62D}",
        'sparkles' => "\u{2728}",
        'star_struck' => "\u{1F929}",
        'stuck_out_tongue' => "\u{1F61B}",
        'stuck_out_tongue_closed_eyes' => "\u{1F61D}",
        'stuck_out_tongue_winking_eye' => "\u{1F61C}",
        'sunglasses' => "\u{1F60E}",
        'sweat_smile' => "\u{1F605}",
        'tada' => "\u{1F389}",
        'thinking' => "\u{1F914}",
        'thumbsdown' => "\u{1F44E}",
        'thumbsup' => "\u{1F44D}",
        'tired_face' => "\u{1F62B}",
        'triumph' => "\u{1F624}",
        'unamused' => "\u{1F612}",
        'unlock' => "\u{1F513}",
        'warning' => "\u{26A0}\u{FE0F}",
        'wave' => "\u{1F44B}",
        'weary' => "\u{1F629}",
        'white_check_mark' => "\u{2705}",
        'wink' => "\u{1F609}",
        'worried' => "\u{1F61F}",
        'wrench' => "\u{1F527}",
        'writing_hand' => "\u{270D}\u{FE0F}",
        'x' => "\u{274C}",
        'yum' => "\u{1F60B}",
        'zap' => "\u{26A1}",
    ];

    public static function glyphForAlias(string $alias): ?string
    {
        return self::ALIASES[$alias] ?? null;
    }

    public static function aliasMatchesGlyph(string $alias, string $glyph): bool
    {
        return (self::ALIASES[$alias] ?? null) === $glyph;
    }

    public static function replaceGlyphsWithAliases(string $text): string
    {
        $replacements = [];
        foreach (self::ALIASES as $alias => $glyph) {
            $replacements[$glyph] ??= $alias;
        }

        return $replacements === [] ? $text : strtr($text, $replacements);
    }
}
