<?php

declare(strict_types=1);

namespace PortLibs\Pandoc;

final class MarkdownEmojiAliases
{
    private const ALIASES = [
        '+1' => "\u{1F44D}",
        '100' => "\u{1F4AF}",
        '1234' => "\u{1F522}",
        '-1' => "\u{1F44E}",
        '8ball' => "\u{1F3B1}",
        'airplane' => "\u{2708}\u{FE0F}",
        'alarm_clock' => "\u{23F0}",
        'anchor' => "\u{2693}",
        'art' => "\u{1F3A8}",
        'atm' => "\u{1F3E7}",
        'ballot_box_with_check' => "\u{2611}\u{FE0F}",
        'bank' => "\u{1F3E6}",
        'bar_chart' => "\u{1F4CA}",
        'battery' => "\u{1F50B}",
        'bell' => "\u{1F514}",
        'blue_book' => "\u{1F4D8}",
        'blue_heart' => "\u{1F499}",
        'boom' => "\u{1F4A5}",
        'briefcase' => "\u{1F4BC}",
        'bug' => "\u{1F41B}",
        'bulb' => "\u{1F4A1}",
        'calendar' => "\u{1F4C6}",
        'calling' => "\u{1F4F2}",
        'camera' => "\u{1F4F7}",
        'chart_with_upwards_trend' => "\u{1F4C8}",
        'clap' => "\u{1F44F}",
        'clipboard' => "\u{1F4CB}",
        'clock1' => "\u{1F550}",
        'coffee' => "\u{2615}",
        'computer' => "\u{1F4BB}",
        'construction' => "\u{1F6A7}",
        'email' => "\u{1F4E7}",
        'envelope' => "\u{2709}\u{FE0F}",
        'exclamation' => "\u{2757}",
        'eyes' => "\u{1F440}",
        'file_folder' => "\u{1F4C1}",
        'fire' => "\u{1F525}",
        'gear' => "\u{2699}\u{FE0F}",
        'green_book' => "\u{1F4D7}",
        'green_heart' => "\u{1F49A}",
        'grey_question' => "\u{2754}",
        'hammer' => "\u{1F528}",
        'heart' => "\u{2764}\u{FE0F}",
        'heavy_check_mark' => "\u{2714}\u{FE0F}",
        'hourglass' => "\u{231B}",
        'hourglass_flowing_sand' => "\u{23F3}",
        'information_source' => "\u{2139}\u{FE0F}",
        'joy' => "\u{1F602}",
        'key' => "\u{1F511}",
        'keyboard' => "\u{2328}\u{FE0F}",
        'label' => "\u{1F3F7}\u{FE0F}",
        'large_blue_circle' => "\u{1F535}",
        'link' => "\u{1F517}",
        'lock' => "\u{1F512}",
        'mag' => "\u{1F50D}",
        'memo' => "\u{1F4DD}",
        'microphone' => "\u{1F3A4}",
        'mobile_phone_off' => "\u{1F4F4}",
        'new' => "\u{1F195}",
        'no_entry' => "\u{26D4}",
        'notebook' => "\u{1F4D3}",
        'office' => "\u{1F3E2}",
        'ok_hand' => "\u{1F44C}",
        'open_file_folder' => "\u{1F4C2}",
        'orange_book' => "\u{1F4D9}",
        'paperclip' => "\u{1F4CE}",
        'pencil2' => "\u{270F}\u{FE0F}",
        'phone' => "\u{260E}\u{FE0F}",
        'pushpin' => "\u{1F4CC}",
        'question' => "\u{2753}",
        'recycle' => "\u{267B}\u{FE0F}",
        'red_circle' => "\u{1F534}",
        'rocket' => "\u{1F680}",
        'round_pushpin' => "\u{1F4CD}",
        'satellite' => "\u{1F4E1}",
        'scissors' => "\u{2702}\u{FE0F}",
        'scroll' => "\u{1F4DC}",
        'shield' => "\u{1F6E1}\u{FE0F}",
        'smile' => "\u{1F604}",
        'small_blue_diamond' => "\u{1F539}",
        'small_orange_diamond' => "\u{1F538}",
        'sparkles' => "\u{2728}",
        'sparkling_heart' => "\u{1F496}",
        'speech_balloon' => "\u{1F4AC}",
        'star' => "\u{2B50}",
        'star2' => "\u{1F31F}",
        'stop_sign' => "\u{1F6D1}",
        'tada' => "\u{1F389}",
        'telephone_receiver' => "\u{1F4DE}",
        'thinking' => "\u{1F914}",
        'thumbsdown' => "\u{1F44E}",
        'thumbsup' => "\u{1F44D}",
        'triangular_flag_on_post' => "\u{1F6A9}",
        'unlock' => "\u{1F513}",
        'warning' => "\u{26A0}\u{FE0F}",
        'white_circle' => "\u{26AA}",
        'white_check_mark' => "\u{2705}",
        'white_large_square' => "\u{2B1C}",
        'wrench' => "\u{1F527}",
        'writing_hand' => "\u{270D}\u{FE0F}",
        'x' => "\u{274C}",
        'zap' => "\u{26A1}",
    ];

    public static function glyphForAlias(string $alias): ?string
    {
        return self::ALIASES[$alias] ?? null;
    }

    public static function aliasMatchesGlyph(string $alias, string $glyph): bool
    {
        return (self::ALIASES[$alias] ?? null) === $glyph;
    }
}
