<?php

declare(strict_types=1);

use PortLibs\LibSqlite\SQLiteSchemaRecord;
use PortLibs\LibSqlite\SQLiteViewTriggerDdlCorpus;

$records = [
    new SQLiteSchemaRecord('table', 'app_settings', 'app_settings', 2, 'CREATE TABLE app_settings(setting_id integer primary key, key_name text, key_value text, load_policy text)', 1),
    new SQLiteSchemaRecord('table', 'app_setting_audit', 'app_setting_audit', 3, 'CREATE TABLE app_setting_audit(setting_id integer, action text)', 2),
    new SQLiteSchemaRecord('view', 'loadable_settings', 'loadable_settings', 0, "CREATE VIEW loadable_settings(setting_id, key_name) AS SELECT setting_id, key_name FROM app_settings WHERE load_policy = 'yes'", 3),
    new SQLiteSchemaRecord('view', 'temp_setting_names', 'temp_setting_names', null, 'CREATE TEMP VIEW temp_setting_names(name) AS SELECT key_name FROM main.app_settings', 4),
    new SQLiteSchemaRecord('view', 'joined_setting_audit', 'joined_setting_audit', 0, 'CREATE VIEW joined_setting_audit AS SELECT o.key_name, a.action FROM app_settings o JOIN app_setting_audit a ON a.setting_id = o.setting_id', 5),
    new SQLiteSchemaRecord('trigger', 'setting_audit_insert', 'app_settings', 0, "CREATE TRIGGER setting_audit_insert AFTER INSERT ON app_settings BEGIN INSERT INTO app_setting_audit(setting_id, action) VALUES (new.setting_id, 'insert'); END", 6),
    new SQLiteSchemaRecord('trigger', 'setting_key_guard', 'app_settings', 0, "CREATE TRIGGER setting_key_guard BEFORE UPDATE ON app_settings BEGIN SELECT CASE WHEN new.key_name IS NULL THEN RAISE(ABORT, 'missing key_name') END; INSERT INTO app_setting_audit(setting_id, action) VALUES (old.setting_id, 'rename'); END", 7),
    new SQLiteSchemaRecord('trigger', 'setting_view_insert', 'loadable_settings', 0, "CREATE TRIGGER setting_view_insert INSTEAD OF INSERT ON loadable_settings BEGIN INSERT INTO app_settings(setting_id, key_name, load_policy) VALUES (new.setting_id, new.key_name, 'yes'); END", 8),
    new SQLiteSchemaRecord('trigger', 'temp_setting_delete', 'app_settings', null, "CREATE TEMP TRIGGER temp_setting_delete AFTER DELETE ON app_settings BEGIN INSERT INTO app_setting_audit(setting_id, action) VALUES (old.setting_id, 'delete'); END", 9),
    new SQLiteSchemaRecord('trigger', 'dangling_setting_cleanup', 'missing_settings', 0, 'CREATE TRIGGER dangling_setting_cleanup AFTER DELETE ON missing_settings BEGIN SELECT old.setting_id; END', 10),
];

$views = static fn (): array => SQLiteViewTriggerDdlCorpus::views($records);
$triggers = static fn (): array => SQLiteViewTriggerDdlCorpus::triggers($records);
$summary = static fn (): array => SQLiteViewTriggerDdlCorpus::summary($records);

return [
    'view trigger ddl corpus counts views' => static fn (TestRunner $t) => $t->same(3, count($views())),
    'view trigger ddl corpus first view name' => static fn (TestRunner $t) => $t->same('loadable_settings', $views()[0]['name']),
    'view trigger ddl corpus preserves view table name' => static fn (TestRunner $t) => $t->same('loadable_settings', $views()[0]['table']),
    'view trigger ddl corpus detects explicit view columns' => static fn (TestRunner $t) => $t->same(['setting_id', 'key_name'], $views()[0]['columns']),
    'view trigger ddl corpus detects temp view column' => static fn (TestRunner $t) => $t->same(['name'], $views()[1]['columns']),
    'view trigger ddl corpus leaves implicit view columns empty' => static fn (TestRunner $t) => $t->same([], $views()[2]['columns']),
    'view trigger ddl corpus detects view dependency' => static fn (TestRunner $t) => $t->same(['app_settings'], $views()[0]['dependencies']),
    'view trigger ddl corpus strips schema-qualified dependency' => static fn (TestRunner $t) => $t->same(['app_settings'], $views()[1]['dependencies']),
    'view trigger ddl corpus detects joined dependencies' => static fn (TestRunner $t) => $t->same(['app_settings', 'app_setting_audit'], $views()[2]['dependencies']),
    'view trigger ddl corpus detects temp view' => static fn (TestRunner $t) => $t->same(true, $views()[1]['temporary']),
    'view trigger ddl corpus main view is not temp' => static fn (TestRunner $t) => $t->same(false, $views()[0]['temporary']),
    'view trigger ddl corpus normalizes view sql whitespace' => static fn (TestRunner $t) => $t->same("CREATE VIEW loadable_settings(setting_id, key_name) AS SELECT setting_id, key_name FROM app_settings WHERE load_policy = 'yes'", $views()[0]['sql']),
    'view trigger ddl corpus counts triggers' => static fn (TestRunner $t) => $t->same(5, count($triggers())),
    'view trigger ddl corpus first trigger name' => static fn (TestRunner $t) => $t->same('setting_audit_insert', $triggers()[0]['name']),
    'view trigger ddl corpus after trigger timing' => static fn (TestRunner $t) => $t->same('after', $triggers()[0]['timing']),
    'view trigger ddl corpus insert trigger event' => static fn (TestRunner $t) => $t->same('insert', $triggers()[0]['event']),
    'view trigger ddl corpus before trigger timing' => static fn (TestRunner $t) => $t->same('before', $triggers()[1]['timing']),
    'view trigger ddl corpus update trigger event' => static fn (TestRunner $t) => $t->same('update', $triggers()[1]['event']),
    'view trigger ddl corpus instead of trigger timing' => static fn (TestRunner $t) => $t->same('instead of', $triggers()[2]['timing']),
    'view trigger ddl corpus instead of flag' => static fn (TestRunner $t) => $t->same(true, $triggers()[2]['insteadOf']),
    'view trigger ddl corpus ordinary trigger not instead of' => static fn (TestRunner $t) => $t->same(false, $triggers()[0]['insteadOf']),
    'view trigger ddl corpus delete trigger event' => static fn (TestRunner $t) => $t->same('delete', $triggers()[3]['event']),
    'view trigger ddl corpus detects temp trigger' => static fn (TestRunner $t) => $t->same(true, $triggers()[3]['temporary']),
    'view trigger ddl corpus main trigger is not temp' => static fn (TestRunner $t) => $t->same(false, $triggers()[0]['temporary']),
    'view trigger ddl corpus trigger target table' => static fn (TestRunner $t) => $t->same('app_settings', $triggers()[0]['table']),
    'view trigger ddl corpus view trigger target' => static fn (TestRunner $t) => $t->same('loadable_settings', $triggers()[2]['table']),
    'view trigger ddl corpus trigger body one statement' => static fn (TestRunner $t) => $t->same(1, $triggers()[0]['bodyStatements']),
    'view trigger ddl corpus trigger body two statements' => static fn (TestRunner $t) => $t->same(2, $triggers()[1]['bodyStatements']),
    'view trigger ddl corpus trigger new references' => static fn (TestRunner $t) => $t->same(['setting_id'], $triggers()[0]['referencedNew']),
    'view trigger ddl corpus update trigger new references' => static fn (TestRunner $t) => $t->same(['key_name'], $triggers()[1]['referencedNew']),
    'view trigger ddl corpus update trigger old references' => static fn (TestRunner $t) => $t->same(['setting_id'], $triggers()[1]['referencedOld']),
    'view trigger ddl corpus instead trigger new references' => static fn (TestRunner $t) => $t->same(['setting_id', 'key_name'], $triggers()[2]['referencedNew']),
    'view trigger ddl corpus delete trigger old references' => static fn (TestRunner $t) => $t->same(['setting_id'], $triggers()[3]['referencedOld']),
    'view trigger ddl corpus trigger insert dependency' => static fn (TestRunner $t) => $t->same(['app_setting_audit'], $triggers()[0]['dependencies']),
    'view trigger ddl corpus trigger mixed dependencies' => static fn (TestRunner $t) => $t->same(['app_setting_audit'], $triggers()[1]['dependencies']),
    'view trigger ddl corpus trigger target insert dependency' => static fn (TestRunner $t) => $t->same(['app_settings'], $triggers()[2]['dependencies']),
    'view trigger ddl corpus dangling trigger dependency empty' => static fn (TestRunner $t) => $t->same([], $triggers()[4]['dependencies']),
    'view trigger ddl corpus dangling trigger detected' => static fn (TestRunner $t) => $t->same(['dangling_setting_cleanup'], SQLiteViewTriggerDdlCorpus::danglingTriggers($records)),
    'view trigger ddl corpus summary view count' => static fn (TestRunner $t) => $t->same(3, $summary()['views']),
    'view trigger ddl corpus summary trigger count' => static fn (TestRunner $t) => $t->same(5, $summary()['triggers']),
    'view trigger ddl corpus summary temp count' => static fn (TestRunner $t) => $t->same(2, $summary()['temporary']),
    'view trigger ddl corpus summary instead count' => static fn (TestRunner $t) => $t->same(1, $summary()['insteadOf']),
    'view trigger ddl corpus summary trigger events' => static fn (TestRunner $t) => $t->same(['delete' => 2, 'insert' => 2, 'update' => 1], $summary()['triggerEvents']),
    'view trigger ddl corpus summary view dependencies' => static fn (TestRunner $t) => $t->same(['app_settings', 'app_setting_audit'], $summary()['viewDependencies']),
    'view trigger ddl corpus summary dangling triggers' => static fn (TestRunner $t) => $t->same(['dangling_setting_cleanup'], $summary()['danglingTriggers']),
    'view trigger ddl corpus drop view status' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropView($records, 'loadable_settings')['status']),
    'view trigger ddl corpus drop view removes target' => static fn (TestRunner $t) => $t->same(['loadable_settings'], SQLiteViewTriggerDdlCorpus::dropView($records, 'loadable_settings')['dropped']),
    'view trigger ddl corpus drop view leaves trigger dangling' => static fn (TestRunner $t) => $t->same(['setting_view_insert', 'dangling_setting_cleanup'], SQLiteViewTriggerDdlCorpus::dropView($records, 'loadable_settings')['danglingTriggers']),
    'view trigger ddl corpus drop trigger status' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'setting_audit_insert')['status']),
    'view trigger ddl corpus drop trigger removes target' => static fn (TestRunner $t) => $t->same(['setting_audit_insert'], SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'setting_audit_insert')['dropped']),
    'view trigger ddl corpus drop trigger keeps view names' => static fn (TestRunner $t) => $t->same(true, in_array('loadable_settings', SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'setting_audit_insert')['remaining'], true)),
    'view trigger ddl corpus drop missing view if exists' => static fn (TestRunner $t) => $t->same('missing', SQLiteViewTriggerDdlCorpus::dropView($records, 'missing_view', true)['status']),
    'view trigger ddl corpus drop missing trigger if exists flag' => static fn (TestRunner $t) => $t->same(true, SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'missing_trigger', true)['ifExists']),
    'view trigger ddl corpus missing view without if exists throws' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::dropView($records, 'missing_view')),
    'view trigger ddl corpus missing trigger without if exists throws' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'missing_trigger')),
    'view trigger ddl corpus rejects view root page' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('view', 'bad_view', 'bad_view', 9, 'CREATE VIEW bad_view AS SELECT 1', 11)])),
    'view trigger ddl corpus rejects view without sql' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('view', 'bad_view', 'bad_view', 0, null, 12)])),
    'view trigger ddl corpus rejects trigger root page' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bad_trigger', 'app_settings', 7, 'CREATE TRIGGER bad_trigger AFTER INSERT ON app_settings BEGIN SELECT 1; END', 13)])),
    'view trigger ddl corpus rejects trigger without sql' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bad_trigger', 'app_settings', 0, null, 14)])),
    'view trigger ddl corpus rejects malformed trigger sql' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bad_trigger', 'app_settings', 0, 'CREATE TRIGGER bad_trigger BEGIN SELECT 1; END', 15)])),
    'view trigger ddl corpus ignores table records in views' => static fn (TestRunner $t) => $t->same([], SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('table', 'app_settings', 'app_settings', 2, 'CREATE TABLE app_settings(setting_id integer)', 16)])),
    'view trigger ddl corpus ignores view records in triggers' => static fn (TestRunner $t) => $t->same([], SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('view', 'v', 'v', 0, 'CREATE VIEW v AS SELECT 1', 17)])),
    'view trigger ddl corpus quoted view columns' => static fn (TestRunner $t) => $t->same(['setting key'], SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('view', 'quoted_view', 'quoted_view', 0, 'CREATE VIEW quoted_view("setting key") AS SELECT key_name FROM app_settings', 18)])[0]['columns']),
    'view trigger ddl corpus quoted trigger pseudo column' => static fn (TestRunner $t) => $t->same(['key_name'], SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'quoted_trigger', 'app_settings', 0, 'CREATE TRIGGER quoted_trigger AFTER INSERT ON app_settings BEGIN SELECT new."key_name"; END', 19)])[0]['referencedNew']),
    'view trigger ddl corpus default trigger timing is before' => static fn (TestRunner $t) => $t->same('before', SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'implicit_before', 'app_settings', 0, 'CREATE TRIGGER implicit_before INSERT ON app_settings BEGIN SELECT new.setting_id; END', 20)])[0]['timing']),
    'view trigger ddl corpus trigger body missing begin has zero statements' => static fn (TestRunner $t) => $t->same(0, SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bodyless', 'app_settings', 0, 'CREATE TRIGGER bodyless AFTER INSERT ON app_settings SELECT new.setting_id', 21)])[0]['bodyStatements']),
    'view trigger ddl corpus drop by case insensitive name' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropView($records, 'LOADABLE_SETTINGS')['status']),
    'view trigger ddl corpus trigger by case insensitive name' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'SETTING_AUDIT_INSERT')['status']),
];
