<?php

declare(strict_types=1);

use PortLibs\LibSqlite\SQLiteSchemaRecord;
use PortLibs\LibSqlite\SQLiteViewTriggerDdlCorpus;

$records = [
    new SQLiteSchemaRecord('table', 'wp_options', 'wp_options', 2, 'CREATE TABLE wp_options(option_id integer primary key, option_name text, option_value text, autoload text)', 1),
    new SQLiteSchemaRecord('table', 'wp_option_audit', 'wp_option_audit', 3, 'CREATE TABLE wp_option_audit(option_id integer, action text)', 2),
    new SQLiteSchemaRecord('view', 'autoloaded_options', 'autoloaded_options', 0, "CREATE VIEW autoloaded_options(option_id, option_name) AS SELECT option_id, option_name FROM wp_options WHERE autoload = 'yes'", 3),
    new SQLiteSchemaRecord('view', 'temp_option_names', 'temp_option_names', null, 'CREATE TEMP VIEW temp_option_names(name) AS SELECT option_name FROM main.wp_options', 4),
    new SQLiteSchemaRecord('view', 'joined_option_audit', 'joined_option_audit', 0, 'CREATE VIEW joined_option_audit AS SELECT o.option_name, a.action FROM wp_options o JOIN wp_option_audit a ON a.option_id = o.option_id', 5),
    new SQLiteSchemaRecord('trigger', 'option_audit_insert', 'wp_options', 0, "CREATE TRIGGER option_audit_insert AFTER INSERT ON wp_options BEGIN INSERT INTO wp_option_audit(option_id, action) VALUES (new.option_id, 'insert'); END", 6),
    new SQLiteSchemaRecord('trigger', 'option_name_guard', 'wp_options', 0, "CREATE TRIGGER option_name_guard BEFORE UPDATE ON wp_options BEGIN SELECT CASE WHEN new.option_name IS NULL THEN RAISE(ABORT, 'missing option_name') END; INSERT INTO wp_option_audit(option_id, action) VALUES (old.option_id, 'rename'); END", 7),
    new SQLiteSchemaRecord('trigger', 'option_view_insert', 'autoloaded_options', 0, "CREATE TRIGGER option_view_insert INSTEAD OF INSERT ON autoloaded_options BEGIN INSERT INTO wp_options(option_id, option_name, autoload) VALUES (new.option_id, new.option_name, 'yes'); END", 8),
    new SQLiteSchemaRecord('trigger', 'temp_option_delete', 'wp_options', null, "CREATE TEMP TRIGGER temp_option_delete AFTER DELETE ON wp_options BEGIN INSERT INTO wp_option_audit(option_id, action) VALUES (old.option_id, 'delete'); END", 9),
    new SQLiteSchemaRecord('trigger', 'dangling_option_cleanup', 'missing_options', 0, 'CREATE TRIGGER dangling_option_cleanup AFTER DELETE ON missing_options BEGIN SELECT old.option_id; END', 10),
];

$views = static fn (): array => SQLiteViewTriggerDdlCorpus::views($records);
$triggers = static fn (): array => SQLiteViewTriggerDdlCorpus::triggers($records);
$summary = static fn (): array => SQLiteViewTriggerDdlCorpus::summary($records);

return [
    'view trigger ddl corpus counts views' => static fn (TestRunner $t) => $t->same(3, count($views())),
    'view trigger ddl corpus first view name' => static fn (TestRunner $t) => $t->same('autoloaded_options', $views()[0]['name']),
    'view trigger ddl corpus preserves view table name' => static fn (TestRunner $t) => $t->same('autoloaded_options', $views()[0]['table']),
    'view trigger ddl corpus detects explicit view columns' => static fn (TestRunner $t) => $t->same(['option_id', 'option_name'], $views()[0]['columns']),
    'view trigger ddl corpus detects temp view column' => static fn (TestRunner $t) => $t->same(['name'], $views()[1]['columns']),
    'view trigger ddl corpus leaves implicit view columns empty' => static fn (TestRunner $t) => $t->same([], $views()[2]['columns']),
    'view trigger ddl corpus detects view dependency' => static fn (TestRunner $t) => $t->same(['wp_options'], $views()[0]['dependencies']),
    'view trigger ddl corpus strips schema-qualified dependency' => static fn (TestRunner $t) => $t->same(['wp_options'], $views()[1]['dependencies']),
    'view trigger ddl corpus detects joined dependencies' => static fn (TestRunner $t) => $t->same(['wp_options', 'wp_option_audit'], $views()[2]['dependencies']),
    'view trigger ddl corpus detects temp view' => static fn (TestRunner $t) => $t->same(true, $views()[1]['temporary']),
    'view trigger ddl corpus main view is not temp' => static fn (TestRunner $t) => $t->same(false, $views()[0]['temporary']),
    'view trigger ddl corpus normalizes view sql whitespace' => static fn (TestRunner $t) => $t->same("CREATE VIEW autoloaded_options(option_id, option_name) AS SELECT option_id, option_name FROM wp_options WHERE autoload = 'yes'", $views()[0]['sql']),
    'view trigger ddl corpus counts triggers' => static fn (TestRunner $t) => $t->same(5, count($triggers())),
    'view trigger ddl corpus first trigger name' => static fn (TestRunner $t) => $t->same('option_audit_insert', $triggers()[0]['name']),
    'view trigger ddl corpus after trigger timing' => static fn (TestRunner $t) => $t->same('after', $triggers()[0]['timing']),
    'view trigger ddl corpus insert trigger event' => static fn (TestRunner $t) => $t->same('insert', $triggers()[0]['event']),
    'view trigger ddl corpus before trigger timing' => static fn (TestRunner $t) => $t->same('before', $triggers()[1]['timing']),
    'view trigger ddl corpus update trigger event' => static fn (TestRunner $t) => $t->same('update', $triggers()[1]['event']),
    'view trigger ddl corpus instead of trigger timing' => static fn (TestRunner $t) => $t->same('instead of', $triggers()[2]['timing']),
    'view trigger ddl corpus instead of flag' => static fn (TestRunner $t) => $t->same(true, $triggers()[2]['insteadOf']),
    'view trigger ddl corpus ordinary trigger not instead of' => static fn (TestRunner $t) => $t->same(false, $triggers()[0]['insteadOf']),
    'view trigger ddl corpus delete trigger event' => static fn (TestRunner $t) => $t->same('delete', $triggers()[3]['event']),
    'view trigger ddl corpus detects temp trigger' => static fn (TestRunner $t) => $t->same(true, $triggers()[3]['temporary']),
    'view trigger ddl corpus main trigger is not temp' => static fn (TestRunner $t) => $t->same(false, $triggers()[0]['temporary']),
    'view trigger ddl corpus trigger target table' => static fn (TestRunner $t) => $t->same('wp_options', $triggers()[0]['table']),
    'view trigger ddl corpus view trigger target' => static fn (TestRunner $t) => $t->same('autoloaded_options', $triggers()[2]['table']),
    'view trigger ddl corpus trigger body one statement' => static fn (TestRunner $t) => $t->same(1, $triggers()[0]['bodyStatements']),
    'view trigger ddl corpus trigger body two statements' => static fn (TestRunner $t) => $t->same(2, $triggers()[1]['bodyStatements']),
    'view trigger ddl corpus trigger new references' => static fn (TestRunner $t) => $t->same(['option_id'], $triggers()[0]['referencedNew']),
    'view trigger ddl corpus update trigger new references' => static fn (TestRunner $t) => $t->same(['option_name'], $triggers()[1]['referencedNew']),
    'view trigger ddl corpus update trigger old references' => static fn (TestRunner $t) => $t->same(['option_id'], $triggers()[1]['referencedOld']),
    'view trigger ddl corpus instead trigger new references' => static fn (TestRunner $t) => $t->same(['option_id', 'option_name'], $triggers()[2]['referencedNew']),
    'view trigger ddl corpus delete trigger old references' => static fn (TestRunner $t) => $t->same(['option_id'], $triggers()[3]['referencedOld']),
    'view trigger ddl corpus trigger insert dependency' => static fn (TestRunner $t) => $t->same(['wp_option_audit'], $triggers()[0]['dependencies']),
    'view trigger ddl corpus trigger mixed dependencies' => static fn (TestRunner $t) => $t->same(['wp_option_audit'], $triggers()[1]['dependencies']),
    'view trigger ddl corpus trigger target insert dependency' => static fn (TestRunner $t) => $t->same(['wp_options'], $triggers()[2]['dependencies']),
    'view trigger ddl corpus dangling trigger dependency empty' => static fn (TestRunner $t) => $t->same([], $triggers()[4]['dependencies']),
    'view trigger ddl corpus dangling trigger detected' => static fn (TestRunner $t) => $t->same(['dangling_option_cleanup'], SQLiteViewTriggerDdlCorpus::danglingTriggers($records)),
    'view trigger ddl corpus summary view count' => static fn (TestRunner $t) => $t->same(3, $summary()['views']),
    'view trigger ddl corpus summary trigger count' => static fn (TestRunner $t) => $t->same(5, $summary()['triggers']),
    'view trigger ddl corpus summary temp count' => static fn (TestRunner $t) => $t->same(2, $summary()['temporary']),
    'view trigger ddl corpus summary instead count' => static fn (TestRunner $t) => $t->same(1, $summary()['insteadOf']),
    'view trigger ddl corpus summary trigger events' => static fn (TestRunner $t) => $t->same(['delete' => 2, 'insert' => 2, 'update' => 1], $summary()['triggerEvents']),
    'view trigger ddl corpus summary view dependencies' => static fn (TestRunner $t) => $t->same(['wp_options', 'wp_option_audit'], $summary()['viewDependencies']),
    'view trigger ddl corpus summary dangling triggers' => static fn (TestRunner $t) => $t->same(['dangling_option_cleanup'], $summary()['danglingTriggers']),
    'view trigger ddl corpus drop view status' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropView($records, 'autoloaded_options')['status']),
    'view trigger ddl corpus drop view removes target' => static fn (TestRunner $t) => $t->same(['autoloaded_options'], SQLiteViewTriggerDdlCorpus::dropView($records, 'autoloaded_options')['dropped']),
    'view trigger ddl corpus drop view leaves trigger dangling' => static fn (TestRunner $t) => $t->same(['option_view_insert', 'dangling_option_cleanup'], SQLiteViewTriggerDdlCorpus::dropView($records, 'autoloaded_options')['danglingTriggers']),
    'view trigger ddl corpus drop trigger status' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'option_audit_insert')['status']),
    'view trigger ddl corpus drop trigger removes target' => static fn (TestRunner $t) => $t->same(['option_audit_insert'], SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'option_audit_insert')['dropped']),
    'view trigger ddl corpus drop trigger keeps view names' => static fn (TestRunner $t) => $t->same(true, in_array('autoloaded_options', SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'option_audit_insert')['remaining'], true)),
    'view trigger ddl corpus drop missing view if exists' => static fn (TestRunner $t) => $t->same('missing', SQLiteViewTriggerDdlCorpus::dropView($records, 'missing_view', true)['status']),
    'view trigger ddl corpus drop missing trigger if exists flag' => static fn (TestRunner $t) => $t->same(true, SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'missing_trigger', true)['ifExists']),
    'view trigger ddl corpus missing view without if exists throws' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::dropView($records, 'missing_view')),
    'view trigger ddl corpus missing trigger without if exists throws' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'missing_trigger')),
    'view trigger ddl corpus rejects view root page' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('view', 'bad_view', 'bad_view', 9, 'CREATE VIEW bad_view AS SELECT 1', 11)])),
    'view trigger ddl corpus rejects view without sql' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('view', 'bad_view', 'bad_view', 0, null, 12)])),
    'view trigger ddl corpus rejects trigger root page' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bad_trigger', 'wp_options', 7, 'CREATE TRIGGER bad_trigger AFTER INSERT ON wp_options BEGIN SELECT 1; END', 13)])),
    'view trigger ddl corpus rejects trigger without sql' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bad_trigger', 'wp_options', 0, null, 14)])),
    'view trigger ddl corpus rejects malformed trigger sql' => static fn (TestRunner $t) => $t->throws(InvalidArgumentException::class, static fn () => SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bad_trigger', 'wp_options', 0, 'CREATE TRIGGER bad_trigger BEGIN SELECT 1; END', 15)])),
    'view trigger ddl corpus ignores table records in views' => static fn (TestRunner $t) => $t->same([], SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('table', 'wp_options', 'wp_options', 2, 'CREATE TABLE wp_options(option_id integer)', 16)])),
    'view trigger ddl corpus ignores view records in triggers' => static fn (TestRunner $t) => $t->same([], SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('view', 'v', 'v', 0, 'CREATE VIEW v AS SELECT 1', 17)])),
    'view trigger ddl corpus quoted view columns' => static fn (TestRunner $t) => $t->same(['option name'], SQLiteViewTriggerDdlCorpus::views([new SQLiteSchemaRecord('view', 'quoted_view', 'quoted_view', 0, 'CREATE VIEW quoted_view("option name") AS SELECT option_name FROM wp_options', 18)])[0]['columns']),
    'view trigger ddl corpus quoted trigger pseudo column' => static fn (TestRunner $t) => $t->same(['option_name'], SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'quoted_trigger', 'wp_options', 0, 'CREATE TRIGGER quoted_trigger AFTER INSERT ON wp_options BEGIN SELECT new."option_name"; END', 19)])[0]['referencedNew']),
    'view trigger ddl corpus default trigger timing is before' => static fn (TestRunner $t) => $t->same('before', SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'implicit_before', 'wp_options', 0, 'CREATE TRIGGER implicit_before INSERT ON wp_options BEGIN SELECT new.option_id; END', 20)])[0]['timing']),
    'view trigger ddl corpus trigger body missing begin has zero statements' => static fn (TestRunner $t) => $t->same(0, SQLiteViewTriggerDdlCorpus::triggers([new SQLiteSchemaRecord('trigger', 'bodyless', 'wp_options', 0, 'CREATE TRIGGER bodyless AFTER INSERT ON wp_options SELECT new.option_id', 21)])[0]['bodyStatements']),
    'view trigger ddl corpus drop by case insensitive name' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropView($records, 'AUTOLOADED_OPTIONS')['status']),
    'view trigger ddl corpus trigger by case insensitive name' => static fn (TestRunner $t) => $t->same('dropped', SQLiteViewTriggerDdlCorpus::dropTrigger($records, 'OPTION_AUDIT_INSERT')['status']),
];
