<?php

declare(strict_types=1);

use PortLibs\LibSqlite\SQLitePagerMasterJournalReaderCacheCurrentSourceNextPlan;

$tests = [];

$pageSize = 512;
$database = '/srv/wp-content/database/wp-next398.sqlite';
$usersDatabase = '/srv/wp-content/database/wp-next398-users.sqlite';
$mainJournal = $database . '-journal';
$usersJournal = $usersDatabase . '-journal';
$master = $database . '-mj';
$masterBytes = "{$mainJournal}\n{$usersJournal}\n";
$page = static fn (string $label): string => str_pad($label, $pageSize, '.', STR_PAD_RIGHT);
$formatPage = static function (string $label) use ($pageSize): string {
    $page = str_pad('SQLite format 3' . "\0", 100, "\0", STR_PAD_RIGHT) . str_repeat('.', $pageSize - 100);
    $page = substr_replace($page, pack('n', 512), 16, 2);
    $page = substr_replace($page, chr(4), 20, 1);
    $page = substr_replace($page, pack('N', 2), 56, 4);
    $page = substr_replace($page, pack('N', 398), 60, 4);

    return substr_replace($page, $label, 100, strlen($label));
};
$mapDigest = static function (array $map): string {
    ksort($map, SORT_STRING);

    return hash('sha256', implode('|', array_map(static fn (string $key, string $value): string => $key . '=' . $value, array_keys($map), $map)));
};
$recoveredDigest = static function (array $pages): string {
    ksort($pages, SORT_NUMERIC);

    return hash('sha256', implode('|', array_map(static fn (int $pageNumber, string $image): string => $pageNumber . ':' . hash('sha256', $image), array_keys($pages), $pages)));
};

$before = [1 => $formatPage('next398 stale schema'), 2 => $page('next398 stale options'), 3 => $page('next398 stale plugins'), 4 => $page('next398 stale users')];
$recovered = [1 => $formatPage('next398 current schema'), 2 => $page('next398 current options'), 3 => $page('next398 current plugins'), 4 => $page('next398 current users')];
$tokens = [$mainJournal => 'member-main-current-398', $usersJournal => 'member-users-current-398'];
$headers = [$mainJournal => hash('sha256', 'main header next398'), $usersJournal => hash('sha256', 'users header next398')];
$base = [
    'source_id' => 'pager-reader-cache-current-source-next398',
    'epoch' => 398,
    'format_signature' => hash('sha256', implode('|', [512, 4, 2, 398, 0])),
    'publication_generation' => 398,
    'master_source_digest' => hash('sha256', 'master-next398'),
    'recovery_sequence' => 398,
    'recovered_page_set_digest' => $recoveredDigest($recovered),
    'member_journal_tokens' => $tokens,
    'member_journal_header_digests' => $headers,
    'master_member_order_digest' => hash('sha256', implode("\n", array_keys($tokens))),
    'master_journal_file_token' => 'master-file-current-398',
    'master_journal_bytes_digest' => hash('sha256', $masterBytes),
    'database_file_token' => 'database-file-current-398',
    'master_journal_cleanup_token' => 'master-cleanup-current-398',
    'reader_lease_token' => 'reader-lease-current-398',
    'pager_cache_source_token' => 'pager-cache-source-current-398',
    'read_transaction_token' => 'read-transaction-current-398',
    'schema_reparse_token' => 'schema-reparse-current-398',
    'statement_schema_root_token' => 'statement-schema-root-current-398',
    'current_source_provenance_token' => 'source-provenance-current-398',
    'pager_reader_cache_generation_token' => 'cache-generation-current-398',
    'reader_snapshot_token' => 'reader-snapshot-current-398',
    'master_journal_recovery_receipt_token' => 'recovery-receipt-current-398',
    'pager_spill_drain_token' => 'spill-drain-current-398',
    'rollback_journal_reader_source_token' => 'rollback-source-current-398',
    'pager_hot_journal_header_token' => 'hot-header-current-398',
    'master_journal_member_epoch_token' => 'member-epoch-current-398',
    'reader_cache_schema_cookie_token' => 'schema-cookie-current-398',
    'reader_cache_vacuum_root_token' => 'vacuum-root-current-398',
    'pager_reserved_lock_token' => 'reserved-lock-current-398',
    'reader_cache_page_count_token' => 'page-count-current-398',
    'reader_cache_schema_version_token' => 'schema-version-current-398',
    'reader_cache_change_counter_token' => 'change-counter-current-398',
    'reader_cache_freelist_trunk_token' => 'freelist-trunk-current-398',
    'reader_cache_auto_vacuum_token' => 'auto-vacuum-current-398',
    'reader_cache_encoding_token' => 'encoding-current-398',
    'reader_cache_text_schema_token' => 'text-schema-current-398',
    'reader_cache_index_schema_token' => 'index-schema-current-398',
    'reader_cache_trigger_schema_token' => 'trigger-schema-current-398',
    'reader_cache_view_schema_token' => 'view-schema-current-398',
    'reader_cache_virtual_table_schema_token' => 'virtual-table-schema-current-398',
    'reader_cache_module_schema_token' => 'module-schema-current-398',
    'reader_cache_pragma_schema_token' => 'pragma-schema-current-398',
    'reader_cache_collation_schema_token' => 'collation-schema-current-398',
    'reader_cache_authorizer_schema_token' => 'authorizer-schema-current-398',
    'reader_cache_transaction_state_token' => 'transaction-state-current-398',
    'reader_cache_commit_phase_token' => 'commit-phase-current-398',
    'reader_cache_busy_handler_token' => 'busy-handler-current-398',
    'reader_cache_savepoint_stack_token' => 'savepoint-stack-current-398',
    'reader_cache_statement_journal_token' => 'statement-journal-current-398',
    'reader_cache_temp_page_token' => 'temp-page-current-398',
    'reader_cache_dirty_list_token' => 'dirty-list-current-398',
    'reader_cache_spill_epoch_token' => 'spill-epoch-current-398',
    'reader_cache_locking_mode_token' => 'locking-mode-current-398',
    'reader_cache_journal_mode_token' => 'journal-mode-current-398',
    'reader_cache_synchronous_token' => 'synchronous-current-398',
    'reader_cache_mmap_size_token' => 'mmap-size-current-398',
    'reader_cache_cache_size_token' => 'cache-size-current-398',
    'reader_cache_wal_autocheckpoint_token' => 'wal-autocheckpoint-current-398',
    'reader_cache_query_only_token' => 'query-only-current-398',
    'reader_cache_foreign_key_token' => 'foreign-key-current-398',
    'reader_cache_defer_foreign_key_token' => 'defer-foreign-key-current-398',
    'reader_cache_recursive_trigger_token' => 'recursive-trigger-current-398',
    'reader_cache_trusted_schema_token' => 'trusted-schema-current-398',
    'reader_cache_ignore_check_constraints_token' => 'ignore-check-constraints-current-398',
    'reader_cache_application_id_token' => 'application-id-current-398',
    'reader_cache_user_version_token' => 'user-version-current-398',
    'reader_cache_data_version_token' => 'data-version-current-398',
    'reader_cache_schema_lock_token' => 'schema-lock-current-398',
    'reader_cache_schema_format_token' => 'schema-format-current-398',
    'reader_cache_auto_vacuum_incremental_token' => 'auto-vacuum-incremental-current-398',
    'reader_cache_reverse_unordered_selects_token' => 'reverse-unordered-selects-current-398',
    'reader_cache_automatic_index_token' => 'automatic-index-current-398',
    'reader_cache_case_sensitive_like_token' => 'case-sensitive-like-current-398',
    'reader_cache_count_changes_token' => 'count-changes-current-398',
    'reader_cache_checkpoint_fullfsync_token' => 'checkpoint-fullfsync-current-398',
    'reader_cache_fullfsync_token' => 'fullfsync-current-398',
    'reader_cache_legacy_file_format_token' => 'legacy-file-format-current-398',
    'reader_cache_read_uncommitted_token' => 'read-uncommitted-current-398',
    'reader_cache_reverse_scan_order_token' => 'reverse-scan-order-current-398',
    'reader_cache_defensive_token' => 'defensive-current-398',
    'reader_cache_writable_schema_token' => 'writable-schema-current-398',
    'reader_cache_journal_size_limit_token' => 'journal-size-limit-current-398',
    'reader_cache_secure_delete_token' => 'secure-delete-current-398',
    'reader_cache_temp_store_token' => 'temp-store-current-398',
    'reader_cache_cache_spill_token' => 'cache-spill-current-398',
    'reader_cache_cell_size_check_token' => 'cell-size-check-current-398',
    'reader_cache_threads_token' => 'threads-current-398',
    'reader_cache_optimize_token' => 'optimize-current-398',
    'reader_cache_analysis_limit_token' => 'analysis-limit-current-398',
    'reader_cache_hard_heap_limit_token' => 'hard-heap-limit-current-398',
    'reader_cache_soft_heap_limit_token' => 'soft-heap-limit-current-398',
    'reader_cache_page_size_token' => 'page-size-current-398',
    'reader_cache_max_page_count_token' => 'max-page-count-current-398',
    'reader_cache_locking_proxy_file_token' => 'locking-proxy-file-current-398',
    'reader_cache_page_cache_overflow_token' => 'page-cache-overflow-current-398',
    'reader_cache_scratch_allocator_token' => 'scratch-allocator-current-398',
    'reader_cache_lookaside_token' => 'lookaside-current-398',
    'reader_cache_pcache_dirty_limit_token' => 'pcache-dirty-limit-current-398',
    'reader_cache_mmap_read_limit_token' => 'mmap-read-limit-current-398',
    'reader_cache_sorter_reference_token' => 'sorter-reference-current-398',
    'reader_cache_worker_thread_token' => 'worker-thread-current-398',
    'reader_cache_memory_alarm_token' => 'memory-alarm-current-398',
    'reader_cache_status_counter_token' => 'status-counter-current-398',
    'reader_cache_pagecache_size_token' => 'pagecache-size-current-398',
    'reader_cache_pagecache_recycle_token' => 'pagecache-recycle-current-398',
    'reader_cache_scratch_spill_token' => 'scratch-spill-current-398',
    'reader_cache_lookaside_hit_token' => 'lookaside-hit-current-398',
    'reader_cache_lookaside_miss_size_token' => 'lookaside-miss-size-current-398',
    'reader_cache_pcache_refcount_token' => 'pcache-refcount-current-398',
    'reader_cache_memory_used_token' => 'memory-used-current-398',
    'reader_cache_memory_highwater_token' => 'memory-highwater-current-398',
    'reader_cache_pagecache_used_token' => 'pagecache-used-current-398',
    'reader_cache_pagecache_overflow_token' => 'pagecache-overflow-current-398',
    'reader_cache_scratch_used_token' => 'scratch-used-current-398',
    'reader_cache_scratch_overflow_token' => 'scratch-overflow-current-398',
    'reader_cache_malloc_size_token' => 'malloc-size-current-398',
    'reader_cache_malloc_count_token' => 'malloc-count-current-398',
    'reader_cache_stmt_used_token' => 'stmt-used-current-398',
    'reader_cache_stmt_busy_token' => 'stmt-busy-current-398',
    'reader_cache_stmt_memused_token' => 'stmt-memused-current-398',
    'reader_cache_stmt_scanstatus_token' => 'stmt-scanstatus-current-398',
    'reader_cache_stmt_reprepare_token' => 'stmt-reprepare-current-398',
    'reader_cache_stmt_run_token' => 'stmt-run-current-398',
    'reader_cache_stmt_sort_token' => 'stmt-sort-current-398',
    'reader_cache_stmt_autoindex_token' => 'stmt-autoindex-current-398',
    'reader_cache_stmt_fullscan_token' => 'stmt-fullscan-current-398',
    'reader_cache_stmt_vmstep_token' => 'stmt-vmstep-current-398',
    'reader_cache_stmt_filter_hit_token' => 'stmt-filter-hit-current-398',
    'reader_cache_stmt_filter_miss_token' => 'stmt-filter-miss-current-398',
    'reader_cache_stmt_nsort_token' => 'stmt-nsort-current-398',
    'reader_cache_stmt_nautoindex_token' => 'stmt-nautoindex-current-398',
    'reader_cache_stmt_nfullscan_token' => 'stmt-nfullscan-current-398',
    'reader_cache_stmt_expired_token' => 'stmt-expired-current-398',
    'reader_cache_stmt_readonly_token' => 'stmt-readonly-current-398',
    'reader_cache_stmt_scanstatus_nloop_token' => 'stmt-scanstatus-nloop-current-398',
    'reader_cache_stmt_scanstatus_nvisit_token' => 'stmt-scanstatus-nvisit-current-398',
    'reader_cache_stmt_scanstatus_est_token' => 'stmt-scanstatus-est-current-398',
    'reader_cache_stmt_scanstatus_name_token' => 'stmt-scanstatus-name-current-398',
    'reader_cache_stmt_scanstatus_explain_token' => 'stmt-scanstatus-explain-current-398',
    'reader_cache_stmt_scanstatus_selectid_token' => 'stmt-scanstatus-selectid-current-398',
    'reader_cache_stmt_scanstatus_parentid_token' => 'stmt-scanstatus-parentid-current-398',
    'reader_cache_stmt_scanstatus_ncycle_token' => 'stmt-scanstatus-ncycle-current-398',
    'reader_cache_stmt_vm_halt_token' => 'stmt-vm-halt-current-398',
    'reader_cache_stmt_vm_reset_token' => 'stmt-vm-reset-current-398',
    'reader_cache_stmt_bind_parameter_token' => 'stmt-bind-parameter-current-398',
    'reader_cache_stmt_expanded_sql_token' => 'stmt-expanded-sql-current-398',
    'reader_cache_stmt_normalized_sql_token' => 'stmt-normalized-sql-current-398',
    'reader_cache_stmt_sql_text_token' => 'stmt-sql-text-current-398',
    'reader_cache_stmt_readonly_schema_token' => 'stmt-readonly-schema-current-398',
    'reader_cache_stmt_busy_state_token' => 'stmt-busy-state-current-398',
];
$cacheEntry = static fn (string $label, string $image, array $extra = []): array => array_merge($base, ['label' => $label, 'reader_id' => $label . '-reader', 'image' => $image], $extra);
$read = static fn (int $pageNumber, array $extra = []): array => array_merge([
    'reader_id' => 'read-' . $pageNumber,
    'page_number' => $pageNumber,
    'source_id' => $base['source_id'],
    'epoch' => 398,
    'format_signature' => $base['format_signature'],
    'publication_generation' => 398,
    'master_source_digest' => $base['master_source_digest'],
    'recovery_sequence' => 398,
    'recovered_page_set_digest' => $base['recovered_page_set_digest'],
    'member_journal_token_digest' => $mapDigest($tokens),
    'member_journal_header_digest' => $mapDigest($headers),
    'master_member_order_digest' => $base['master_member_order_digest'],
    'master_journal_file_token' => $base['master_journal_file_token'],
    'master_journal_bytes_digest' => $base['master_journal_bytes_digest'],
    'database_file_token' => $base['database_file_token'],
    'master_journal_cleanup_token' => $base['master_journal_cleanup_token'],
    'reader_lease_token' => $base['reader_lease_token'],
    'pager_cache_source_token' => $base['pager_cache_source_token'],
    'read_transaction_token' => $base['read_transaction_token'],
    'schema_reparse_token' => $base['schema_reparse_token'],
    'statement_schema_root_token' => $base['statement_schema_root_token'],
    'current_source_provenance_token' => $base['current_source_provenance_token'],
    'pager_reader_cache_generation_token' => $base['pager_reader_cache_generation_token'],
    'reader_snapshot_token' => $base['reader_snapshot_token'],
    'master_journal_recovery_receipt_token' => $base['master_journal_recovery_receipt_token'],
    'pager_spill_drain_token' => $base['pager_spill_drain_token'],
    'rollback_journal_reader_source_token' => $base['rollback_journal_reader_source_token'],
    'pager_hot_journal_header_token' => $base['pager_hot_journal_header_token'],
    'master_journal_member_epoch_token' => $base['master_journal_member_epoch_token'],
    'reader_cache_schema_cookie_token' => $base['reader_cache_schema_cookie_token'],
    'reader_cache_vacuum_root_token' => $base['reader_cache_vacuum_root_token'],
    'pager_reserved_lock_token' => $base['pager_reserved_lock_token'],
    'reader_cache_page_count_token' => $base['reader_cache_page_count_token'],
    'reader_cache_schema_version_token' => $base['reader_cache_schema_version_token'],
    'reader_cache_change_counter_token' => $base['reader_cache_change_counter_token'],
    'reader_cache_freelist_trunk_token' => $base['reader_cache_freelist_trunk_token'],
    'reader_cache_auto_vacuum_token' => $base['reader_cache_auto_vacuum_token'],
    'reader_cache_encoding_token' => $base['reader_cache_encoding_token'],
    'reader_cache_text_schema_token' => $base['reader_cache_text_schema_token'],
    'reader_cache_index_schema_token' => $base['reader_cache_index_schema_token'],
    'reader_cache_trigger_schema_token' => $base['reader_cache_trigger_schema_token'],
    'reader_cache_view_schema_token' => $base['reader_cache_view_schema_token'],
    'reader_cache_virtual_table_schema_token' => $base['reader_cache_virtual_table_schema_token'],
    'reader_cache_module_schema_token' => $base['reader_cache_module_schema_token'],
    'reader_cache_pragma_schema_token' => $base['reader_cache_pragma_schema_token'],
    'reader_cache_collation_schema_token' => $base['reader_cache_collation_schema_token'],
    'reader_cache_authorizer_schema_token' => $base['reader_cache_authorizer_schema_token'],
    'reader_cache_transaction_state_token' => $base['reader_cache_transaction_state_token'],
    'reader_cache_commit_phase_token' => $base['reader_cache_commit_phase_token'],
    'reader_cache_busy_handler_token' => $base['reader_cache_busy_handler_token'],
    'reader_cache_savepoint_stack_token' => $base['reader_cache_savepoint_stack_token'],
    'reader_cache_statement_journal_token' => $base['reader_cache_statement_journal_token'],
    'reader_cache_temp_page_token' => $base['reader_cache_temp_page_token'],
    'reader_cache_dirty_list_token' => $base['reader_cache_dirty_list_token'],
    'reader_cache_spill_epoch_token' => $base['reader_cache_spill_epoch_token'],
    'reader_cache_locking_mode_token' => $base['reader_cache_locking_mode_token'],
    'reader_cache_journal_mode_token' => $base['reader_cache_journal_mode_token'],
    'reader_cache_synchronous_token' => $base['reader_cache_synchronous_token'],
    'reader_cache_mmap_size_token' => $base['reader_cache_mmap_size_token'],
    'reader_cache_cache_size_token' => $base['reader_cache_cache_size_token'],
    'reader_cache_wal_autocheckpoint_token' => $base['reader_cache_wal_autocheckpoint_token'],
    'reader_cache_query_only_token' => $base['reader_cache_query_only_token'],
    'reader_cache_foreign_key_token' => $base['reader_cache_foreign_key_token'],
    'reader_cache_defer_foreign_key_token' => $base['reader_cache_defer_foreign_key_token'],
    'reader_cache_recursive_trigger_token' => $base['reader_cache_recursive_trigger_token'],
    'reader_cache_trusted_schema_token' => $base['reader_cache_trusted_schema_token'],
    'reader_cache_ignore_check_constraints_token' => $base['reader_cache_ignore_check_constraints_token'],
    'reader_cache_application_id_token' => $base['reader_cache_application_id_token'],
    'reader_cache_user_version_token' => $base['reader_cache_user_version_token'],
    'reader_cache_data_version_token' => $base['reader_cache_data_version_token'],
    'reader_cache_schema_lock_token' => $base['reader_cache_schema_lock_token'],
    'reader_cache_schema_format_token' => $base['reader_cache_schema_format_token'],
    'reader_cache_auto_vacuum_incremental_token' => $base['reader_cache_auto_vacuum_incremental_token'],
    'reader_cache_reverse_unordered_selects_token' => $base['reader_cache_reverse_unordered_selects_token'],
    'reader_cache_automatic_index_token' => $base['reader_cache_automatic_index_token'],
    'reader_cache_case_sensitive_like_token' => $base['reader_cache_case_sensitive_like_token'],
    'reader_cache_count_changes_token' => $base['reader_cache_count_changes_token'],
    'reader_cache_checkpoint_fullfsync_token' => $base['reader_cache_checkpoint_fullfsync_token'],
    'reader_cache_fullfsync_token' => $base['reader_cache_fullfsync_token'],
    'reader_cache_legacy_file_format_token' => $base['reader_cache_legacy_file_format_token'],
    'reader_cache_read_uncommitted_token' => $base['reader_cache_read_uncommitted_token'],
    'reader_cache_reverse_scan_order_token' => $base['reader_cache_reverse_scan_order_token'],
    'reader_cache_defensive_token' => $base['reader_cache_defensive_token'],
    'reader_cache_writable_schema_token' => $base['reader_cache_writable_schema_token'],
    'reader_cache_journal_size_limit_token' => $base['reader_cache_journal_size_limit_token'],
    'reader_cache_secure_delete_token' => $base['reader_cache_secure_delete_token'],
    'reader_cache_temp_store_token' => $base['reader_cache_temp_store_token'],
    'reader_cache_cache_spill_token' => $base['reader_cache_cache_spill_token'],
    'reader_cache_cell_size_check_token' => $base['reader_cache_cell_size_check_token'],
    'reader_cache_threads_token' => $base['reader_cache_threads_token'],
    'reader_cache_optimize_token' => $base['reader_cache_optimize_token'],
    'reader_cache_analysis_limit_token' => $base['reader_cache_analysis_limit_token'],
    'reader_cache_hard_heap_limit_token' => $base['reader_cache_hard_heap_limit_token'],
    'reader_cache_soft_heap_limit_token' => $base['reader_cache_soft_heap_limit_token'],
    'reader_cache_page_size_token' => $base['reader_cache_page_size_token'],
    'reader_cache_max_page_count_token' => $base['reader_cache_max_page_count_token'],
    'reader_cache_locking_proxy_file_token' => $base['reader_cache_locking_proxy_file_token'],
    'reader_cache_page_cache_overflow_token' => $base['reader_cache_page_cache_overflow_token'],
    'reader_cache_scratch_allocator_token' => $base['reader_cache_scratch_allocator_token'],
    'reader_cache_lookaside_token' => $base['reader_cache_lookaside_token'],
    'reader_cache_pcache_dirty_limit_token' => $base['reader_cache_pcache_dirty_limit_token'],
    'reader_cache_mmap_read_limit_token' => $base['reader_cache_mmap_read_limit_token'],
    'reader_cache_sorter_reference_token' => $base['reader_cache_sorter_reference_token'],
    'reader_cache_worker_thread_token' => $base['reader_cache_worker_thread_token'],
    'reader_cache_memory_alarm_token' => $base['reader_cache_memory_alarm_token'],
    'reader_cache_status_counter_token' => $base['reader_cache_status_counter_token'],
    'reader_cache_pagecache_size_token' => $base['reader_cache_pagecache_size_token'],
    'reader_cache_pagecache_recycle_token' => $base['reader_cache_pagecache_recycle_token'],
    'reader_cache_scratch_spill_token' => $base['reader_cache_scratch_spill_token'],
    'reader_cache_lookaside_hit_token' => $base['reader_cache_lookaside_hit_token'],
    'reader_cache_lookaside_miss_size_token' => $base['reader_cache_lookaside_miss_size_token'],
    'reader_cache_pcache_refcount_token' => $base['reader_cache_pcache_refcount_token'],
    'reader_cache_memory_used_token' => $base['reader_cache_memory_used_token'],
    'reader_cache_memory_highwater_token' => $base['reader_cache_memory_highwater_token'],
    'reader_cache_pagecache_used_token' => $base['reader_cache_pagecache_used_token'],
    'reader_cache_pagecache_overflow_token' => $base['reader_cache_pagecache_overflow_token'],
    'reader_cache_scratch_used_token' => $base['reader_cache_scratch_used_token'],
    'reader_cache_scratch_overflow_token' => $base['reader_cache_scratch_overflow_token'],
    'reader_cache_malloc_size_token' => $base['reader_cache_malloc_size_token'],
    'reader_cache_malloc_count_token' => $base['reader_cache_malloc_count_token'],
    'reader_cache_stmt_used_token' => $base['reader_cache_stmt_used_token'],
    'reader_cache_stmt_busy_token' => $base['reader_cache_stmt_busy_token'],
    'reader_cache_stmt_memused_token' => $base['reader_cache_stmt_memused_token'],
    'reader_cache_stmt_scanstatus_token' => $base['reader_cache_stmt_scanstatus_token'],
    'reader_cache_stmt_reprepare_token' => $base['reader_cache_stmt_reprepare_token'],
    'reader_cache_stmt_run_token' => $base['reader_cache_stmt_run_token'],
    'reader_cache_stmt_sort_token' => $base['reader_cache_stmt_sort_token'],
    'reader_cache_stmt_autoindex_token' => $base['reader_cache_stmt_autoindex_token'],
    'reader_cache_stmt_fullscan_token' => $base['reader_cache_stmt_fullscan_token'],
    'reader_cache_stmt_vmstep_token' => $base['reader_cache_stmt_vmstep_token'],
    'reader_cache_stmt_filter_hit_token' => $base['reader_cache_stmt_filter_hit_token'],
    'reader_cache_stmt_filter_miss_token' => $base['reader_cache_stmt_filter_miss_token'],
    'reader_cache_stmt_nsort_token' => $base['reader_cache_stmt_nsort_token'],
    'reader_cache_stmt_nautoindex_token' => $base['reader_cache_stmt_nautoindex_token'],
    'reader_cache_stmt_nfullscan_token' => $base['reader_cache_stmt_nfullscan_token'],
    'reader_cache_stmt_expired_token' => $base['reader_cache_stmt_expired_token'],
    'reader_cache_stmt_readonly_token' => $base['reader_cache_stmt_readonly_token'],
    'reader_cache_stmt_scanstatus_nloop_token' => $base['reader_cache_stmt_scanstatus_nloop_token'],
    'reader_cache_stmt_scanstatus_nvisit_token' => $base['reader_cache_stmt_scanstatus_nvisit_token'],
    'reader_cache_stmt_scanstatus_est_token' => $base['reader_cache_stmt_scanstatus_est_token'],
    'reader_cache_stmt_scanstatus_name_token' => $base['reader_cache_stmt_scanstatus_name_token'],
    'reader_cache_stmt_scanstatus_explain_token' => $base['reader_cache_stmt_scanstatus_explain_token'],
    'reader_cache_stmt_scanstatus_selectid_token' => $base['reader_cache_stmt_scanstatus_selectid_token'],
    'reader_cache_stmt_scanstatus_parentid_token' => $base['reader_cache_stmt_scanstatus_parentid_token'],
    'reader_cache_stmt_scanstatus_ncycle_token' => $base['reader_cache_stmt_scanstatus_ncycle_token'],
    'reader_cache_stmt_vm_halt_token' => $base['reader_cache_stmt_vm_halt_token'],
    'reader_cache_stmt_vm_reset_token' => $base['reader_cache_stmt_vm_reset_token'],
    'reader_cache_stmt_bind_parameter_token' => $base['reader_cache_stmt_bind_parameter_token'],
    'reader_cache_stmt_expanded_sql_token' => $base['reader_cache_stmt_expanded_sql_token'],
    'reader_cache_stmt_normalized_sql_token' => $base['reader_cache_stmt_normalized_sql_token'],
    'reader_cache_stmt_sql_text_token' => $base['reader_cache_stmt_sql_text_token'],
    'reader_cache_stmt_readonly_schema_token' => $base['reader_cache_stmt_readonly_schema_token'],
    'reader_cache_stmt_busy_state_token' => $base['reader_cache_stmt_busy_state_token'],
], $extra);
$plan = static function (?array $cache = null, ?array $reads = null) use ($database, $master, $masterBytes, $before, $pageSize, $recovered, $base, $tokens, $headers, $cacheEntry, $read): array {
    return SQLitePagerMasterJournalReaderCacheCurrentSourceNextPlan::readerCacheStatementFence(398, $database, $master, $masterBytes, implode('', $before), $pageSize, $recovered, $cache ?? [
        1 => $cacheEntry('schema-stale-module', $recovered[1], ['reader_cache_module_schema_token' => 'module-schema-old']),
        2 => $cacheEntry('options-stale-pragma', $recovered[2], ['reader_cache_pragma_schema_token' => 'pragma-schema-old']),
        3 => $cacheEntry('plugins-stale-collation', $recovered[3], ['reader_cache_collation_schema_token' => 'collation-schema-old']),
        4 => $cacheEntry('users-stale-secure-delete', $recovered[4], ['reader_cache_secure_delete_token' => 'secure-delete-old']),
    ], $reads ?? [$read(1), $read(2), $read(3), $read(4, ['reader_cache_savepoint_stack_token' => 'savepoint-stack-old', 'reader_cache_statement_journal_token' => 'statement-journal-old', 'reader_cache_temp_page_token' => 'temp-page-old', 'reader_cache_dirty_list_token' => 'dirty-list-old', 'reader_cache_spill_epoch_token' => 'spill-epoch-old', 'reader_cache_locking_mode_token' => 'locking-mode-old', 'reader_cache_journal_mode_token' => 'journal-mode-old', 'reader_cache_synchronous_token' => 'synchronous-old', 'reader_cache_mmap_size_token' => 'mmap-size-old', 'reader_cache_cache_size_token' => 'cache-size-old', 'reader_cache_wal_autocheckpoint_token' => 'wal-autocheckpoint-old', 'reader_cache_query_only_token' => 'query-only-old', 'reader_cache_foreign_key_token' => 'foreign-key-old', 'reader_cache_defer_foreign_key_token' => 'defer-foreign-key-old', 'reader_cache_recursive_trigger_token' => 'recursive-trigger-old', 'reader_cache_trusted_schema_token' => 'trusted-schema-old', 'reader_cache_ignore_check_constraints_token' => 'ignore-check-constraints-old', 'reader_cache_application_id_token' => 'application-id-old', 'reader_cache_user_version_token' => 'user-version-old', 'reader_cache_data_version_token' => 'data-version-old', 'reader_cache_schema_lock_token' => 'schema-lock-old', 'reader_cache_secure_delete_token' => 'secure-delete-old', 'reader_cache_temp_store_token' => 'temp-store-old', 'reader_cache_cache_spill_token' => 'cache-spill-old', 'reader_cache_cell_size_check_token' => 'cell-size-check-old', 'reader_cache_reverse_unordered_selects_token' => 'reverse-unordered-selects-old', 'reader_cache_automatic_index_token' => 'automatic-index-old', 'reader_cache_case_sensitive_like_token' => 'case-sensitive-like-old', 'reader_cache_count_changes_token' => 'count-changes-old', 'reader_cache_checkpoint_fullfsync_token' => 'checkpoint-fullfsync-old', 'reader_cache_fullfsync_token' => 'fullfsync-old', 'reader_cache_legacy_file_format_token' => 'legacy-file-format-old', 'reader_cache_read_uncommitted_token' => 'read-uncommitted-old', 'reader_cache_reverse_scan_order_token' => 'reverse-scan-order-old', 'reader_cache_defensive_token' => 'defensive-old', 'reader_cache_writable_schema_token' => 'writable-schema-old', 'reader_cache_journal_size_limit_token' => 'journal-size-limit-old', 'reader_cache_threads_token' => 'threads-old', 'reader_cache_optimize_token' => 'optimize-old', 'reader_cache_analysis_limit_token' => 'analysis-limit-old', 'reader_cache_hard_heap_limit_token' => 'hard-heap-limit-old', 'reader_cache_soft_heap_limit_token' => 'soft-heap-limit-old', 'reader_cache_page_size_token' => 'page-size-old', 'reader_cache_max_page_count_token' => 'max-page-count-old', 'reader_cache_locking_proxy_file_token' => 'locking-proxy-file-old', 'reader_cache_page_cache_overflow_token' => 'page-cache-overflow-old', 'reader_cache_scratch_allocator_token' => 'scratch-allocator-old', 'reader_cache_lookaside_token' => 'lookaside-old', 'reader_cache_pcache_dirty_limit_token' => 'pcache-dirty-limit-old', 'reader_cache_mmap_read_limit_token' => 'mmap-read-limit-old', 'reader_cache_sorter_reference_token' => 'sorter-reference-old', 'reader_cache_worker_thread_token' => 'worker-thread-old', 'reader_cache_memory_alarm_token' => 'memory-alarm-old', 'reader_cache_status_counter_token' => 'status-counter-old', 'reader_cache_pagecache_size_token' => 'pagecache-size-old', 'reader_cache_pagecache_recycle_token' => 'pagecache-recycle-old', 'reader_cache_scratch_spill_token' => 'scratch-spill-old', 'reader_cache_lookaside_hit_token' => 'lookaside-hit-old', 'reader_cache_lookaside_miss_size_token' => 'lookaside-miss-size-old', 'reader_cache_pcache_refcount_token' => 'pcache-refcount-old', 'reader_cache_memory_used_token' => 'memory-used-old', 'reader_cache_memory_highwater_token' => 'memory-highwater-old', 'reader_cache_pagecache_used_token' => 'pagecache-used-old', 'reader_cache_pagecache_overflow_token' => 'pagecache-overflow-old', 'reader_cache_scratch_used_token' => 'scratch-used-old', 'reader_cache_scratch_overflow_token' => 'scratch-overflow-old', 'reader_cache_malloc_size_token' => 'malloc-size-old', 'reader_cache_malloc_count_token' => 'malloc-count-old', 'reader_cache_stmt_used_token' => 'stmt-used-old', 'reader_cache_stmt_busy_token' => 'stmt-busy-old', 'reader_cache_stmt_memused_token' => 'stmt-memused-old', 'reader_cache_stmt_scanstatus_token' => 'stmt-scanstatus-old', 'reader_cache_stmt_reprepare_token' => 'stmt-reprepare-old', 'reader_cache_stmt_run_token' => 'stmt-run-old', 'reader_cache_stmt_sort_token' => 'stmt-sort-old', 'reader_cache_stmt_autoindex_token' => 'stmt-autoindex-old', 'reader_cache_stmt_fullscan_token' => 'stmt-fullscan-old', 'reader_cache_stmt_vmstep_token' => 'stmt-vmstep-old', 'reader_cache_stmt_filter_hit_token' => 'stmt-filter-hit-old', 'reader_cache_stmt_filter_miss_token' => 'stmt-filter-miss-old', 'reader_cache_stmt_nsort_token' => 'stmt-nsort-old', 'reader_cache_stmt_nautoindex_token' => 'stmt-nautoindex-old', 'reader_cache_stmt_nfullscan_token' => 'stmt-nfullscan-old', 'reader_cache_stmt_expired_token' => 'stmt-expired-old', 'reader_cache_stmt_readonly_token' => 'stmt-readonly-old', 'reader_cache_stmt_scanstatus_nloop_token' => 'stmt-scanstatus-nloop-old', 'reader_cache_stmt_scanstatus_nvisit_token' => 'stmt-scanstatus-nvisit-old', 'reader_cache_stmt_scanstatus_est_token' => 'stmt-scanstatus-est-old', 'reader_cache_stmt_scanstatus_name_token' => 'stmt-scanstatus-name-old', 'reader_cache_stmt_scanstatus_explain_token' => 'stmt-scanstatus-explain-old', 'reader_cache_stmt_scanstatus_selectid_token' => 'stmt-scanstatus-selectid-old', 'reader_cache_stmt_scanstatus_parentid_token' => 'stmt-scanstatus-parentid-old', 'reader_cache_stmt_scanstatus_ncycle_token' => 'stmt-scanstatus-ncycle-old', 'reader_cache_stmt_vm_halt_token' => 'stmt-vm-halt-old', 'reader_cache_stmt_vm_reset_token' => 'stmt-vm-reset-old', 'reader_cache_stmt_bind_parameter_token' => 'stmt-bind-parameter-old', 'reader_cache_stmt_expanded_sql_token' => 'stmt-expanded-sql-old', 'reader_cache_stmt_normalized_sql_token' => 'stmt-normalized-sql-old', 'reader_cache_stmt_sql_text_token' => 'stmt-sql-text-old', 'reader_cache_stmt_readonly_schema_token' => 'stmt-readonly-schema-old', 'reader_cache_stmt_busy_state_token' => 'stmt-busy-state-old'])], $base['source_id'], 398, 398, $base['master_source_digest'], 398, $tokens, $headers, $base['master_journal_file_token'], $base['database_file_token'], $base['master_journal_cleanup_token'], $base['reader_lease_token'], $base['pager_cache_source_token'], $base['read_transaction_token'], $base['schema_reparse_token'], $base['statement_schema_root_token'], $base['current_source_provenance_token'], $base['pager_reader_cache_generation_token'], $base['reader_snapshot_token'], $base['master_journal_recovery_receipt_token'], $base['pager_spill_drain_token'], $base['rollback_journal_reader_source_token'], $base['pager_hot_journal_header_token'], $base['master_journal_member_epoch_token'], $base['reader_cache_schema_cookie_token'], $base['reader_cache_vacuum_root_token'], $base['pager_reserved_lock_token'], $base['reader_cache_page_count_token'], $base['reader_cache_schema_version_token'], $base['reader_cache_change_counter_token'], $base['reader_cache_freelist_trunk_token'], $base['reader_cache_auto_vacuum_token'], $base['reader_cache_encoding_token'], $base['reader_cache_text_schema_token'], $base['reader_cache_index_schema_token'], $base['reader_cache_trigger_schema_token'], $base['reader_cache_view_schema_token'], $base['reader_cache_virtual_table_schema_token'], $base['reader_cache_module_schema_token'], $base['reader_cache_pragma_schema_token'], $base['reader_cache_collation_schema_token'], $base['reader_cache_authorizer_schema_token'], $base['reader_cache_transaction_state_token'], $base['reader_cache_commit_phase_token'], $base['reader_cache_busy_handler_token'], $base['reader_cache_savepoint_stack_token'], $base['reader_cache_statement_journal_token'], $base['reader_cache_temp_page_token'], $base['reader_cache_dirty_list_token'], $base['reader_cache_spill_epoch_token'], $base['reader_cache_locking_mode_token'], $base['reader_cache_journal_mode_token'], $base['reader_cache_synchronous_token'], $base['reader_cache_mmap_size_token'], $base['reader_cache_cache_size_token'], $base['reader_cache_wal_autocheckpoint_token'], $base['reader_cache_query_only_token'], $base['reader_cache_foreign_key_token'], $base['reader_cache_defer_foreign_key_token'], $base['reader_cache_recursive_trigger_token'], $base['reader_cache_trusted_schema_token'], $base['reader_cache_ignore_check_constraints_token'], $base['reader_cache_application_id_token'], $base['reader_cache_user_version_token'], $base['reader_cache_data_version_token'], $base['reader_cache_schema_lock_token'], $base['reader_cache_secure_delete_token'], $base['reader_cache_temp_store_token'], $base['reader_cache_cache_spill_token'], $base['reader_cache_cell_size_check_token'], $base['reader_cache_reverse_unordered_selects_token'], $base['reader_cache_automatic_index_token'], $base['reader_cache_case_sensitive_like_token'], $base['reader_cache_count_changes_token'], $base['reader_cache_checkpoint_fullfsync_token'], $base['reader_cache_fullfsync_token'], $base['reader_cache_legacy_file_format_token'], $base['reader_cache_read_uncommitted_token'], $base['reader_cache_reverse_scan_order_token'], $base['reader_cache_defensive_token'], $base['reader_cache_writable_schema_token'], $base['reader_cache_journal_size_limit_token'], $base['reader_cache_threads_token'], $base['reader_cache_optimize_token'], $base['reader_cache_analysis_limit_token'], $base['reader_cache_hard_heap_limit_token'], $base['reader_cache_soft_heap_limit_token'], $base['reader_cache_page_size_token'], $base['reader_cache_max_page_count_token'], $base['reader_cache_locking_proxy_file_token'], $base['reader_cache_page_cache_overflow_token'], $base['reader_cache_scratch_allocator_token'], $base['reader_cache_lookaside_token'], $base['reader_cache_pcache_dirty_limit_token'], $base['reader_cache_mmap_read_limit_token'], $base['reader_cache_sorter_reference_token'], $base['reader_cache_worker_thread_token'], $base["reader_cache_memory_alarm_token"], $base["reader_cache_status_counter_token"], $base["reader_cache_pagecache_size_token"], $base["reader_cache_pagecache_recycle_token"], $base["reader_cache_scratch_spill_token"], $base["reader_cache_lookaside_hit_token"], $base["reader_cache_lookaside_miss_size_token"], $base["reader_cache_pcache_refcount_token"], $base["reader_cache_memory_used_token"], $base["reader_cache_memory_highwater_token"], $base["reader_cache_pagecache_used_token"], $base["reader_cache_pagecache_overflow_token"], $base["reader_cache_scratch_used_token"], $base["reader_cache_scratch_overflow_token"], $base["reader_cache_malloc_size_token"], $base["reader_cache_malloc_count_token"], $base["reader_cache_stmt_used_token"], $base["reader_cache_stmt_busy_token"], $base["reader_cache_stmt_memused_token"], $base["reader_cache_stmt_scanstatus_token"], $base["reader_cache_stmt_reprepare_token"], $base["reader_cache_stmt_run_token"], $base["reader_cache_stmt_sort_token"], $base["reader_cache_stmt_autoindex_token"], $base["reader_cache_stmt_fullscan_token"], $base["reader_cache_stmt_vmstep_token"], $base["reader_cache_stmt_filter_hit_token"], $base["reader_cache_stmt_filter_miss_token"], $base["reader_cache_stmt_nsort_token"], $base["reader_cache_stmt_nautoindex_token"], $base["reader_cache_stmt_nfullscan_token"], $base["reader_cache_stmt_expired_token"], $base["reader_cache_stmt_readonly_token"], $base["reader_cache_stmt_scanstatus_nloop_token"], $base["reader_cache_stmt_scanstatus_nvisit_token"], $base["reader_cache_stmt_scanstatus_est_token"], $base["reader_cache_stmt_scanstatus_name_token"], $base["reader_cache_stmt_scanstatus_explain_token"], $base["reader_cache_stmt_scanstatus_selectid_token"], $base["reader_cache_stmt_scanstatus_parentid_token"], $base["reader_cache_stmt_scanstatus_ncycle_token"], $base["reader_cache_stmt_vm_halt_token"], $base["reader_cache_stmt_vm_reset_token"], $base["reader_cache_stmt_bind_parameter_token"], $base["reader_cache_stmt_expanded_sql_token"], $base["reader_cache_stmt_normalized_sql_token"], $base["reader_cache_stmt_sql_text_token"], $base["reader_cache_stmt_readonly_schema_token"], $base["reader_cache_stmt_busy_state_token"]);
};
$opCount = static fn (array $plan, string $op): int => count(array_filter($plan['operations'], static fn (array $operation): bool => ($operation['op'] ?? '') === $op));

$cases = [
    'status' => [static fn (): mixed => $plan()['status'], 'pager-master-journal-reader-cache-current-source-next398'],
    'next287 module-schema invalidation' => [static fn (): mixed => $plan()['reader_cache_module_schema_invalidated_cache_page_numbers'], [1]],
    'next288 pragma-schema invalidation' => [static fn (): mixed => $plan()['reader_cache_pragma_schema_invalidated_cache_page_numbers'], [2]],
    'next289 collation-schema invalidation' => [static fn (): mixed => $plan()['reader_cache_collation_schema_invalidated_cache_page_numbers'], [3]],
    'next291 transaction-state fence is current' => [static fn (): mixed => $plan()['current_reader_cache_transaction_state_token'], 'transaction-state-current-398'],
    'next292 commit-phase fence is current' => [static fn (): mixed => $plan()['current_reader_cache_commit_phase_token'], 'commit-phase-current-398'],
    'next293 busy-handler fence is current' => [static fn (): mixed => $plan()['current_reader_cache_busy_handler_token'], 'busy-handler-current-398'],
    'next294 savepoint-stack ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_savepoint_stack_token_reason'], 'reader_ticket_reader_cache_savepoint_stack_predates_current_source'],
    'next295 statement-journal ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_statement_journal_token_reason'], 'reader_ticket_reader_cache_statement_journal_predates_current_source'],
    'next296 temp-page ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_temp_page_token_reason'], 'reader_ticket_reader_cache_temp_page_predates_current_source'],
    'next297 dirty-list ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_dirty_list_token_reason'], 'reader_ticket_reader_cache_dirty_list_predates_current_source'],
    'next298 spill-epoch ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_spill_epoch_token_reason'], 'reader_ticket_reader_cache_spill_epoch_predates_current_source'],
    'next299 locking-mode ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_locking_mode_token_reason'], 'reader_ticket_reader_cache_locking_mode_predates_current_source'],
    'next300 journal-mode ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_journal_mode_token_reason'], 'reader_ticket_reader_cache_journal_mode_predates_current_source'],
    'next301 synchronous ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_synchronous_token_reason'], 'reader_ticket_reader_cache_synchronous_predates_current_source'],
    'next302 mmap-size ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_mmap_size_token_reason'], 'reader_ticket_reader_cache_mmap_size_predates_current_source'],
    'next303 cache-size ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_cache_size_token_reason'], 'reader_ticket_reader_cache_cache_size_predates_current_source'],
    'next304 wal-autocheckpoint ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_wal_autocheckpoint_token_reason'], 'reader_ticket_reader_cache_wal_autocheckpoint_predates_current_source'],
    'next305 query-only ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_query_only_token_reason'], 'reader_ticket_reader_cache_query_only_predates_current_source'],
    'next306 foreign-key ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_foreign_key_token_reason'], 'reader_ticket_reader_cache_foreign_key_predates_current_source'],
    'next307 defer-foreign-key ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_defer_foreign_key_token_reason'], 'reader_ticket_reader_cache_defer_foreign_key_predates_current_source'],
    'next308 recursive-trigger ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_recursive_trigger_token_reason'], 'reader_ticket_reader_cache_recursive_trigger_predates_current_source'],
    'next309 trusted-schema ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_trusted_schema_token_reason'], 'reader_ticket_reader_cache_trusted_schema_predates_current_source'],
    'next310 ignore-check-constraints ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_ignore_check_constraints_token_reason'], 'reader_ticket_reader_cache_ignore_check_constraints_predates_current_source'],
    'next315 application-id ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_application_id_token_reason'], 'reader_ticket_reader_cache_application_id_predates_current_source'],
    'next316 user-version ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_user_version_token_reason'], 'reader_ticket_reader_cache_user_version_predates_current_source'],
    'next317 data-version ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_data_version_token_reason'], 'reader_ticket_reader_cache_data_version_predates_current_source'],
    'next318 schema-lock ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_schema_lock_token_reason'], 'reader_ticket_reader_cache_schema_lock_predates_current_source'],
    'next319 secure-delete invalidation' => [static fn (): mixed => $plan()['reader_cache_secure_delete_invalidated_cache_page_numbers'], [4]],
    'next320 temp-store ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_temp_store_token_reason'], 'reader_ticket_reader_cache_temp_store_predates_current_source'],
    'next321 cache-spill ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_cache_spill_token_reason'], 'reader_ticket_reader_cache_cache_spill_predates_current_source'],
    'next322 cell-size-check ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_cell_size_check_token_reason'], 'reader_ticket_reader_cache_cell_size_check_predates_current_source'],
    'next323 reverse-unordered-selects ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_reverse_unordered_selects_token_reason'], 'reader_ticket_reader_cache_reverse_unordered_selects_predates_current_source'],
    'next324 automatic-index ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_automatic_index_token_reason'], 'reader_ticket_reader_cache_automatic_index_predates_current_source'],
    'next325 case-sensitive-like ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_case_sensitive_like_token_reason'], 'reader_ticket_reader_cache_case_sensitive_like_predates_current_source'],
    'next326 count-changes ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_count_changes_token_reason'], 'reader_ticket_reader_cache_count_changes_predates_current_source'],
    'next327 checkpoint-fullfsync ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_checkpoint_fullfsync_token_reason'], 'reader_ticket_reader_cache_checkpoint_fullfsync_predates_current_source'],
    'next328 fullfsync ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_fullfsync_token_reason'], 'reader_ticket_reader_cache_fullfsync_predates_current_source'],
    'next329 legacy-file-format ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_legacy_file_format_token_reason'], 'reader_ticket_reader_cache_legacy_file_format_predates_current_source'],
    'next330 read-uncommitted ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_read_uncommitted_token_reason'], 'reader_ticket_reader_cache_read_uncommitted_predates_current_source'],
    'next331 reverse-scan-order ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_reverse_scan_order_token_reason'], 'reader_ticket_reader_cache_reverse_scan_order_predates_current_source'],
    'next332 defensive ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_defensive_token_reason'], 'reader_ticket_reader_cache_defensive_predates_current_source'],
    'next333 writable-schema ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_writable_schema_token_reason'], 'reader_ticket_reader_cache_writable_schema_predates_current_source'],
    'next334 journal-size-limit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_journal_size_limit_token_reason'], 'reader_ticket_reader_cache_journal_size_limit_predates_current_source'],
    'next335 threads ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_threads_token_reason'], 'reader_ticket_reader_cache_threads_predates_current_source'],
    'next336 optimize ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_optimize_token_reason'], 'reader_ticket_reader_cache_optimize_predates_current_source'],
    'next337 analysis-limit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_analysis_limit_token_reason'], 'reader_ticket_reader_cache_analysis_limit_predates_current_source'],
    'next338 hard-heap-limit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_hard_heap_limit_token_reason'], 'reader_ticket_reader_cache_hard_heap_limit_predates_current_source'],
    'next339 soft-heap-limit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_soft_heap_limit_token_reason'], 'reader_ticket_reader_cache_soft_heap_limit_predates_current_source'],
    'next340 page-size ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_page_size_token_reason'], 'reader_ticket_reader_cache_page_size_predates_current_source'],
    'next341 max-page-count ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_max_page_count_token_reason'], 'reader_ticket_reader_cache_max_page_count_predates_current_source'],
    'next342 locking-proxy-file ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_locking_proxy_file_token_reason'], 'reader_ticket_reader_cache_locking_proxy_file_predates_current_source'],
    'next343 page-cache-overflow ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_page_cache_overflow_token_reason'], 'reader_ticket_reader_cache_page_cache_overflow_predates_current_source'],
    'next344 scratch-allocator ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_scratch_allocator_token_reason'], 'reader_ticket_reader_cache_scratch_allocator_predates_current_source'],
    'next345 lookaside ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_lookaside_token_reason'], 'reader_ticket_reader_cache_lookaside_predates_current_source'],
    'next346 pcache-dirty-limit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_pcache_dirty_limit_token_reason'], 'reader_ticket_reader_cache_pcache_dirty_limit_predates_current_source'],
    'next347 mmap-read-limit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_mmap_read_limit_token_reason'], 'reader_ticket_reader_cache_mmap_read_limit_predates_current_source'],
    'next348 sorter-reference ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_sorter_reference_token_reason'], 'reader_ticket_reader_cache_sorter_reference_predates_current_source'],
    'next349 worker-thread ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_worker_thread_token_reason'], 'reader_ticket_reader_cache_worker_thread_predates_current_source'],
    'next350 memory-alarm ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_memory_alarm_token_reason'], 'reader_ticket_reader_cache_memory_alarm_predates_current_source'],
    'next351 status-counter ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_status_counter_token_reason'], 'reader_ticket_reader_cache_status_counter_predates_current_source'],
    'next352 pagecache-size ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_pagecache_size_token_reason'], 'reader_ticket_reader_cache_pagecache_size_predates_current_source'],
    'next353 pagecache-recycle ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_pagecache_recycle_token_reason'], 'reader_ticket_reader_cache_pagecache_recycle_predates_current_source'],
    'next354 scratch-spill ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_scratch_spill_token_reason'], 'reader_ticket_reader_cache_scratch_spill_predates_current_source'],
    'next355 lookaside-hit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_lookaside_hit_token_reason'], 'reader_ticket_reader_cache_lookaside_hit_predates_current_source'],
    'next356 lookaside-miss-size ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_lookaside_miss_size_token_reason'], 'reader_ticket_reader_cache_lookaside_miss_size_predates_current_source'],
    'next357 pcache-refcount ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_pcache_refcount_token_reason'], 'reader_ticket_reader_cache_pcache_refcount_predates_current_source'],
    'next358 memory-used ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_memory_used_token_reason'], 'reader_ticket_reader_cache_memory_used_predates_current_source'],
    'next359 memory-highwater ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_memory_highwater_token_reason'], 'reader_ticket_reader_cache_memory_highwater_predates_current_source'],
    'next360 pagecache-used ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_pagecache_used_token_reason'], 'reader_ticket_reader_cache_pagecache_used_predates_current_source'],
    'next361 pagecache-overflow ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_pagecache_overflow_token_reason'], 'reader_ticket_reader_cache_pagecache_overflow_predates_current_source'],
    'next362 scratch-used ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_scratch_used_token_reason'], 'reader_ticket_reader_cache_scratch_used_predates_current_source'],
    'next363 scratch-overflow ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_scratch_overflow_token_reason'], 'reader_ticket_reader_cache_scratch_overflow_predates_current_source'],
    'next364 malloc-size ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_malloc_size_token_reason'], 'reader_ticket_reader_cache_malloc_size_predates_current_source'],
    'next365 malloc-count ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_malloc_count_token_reason'], 'reader_ticket_reader_cache_malloc_count_predates_current_source'],
    'next366 stmt-used ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_used_token_reason'], 'reader_ticket_reader_cache_stmt_used_predates_current_source'],
    'next367 stmt-busy ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_busy_token_reason'], 'reader_ticket_reader_cache_stmt_busy_predates_current_source'],
    'next368 stmt-memused ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_memused_token_reason'], 'reader_ticket_reader_cache_stmt_memused_predates_current_source'],
    'next369 stmt-scanstatus ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_predates_current_source'],
    'next370 stmt-reprepare ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_reprepare_token_reason'], 'reader_ticket_reader_cache_stmt_reprepare_predates_current_source'],
    'next371 stmt-run ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_run_token_reason'], 'reader_ticket_reader_cache_stmt_run_predates_current_source'],
    'next372 stmt-sort ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_sort_token_reason'], 'reader_ticket_reader_cache_stmt_sort_predates_current_source'],
    'next373 stmt-autoindex ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_autoindex_token_reason'], 'reader_ticket_reader_cache_stmt_autoindex_predates_current_source'],
    'next374 stmt-fullscan ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_fullscan_token_reason'], 'reader_ticket_reader_cache_stmt_fullscan_predates_current_source'],
    'next375 stmt-vmstep ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_vmstep_token_reason'], 'reader_ticket_reader_cache_stmt_vmstep_predates_current_source'],
    'next376 stmt-filter-hit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_filter_hit_token_reason'], 'reader_ticket_reader_cache_stmt_filter_hit_predates_current_source'],
    'next377 stmt-filter-miss ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_filter_miss_token_reason'], 'reader_ticket_reader_cache_stmt_filter_miss_predates_current_source'],
    'next378 stmt-nsort ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_nsort_token_reason'], 'reader_ticket_reader_cache_stmt_nsort_predates_current_source'],
    'next379 stmt-nautoindex ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_nautoindex_token_reason'], 'reader_ticket_reader_cache_stmt_nautoindex_predates_current_source'],
    'next380 stmt-nfullscan ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_nfullscan_token_reason'], 'reader_ticket_reader_cache_stmt_nfullscan_predates_current_source'],
    'next381 stmt-expired ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_expired_token_reason'], 'reader_ticket_reader_cache_stmt_expired_predates_current_source'],
    'next382 stmt-readonly ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_readonly_token_reason'], 'reader_ticket_reader_cache_stmt_readonly_predates_current_source'],
    'next383 stmt-scanstatus-nloop ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_nloop_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_nloop_predates_current_source'],
    'next384 stmt-scanstatus-nvisit ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_nvisit_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_nvisit_predates_current_source'],
    'next385 stmt-scanstatus-est ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_est_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_est_predates_current_source'],
    'next386 stmt-scanstatus-name ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_name_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_name_predates_current_source'],
    'next387 stmt-scanstatus-explain ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_explain_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_explain_predates_current_source'],
    'next388 stmt-scanstatus-selectid ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_selectid_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_selectid_predates_current_source'],
    'next389 stmt-scanstatus-parentid ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_parentid_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_parentid_predates_current_source'],
    'next390 stmt-scanstatus-ncycle ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_scanstatus_ncycle_token_reason'], 'reader_ticket_reader_cache_stmt_scanstatus_ncycle_predates_current_source'],
    'next391 stmt-vm-halt ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_vm_halt_token_reason'], 'reader_ticket_reader_cache_stmt_vm_halt_predates_current_source'],
    'next392 stmt-vm-reset ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_vm_reset_token_reason'], 'reader_ticket_reader_cache_stmt_vm_reset_predates_current_source'],
    'next393 stmt-bind-parameter ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_bind_parameter_token_reason'], 'reader_ticket_reader_cache_stmt_bind_parameter_predates_current_source'],
    'next394 stmt-expanded-sql ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_expanded_sql_token_reason'], 'reader_ticket_reader_cache_stmt_expanded_sql_predates_current_source'],
    'next395 stmt-normalized-sql ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_normalized_sql_token_reason'], 'reader_ticket_reader_cache_stmt_normalized_sql_predates_current_source'],
    'next396 stmt-sql-text ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_sql_text_token_reason'], 'reader_ticket_reader_cache_stmt_sql_text_predates_current_source'],
    'next397 stmt-readonly-schema ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_readonly_schema_token_reason'], 'reader_ticket_reader_cache_stmt_readonly_schema_predates_current_source'],
    'next398 stmt-busy-state ticket reopens reader' => [static fn (): mixed => $plan()['next_reads'][3]['reader_cache_stmt_busy_state_token_reason'], 'reader_ticket_reader_cache_stmt_busy_state_predates_current_source'],
    'combined invalidation set' => [static fn (): mixed => $plan()['invalidated_cache_page_numbers'], [1, 2, 3, 4]],
    'read hits include savepoint-stack miss' => [static fn (): mixed => $plan()['read_cache_hits'], ['read-1' => false, 'read-2' => false, 'read-3' => false, 'read-4' => false]],
    'dependencies include next287' => [static fn (): mixed => in_array('sqlite-pager-master-journal-reader-cache-current-source-next287', $plan()['dependencies'], true), true],
    'dependencies include next398' => [static fn (): mixed => in_array('sqlite-pager-master-journal-reader-cache-current-source-next398', $plan()['dependencies'], true), true],
    'operation next295' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_statement_journal_current_source_next295'), 1],
    'operation next296' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_temp_page_current_source_next296'), 1],
    'operation next297' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_dirty_list_current_source_next297'), 1],
    'operation next298' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_spill_epoch_current_source_next298'), 1],
    'operation next299' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_locking_mode_current_source_next299'), 1],
    'operation next300' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_journal_mode_current_source_next300'), 1],
    'operation next301' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_synchronous_current_source_next301'), 1],
    'operation next302' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_mmap_size_current_source_next302'), 1],
    'operation next303' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_cache_size_current_source_next303'), 1],
    'operation next304' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_wal_autocheckpoint_current_source_next304'), 1],
    'operation next305' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_query_only_current_source_next305'), 1],
    'operation next306' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_foreign_key_current_source_next306'), 1],
    'operation next307' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_defer_foreign_key_current_source_next307'), 1],
    'operation next308' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_recursive_trigger_current_source_next308'), 1],
    'operation next309' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_trusted_schema_current_source_next309'), 1],
    'operation next310' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_ignore_check_constraints_current_source_next310'), 1],
    'operation next315' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_application_id_current_source_next315'), 1],
    'operation next316' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_user_version_current_source_next316'), 1],
    'operation next317' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_data_version_current_source_next317'), 1],
    'operation next318' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_schema_lock_current_source_next318'), 1],
    'operation next319' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_secure_delete_current_source_next319'), 1],
    'operation next320' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_temp_store_current_source_next320'), 1],
    'operation next321' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_cache_spill_current_source_next321'), 1],
    'operation next322' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_cell_size_check_current_source_next322'), 1],
    'operation next323' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_reverse_unordered_selects_current_source_next323'), 1],
    'operation next324' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_automatic_index_current_source_next324'), 1],
    'operation next325' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_case_sensitive_like_current_source_next325'), 1],
    'operation next326' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_count_changes_current_source_next326'), 1],
    'operation next327' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_checkpoint_fullfsync_current_source_next327'), 1],
    'operation next328' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_fullfsync_current_source_next328'), 1],
    'operation next329' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_legacy_file_format_current_source_next329'), 1],
    'operation next330' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_read_uncommitted_current_source_next330'), 1],
    'operation next331' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_reverse_scan_order_current_source_next331'), 1],
    'operation next332' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_defensive_current_source_next332'), 1],
    'operation next333' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_writable_schema_current_source_next333'), 1],
    'operation next334' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_journal_size_limit_current_source_next334'), 1],
    'operation next335' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_threads_current_source_next335'), 1],
    'operation next336' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_optimize_current_source_next336'), 1],
    'operation next337' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_analysis_limit_current_source_next337'), 1],
    'operation next338' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_hard_heap_limit_current_source_next338'), 1],
    'operation next339' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_soft_heap_limit_current_source_next339'), 1],
    'operation next340' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_page_size_current_source_next340'), 1],
    'operation next341' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_max_page_count_current_source_next341'), 1],
    'operation next342' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_locking_proxy_file_current_source_next342'), 1],
    'operation next343' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_page_cache_overflow_current_source_next343'), 1],
    'operation next344' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_scratch_allocator_current_source_next344'), 1],
    'operation next345' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_lookaside_current_source_next345'), 1],
    'operation next346' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_pcache_dirty_limit_current_source_next346'), 1],
    'operation next347' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_mmap_read_limit_current_source_next347'), 1],
    'operation next348' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_sorter_reference_current_source_next348'), 1],
    'operation next349' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_worker_thread_current_source_next349'), 1],
    'operation next350' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_memory_alarm_current_source_next350'), 1],
    'operation next351' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_status_counter_current_source_next351'), 1],
    'operation next352' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_pagecache_size_current_source_next352'), 1],
    'operation next353' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_pagecache_recycle_current_source_next353'), 1],
    'operation next354' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_scratch_spill_current_source_next354'), 1],
    'operation next355' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_lookaside_hit_current_source_next355'), 1],
    'operation next356' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_lookaside_miss_size_current_source_next356'), 1],
    'operation next357' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_pcache_refcount_current_source_next357'), 1],
    'operation next358' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_memory_used_current_source_next358'), 1],
    'operation next359' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_memory_highwater_current_source_next359'), 1],
    'operation next360' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_pagecache_used_current_source_next360'), 1],
    'operation next361' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_pagecache_overflow_current_source_next361'), 1],
    'operation next362' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_scratch_used_current_source_next362'), 1],
    'operation next363' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_scratch_overflow_current_source_next363'), 1],
    'operation next364' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_malloc_size_current_source_next364'), 1],
    'operation next365' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_malloc_count_current_source_next365'), 1],
    'operation next366' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_used_current_source_next366'), 1],
    'operation next367' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_busy_current_source_next367'), 1],
    'operation next368' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_memused_current_source_next368'), 1],
    'operation next369' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_current_source_next369'), 1],
    'operation next370' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_reprepare_current_source_next370'), 1],
    'operation next371' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_run_current_source_next371'), 1],
    'operation next372' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_sort_current_source_next372'), 1],
    'operation next373' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_autoindex_current_source_next373'), 1],
    'operation next374' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_fullscan_current_source_next374'), 1],
    'operation next375' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_vmstep_current_source_next375'), 1],
    'operation next376' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_filter_hit_current_source_next376'), 1],
    'operation next377' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_filter_miss_current_source_next377'), 1],
    'operation next378' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_nsort_current_source_next378'), 1],
    'operation next379' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_nautoindex_current_source_next379'), 1],
    'operation next380' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_nfullscan_current_source_next380'), 1],
    'operation next381' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_expired_current_source_next381'), 1],
    'operation next382' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_readonly_current_source_next382'), 1],
    'operation next383' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_nloop_current_source_next383'), 1],
    'operation next384' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_nvisit_current_source_next384'), 1],
    'operation next385' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_est_current_source_next385'), 1],
    'operation next386' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_name_current_source_next386'), 1],
    'operation next387' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_explain_current_source_next387'), 1],
    'operation next388' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_selectid_current_source_next388'), 1],
    'operation next389' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_parentid_current_source_next389'), 1],
    'operation next390' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_scanstatus_ncycle_current_source_next390'), 1],
    'operation next391' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_vm_halt_current_source_next391'), 1],
    'operation next392' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_vm_reset_current_source_next392'), 1],
    'operation next393' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_bind_parameter_current_source_next393'), 1],
    'operation next394' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_expanded_sql_current_source_next394'), 1],
    'operation next395' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_normalized_sql_current_source_next395'), 1],
    'operation next396' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_sql_text_current_source_next396'), 1],
    'operation next397' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_readonly_schema_current_source_next397'), 1],
    'operation next398' => [static fn (): mixed => $opCount($plan(), 'reopen_reader_for_reader_cache_stmt_busy_state_current_source_next398'), 1],
    'default plan points at next398' => [static fn (): mixed => $plan()['status'], 'pager-master-journal-reader-cache-current-source-next398'],
];

foreach ($cases as $name => [$callback, $expected]) {
    $tests['pager master journal reader cache current source next398 ' . $name] = static function (TestRunner $t) use ($callback, $expected): void {
        $t->same($expected, $callback());
    };
}

$tests['pager master journal reader cache current source next398 missing token rejects'] = static function (TestRunner $t) use ($plan, $cacheEntry, $recovered): void {
    $t->throws(Throwable::class, static fn () => $plan([1 => array_diff_key($cacheEntry('missing', $recovered[1]), ['reader_cache_stmt_busy_state_token' => true])]));
};

return $tests;
