<?php

declare(strict_types=1);

use PortLibs\LibSqlite\SQLitePragmaSchemaCatalog;
use PortLibs\LibSqlite\SQLitePragmaSchemaDataVersion;
use PortLibs\LibSqlite\SQLiteSchemaRecord;

$tests = [];

$valueAt = static function (array $value, string $path): mixed {
    $current = $value;
    foreach (explode('.', $path) as $part) {
        if ($part === 'count') {
            $current = count($current);
            continue;
        }
        $current = is_numeric($part) ? $current[(int) $part] : $current[$part];
    }

    return $current;
};

foreach (range(1, 250) as $variant) {
    $parent = 'pragma_wide_parent_' . $variant;
    $child = 'pragma_wide_child_' . $variant;
    $generated = 'pragma_wide_generated_' . $variant;
    $index = 'pragma_wide_child_' . $variant . '_lookup';
    $partial = 'pragma_wide_generated_' . $variant . '_partial';
    $autoParent = 'sqlite_autoindex_' . $parent . '_1';
    $autoChild = 'sqlite_autoindex_' . $child . '_1';
    $autoGenerated = 'sqlite_autoindex_' . $generated . '_1';

    $catalog = static function () use ($variant, $parent, $child, $generated, $index, $partial, $autoParent, $autoChild, $autoGenerated): SQLitePragmaSchemaCatalog {
        return new SQLitePragmaSchemaCatalog([
            new SQLiteSchemaRecord(
                'table',
                $parent,
                $parent,
                1000 + $variant,
                "CREATE TABLE {$parent}(
                    tenant_id INTEGER NOT NULL,
                    key_name TEXT NOT NULL DEFAULT 'key_{$variant}',
                    region TEXT DEFAULT 'region_{$variant}',
                    PRIMARY KEY(tenant_id, key_name)
                ) WITHOUT ROWID",
                2000 + $variant,
            ),
            new SQLiteSchemaRecord('index', $autoParent, $parent, 3000 + $variant, null, 3000 + $variant),
            new SQLiteSchemaRecord(
                'table',
                $child,
                $child,
                4000 + $variant,
                "CREATE TABLE {$child}(
                    tenant_id INTEGER NOT NULL,
                    key_name TEXT NOT NULL,
                    payload TEXT DEFAULT (json_object('variant',{$variant})),
                    load_policy TEXT DEFAULT 'lazy',
                    UNIQUE(key_name, tenant_id),
                    FOREIGN KEY(tenant_id, key_name) REFERENCES {$parent}(tenant_id, key_name) ON UPDATE CASCADE ON DELETE RESTRICT
                )",
                5000 + $variant,
            ),
            new SQLiteSchemaRecord('index', $autoChild, $child, 6000 + $variant, null, 6000 + $variant),
            new SQLiteSchemaRecord('index', $index, $child, 7000 + $variant, "CREATE INDEX {$index} ON {$child}(load_policy COLLATE nocase DESC, key_name ASC)", 7000 + $variant),
            new SQLiteSchemaRecord(
                'table',
                $generated,
                $generated,
                8000 + $variant,
                "CREATE TABLE {$generated}(
                    id INTEGER PRIMARY KEY,
                    key_name TEXT NOT NULL DEFAULT 'generated_{$variant}',
                    key_fold TEXT GENERATED ALWAYS AS (lower(key_name)) VIRTUAL,
                    key_len INTEGER GENERATED ALWAYS AS (length(key_name)) STORED,
                    UNIQUE(key_name)
                )",
                9000 + $variant,
            ),
            new SQLiteSchemaRecord('index', $autoGenerated, $generated, 10000 + $variant, null, 10000 + $variant),
            new SQLiteSchemaRecord('index', $partial, $generated, 11000 + $variant, "CREATE INDEX {$partial} ON {$generated}((length(key_name)), key_fold DESC COLLATE nocase) WHERE key_name IS NOT NULL", 11000 + $variant),
        ]);
    };

    $tests["real upstream pragma schema wide batch pragma.test 6.2 table-info defaults variant {$variant}"] = static function (TestRunner $t) use ($catalog, $child, $variant): void {
        $rows = $catalog()->execute("PRAGMA table_info({$child})")['rows'];

        $t->same(4, count($rows));
        $t->same('tenant_id', $rows[0]['name']);
        $t->same('INTEGER', $rows[0]['type']);
        $t->same(1, $rows[0]['notnull']);
        $t->same('key_name', $rows[1]['name']);
        $t->same('payload', $rows[2]['name']);
        $t->same("json_object('variant',{$variant})", $rows[2]['dflt_value']);
        $t->same('load_policy', $rows[3]['name']);
        $t->same("'lazy'", $rows[3]['dflt_value']);
    };

    $tests["real upstream pragma schema wide batch pragma4 4.3-4.4 index metadata variant {$variant}"] = static function (TestRunner $t) use ($catalog, $child, $index, $autoChild): void {
        $catalog = $catalog();
        $indexList = $catalog->executeTableValuedPragma("pragma_index_list('{$child}')")['rows'];
        $indexInfo = $catalog->executeTableValuedPragma("pragma_index_xinfo('{$index}')")['rows'];

        $t->same($autoChild, $indexList[0]['name']);
        $t->same(1, $indexList[0]['unique']);
        $t->same('u', $indexList[0]['origin']);
        $t->same($index, $indexList[1]['name']);
        $t->same('c', $indexList[1]['origin']);
        $t->same('load_policy', $indexInfo[0]['name']);
        $t->same('NOCASE', $indexInfo[0]['coll']);
        $t->same(1, $indexInfo[0]['desc']);
        $t->same('key_name', $indexInfo[1]['name']);
        $t->same(0, $indexInfo[1]['desc']);
    };

    $tests["real upstream pragma schema wide batch pragma4 4.5 foreign-key and 6.0 table-list variant {$variant}"] = static function (TestRunner $t) use ($catalog, $parent, $child): void {
        $catalog = $catalog();
        $foreignKeys = $catalog->executeTableValuedPragma("pragma_foreign_key_list('{$child}')")['rows'];
        $tableList = $catalog->executeTableValuedPragma("pragma_table_list('{$child}')")['rows'];

        $t->same(2, count($foreignKeys));
        $t->same($parent, $foreignKeys[0]['table']);
        $t->same('tenant_id', $foreignKeys[0]['from']);
        $t->same('tenant_id', $foreignKeys[0]['to']);
        $t->same('CASCADE', $foreignKeys[0]['on_update']);
        $t->same('RESTRICT', $foreignKeys[0]['on_delete']);
        $t->same('key_name', $foreignKeys[1]['from']);
        $t->same('key_name', $foreignKeys[1]['to']);
        $t->same($child, $tableList[0]['name']);
        $t->same(4, $tableList[0]['ncol']);
    };

    $tests["real upstream pragma schema wide batch generated table-xinfo and expression index variant {$variant}"] = static function (TestRunner $t) use ($catalog, $generated, $partial, $variant): void {
        $catalog = $catalog();
        $xinfo = $catalog->execute("PRAGMA table_xinfo({$generated})")['rows'];
        $indexXinfo = $catalog->execute("PRAGMA index_xinfo({$partial})")['rows'];

        $t->same('id', $xinfo[0]['name']);
        $t->same(1, $xinfo[0]['pk']);
        $t->same('key_name', $xinfo[1]['name']);
        $t->same("'generated_{$variant}'", $xinfo[1]['dflt_value']);
        $t->same('key_fold', $xinfo[2]['name']);
        $t->same(2, $xinfo[2]['hidden']);
        $t->same('key_len', $xinfo[3]['name']);
        $t->same(3, $xinfo[3]['hidden']);
        $t->same(-2, $indexXinfo[0]['cid']);
        $t->same('key_fold', $indexXinfo[1]['name']);
        $t->same('NOCASE', $indexXinfo[1]['coll']);
        $t->same(1, $indexXinfo[1]['desc']);
    };
}

foreach (range(1, 80) as $variant) {
    $tests["real upstream pragma schema wide batch pragma3 data-version external observer variant {$variant}"] = static function (TestRunner $t) use ($variant): void {
        $state = new SQLitePragmaSchemaDataVersion([
            'main' => ['schema_version' => 10 + $variant, 'data_version' => 1, 'change_counter' => 1, 'user_version' => 0],
            'aux' => ['schema_version' => 20 + $variant, 'data_version' => 3, 'change_counter' => 3, 'user_version' => $variant],
        ]);

        $before = $state->execute('PRAGMA main.data_version');
        $ignored = $state->execute('PRAGMA main.data_version = 9000');
        $state->recordLocalCommit('main', 2, 'local_pragma3_commit');
        $local = $state->execute('PRAGMA main.data_version');
        $state->recordExternalCommit('main', 1, 'external_pragma3_commit');
        $external = $state->execute('PRAGMA main.data_version');

        $t->same(1, $before['value']);
        $t->same(false, $ignored['changed']);
        $t->same('read_only_pragma_ignored', $ignored['reason']);
        $t->same(1, $local['value']);
        $t->same(2, $external['value']);
        $t->same(4, $state->headerUpdate('main')['file_change_counter']);
    };

    $tests["real upstream pragma schema wide batch pragma.test 8 schema user rollback variant {$variant}"] = static function (TestRunner $t) use ($variant): void {
        $state = new SQLitePragmaSchemaDataVersion([
            'main' => ['schema_version' => 100 + $variant, 'data_version' => 1, 'change_counter' => 1, 'user_version' => $variant],
            'aux' => ['schema_version' => 200 + $variant, 'data_version' => 1, 'change_counter' => 1, 'user_version' => 10 + $variant],
        ]);

        $state->beginTransaction();
        $state->execute('PRAGMA main.user_version = ' . (300 + $variant));
        $state->execute('PRAGMA aux.schema_version = ' . (400 + $variant));
        $duringMain = $state->execute('PRAGMA user_version')['value'];
        $duringAux = $state->execute('PRAGMA aux.schema_version')['value'];
        $state->rollbackTransaction();

        $t->same(300 + $variant, $duringMain);
        $t->same(400 + $variant, $duringAux);
        $t->same($variant, $state->execute('PRAGMA main.user_version')['value']);
        $t->same(200 + $variant, $state->execute('PRAGMA aux.schema_version')['value']);
    };
}

$tests['real upstream pragma schema wide batch cites source corpus sections'] = static function (TestRunner $t): void {
    $sections = [
        'pragma.test pragma-6.2 table_info/default/pk rows',
        'pragma.test pragma-8.1/8.2 schema_version and user_version',
        'pragma3.test pragma3-100 through pragma3-190 data_version',
        'pragma4.test pragma4-4.3 through pragma4-4.6 table-valued index and foreign-key pragmas',
        'pragma4.test pragma4-6.0 table_list joins',
    ];

    $t->same(5, count($sections));
    $t->same(true, str_contains($sections[0], 'pragma.test'));
    $t->same(true, str_contains($sections[2], 'pragma3.test'));
    $t->same(true, str_contains($sections[3], 'pragma4.test'));
};

return $tests;
