<?php

declare(strict_types=1);

use PortLibs\Pandoc\AstNode;
use PortLibs\Pandoc\PandocConverter;

require __DIR__ . '/bootstrap.php';

ini_set('memory_limit', getenv('PANDOC_SAMPLE_REPORT_MEMORY_LIMIT') ?: '1024M');

$repoRoot = dirname(__DIR__);
$manifestPath = null;
$outputDir = $repoRoot . '/.upstream-cache/pandoc-reader-actual-output-report';
$pandocBin = getenv('PANDOC_BIN') ?: 'pandoc';
$limit = null;

foreach (array_slice($argv, 1) as $argument) {
    if ($argument === '--help' || $argument === '-h') {
        fwrite(STDOUT, <<<'TXT'
Usage: php tools/pandoc-reader-actual-output-report.php --manifest=PATH [--output-dir=PATH] [--pandoc-bin=PATH] [--limit=N]

Builds an HTML report containing the actual native/HTML output generated by
the local PHP Pandoc port and by an installed pandoc executable.

TXT);
        exit(0);
    }

    if (str_starts_with($argument, '--manifest=')) {
        $manifestPath = normalizePath($repoRoot, substr($argument, strlen('--manifest=')));
        continue;
    }

    if (str_starts_with($argument, '--output-dir=')) {
        $outputDir = normalizePath($repoRoot, substr($argument, strlen('--output-dir=')));
        continue;
    }

    if (str_starts_with($argument, '--pandoc-bin=')) {
        $pandocBin = substr($argument, strlen('--pandoc-bin='));
        if ($pandocBin === '') {
            fwrite(STDERR, "--pandoc-bin must not be empty\n");
            exit(2);
        }
        continue;
    }

    if (str_starts_with($argument, '--limit=')) {
        $rawLimit = substr($argument, strlen('--limit='));
        if (!ctype_digit($rawLimit) || (int) $rawLimit < 1) {
            fwrite(STDERR, "--limit must be a positive integer\n");
            exit(2);
        }
        $limit = (int) $rawLimit;
        continue;
    }

    fwrite(STDERR, "Unknown argument: {$argument}\n");
    exit(2);
}

if ($manifestPath === null) {
    fwrite(STDERR, "--manifest is required\n");
    exit(2);
}

$pandoc = resolveExecutable($pandocBin);
if ($pandoc === null) {
    fwrite(STDERR, "pandoc executable not found: {$pandocBin}\n");
    exit(1);
}

$report = buildActualOutputReport($repoRoot, $pandoc, $manifestPath, $outputDir, $limit);
writeFile($outputDir . '/index.html', renderReport($report));
writeFile(
    $outputDir . '/report.json',
    json_encode($report, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n"
);

fwrite(STDOUT, "Wrote {$outputDir}/index.html\n");
fwrite(STDOUT, "Wrote {$outputDir}/report.json\n");
fwrite(STDOUT, summaryLine($report) . "\n");

/**
 * @return array<string, mixed>
 */
function buildActualOutputReport(
    string $repoRoot,
    string $pandoc,
    string $manifestPath,
    string $outputDir,
    ?int $limit
): array {
    if (!is_file($manifestPath)) {
        throw new RuntimeException("Manifest not found: {$manifestPath}");
    }
    $manifest = json_decode((string) file_get_contents($manifestPath), true, 512, JSON_THROW_ON_ERROR);
    if (!is_array($manifest) || !is_array($manifest['entries'] ?? null)) {
        throw new RuntimeException("Manifest must contain an entries array: {$manifestPath}");
    }

    ensureDirectory($outputDir . '/outputs');
    $entries = $manifest['entries'];
    if ($limit !== null) {
        $entries = array_slice($entries, 0, $limit);
    }

    $cases = [];
    foreach ($entries as $entry) {
        if (!is_array($entry)) {
            continue;
        }
        $cases[] = runCase($repoRoot, $pandoc, $outputDir, $entry);
    }

    return [
        'schemaVersion' => 1,
        'tool' => 'pandoc-reader-actual-output-report',
        'generatedAt' => gmdate('c'),
        'repoRoot' => $repoRoot,
        'manifestPath' => $manifestPath,
        'outputDir' => $outputDir,
        'pandocExecutable' => $pandoc,
        'pandocVersion' => pandocVersion($pandoc),
        'title' => (string) ($manifest['title'] ?? 'Pandoc reader actual output report'),
        'description' => (string) ($manifest['description'] ?? ''),
        'caseCount' => count($cases),
        'localNativeOkCount' => count(array_filter($cases, static fn (array $case): bool => $case['localNative']['ok'] === true)),
        'pandocNativeOkCount' => count(array_filter($cases, static fn (array $case): bool => $case['pandocNative']['ok'] === true)),
        'localHtmlOkCount' => count(array_filter($cases, static fn (array $case): bool => $case['localHtml']['ok'] === true)),
        'pandocHtmlOkCount' => count(array_filter($cases, static fn (array $case): bool => $case['pandocHtml']['ok'] === true)),
        'localWordPressOkCount' => count(array_filter($cases, static fn (array $case): bool => $case['localWordPress']['ok'] === true)),
        'cases' => $cases,
    ];
}

/**
 * @param array<string, mixed> $entry
 * @return array<string, mixed>
 */
function runCase(string $repoRoot, string $pandoc, string $outputDir, array $entry): array
{
    $format = (string) ($entry['format'] ?? '');
    $pandocFormat = (string) ($entry['pandocFormat'] ?? $format);
    $readerOptions = is_array($entry['readerOptions'] ?? null) ? $entry['readerOptions'] : [];
    $sourcePath = normalizePath($repoRoot, (string) ($entry['path'] ?? ''));
    $id = slug((string) ($entry['id'] ?? pathinfo($sourcePath, PATHINFO_FILENAME)));
    $caseDir = $outputDir . '/outputs/' . $id;
    ensureDirectory($caseDir);

    $case = [
        'id' => $id,
        'label' => (string) ($entry['id'] ?? $id),
        'format' => $format,
        'pandocFormat' => $pandocFormat,
        'readerOptions' => $readerOptions,
        'sourceFile' => relativePath($repoRoot, $sourcePath),
        'sourceUrl' => is_string($entry['sourceUrl'] ?? null) ? $entry['sourceUrl'] : null,
        'description' => (string) ($entry['description'] ?? ''),
        'features' => is_array($entry['features'] ?? null) ? array_values(array_map('strval', $entry['features'])) : [],
        'sourceBytes' => is_file($sourcePath) ? filesize($sourcePath) : null,
        'sourceSha256' => is_file($sourcePath) ? hash_file('sha256', $sourcePath) : null,
        'expectedSha256' => is_string($entry['sha256'] ?? null) ? $entry['sha256'] : null,
        'outputs' => [],
        'localParse' => ['ok' => false, 'error' => null],
        'localNative' => ['ok' => false, 'path' => null, 'error' => null],
        'pandocNative' => ['ok' => false, 'path' => null, 'error' => null],
        'localHtml' => ['ok' => false, 'path' => null, 'error' => null],
        'pandocHtml' => ['ok' => false, 'path' => null, 'error' => null],
        'localWordPress' => ['ok' => false, 'path' => null, 'error' => null],
    ];

    $document = null;
    if (!is_file($sourcePath)) {
        $case['localParse']['error'] = "Source file not found: {$sourcePath}";
    } else {
        try {
            $document = PandocConverter::readFile($sourcePath, $format, $readerOptions);
            $case['localParse'] = ['ok' => true, 'error' => null];
        } catch (Throwable $throwable) {
            $case['localParse']['error'] = exceptionSummary($throwable);
        }
    }

    if ($document instanceof AstNode) {
        $case['localNative'] = writeLocalOutput(
            $caseDir . '/local.native.txt',
            static fn (): string => PandocConverter::write($document, 'native', ['standalone' => true])
        );
        $case['localHtml'] = writeLocalOutput(
            $caseDir . '/local.html',
            static fn (): string => PandocConverter::write($document, 'html', ['writerHTMLMathMethod' => 'mathml'])
        );
        $case['localWordPress'] = writeLocalOutput(
            $caseDir . '/local-wordpress.html',
            static fn (): string => PandocConverter::write($document, 'wordpress', ['writerHTMLMathMethod' => 'mathml'])
        );
    }

    if (is_file($sourcePath)) {
        $case['pandocNative'] = writePandocOutput(
            $pandoc,
            ['-f', $pandocFormat, '-t', 'native', $sourcePath],
            $caseDir . '/pandoc.native.txt'
        );
        $case['pandocHtml'] = writePandocOutput(
            $pandoc,
            ['-f', $pandocFormat, '-t', 'html', '--standalone', $sourcePath],
            $caseDir . '/pandoc.html'
        );
    }

    foreach (['localNative', 'pandocNative', 'localHtml', 'pandocHtml', 'localWordPress'] as $key) {
        $path = $case[$key]['path'];
        if (is_string($path)) {
            $case[$key]['href'] = relativePath($outputDir, $path);
            $case['outputs'][$key] = [
                'path' => relativePath($outputDir, $path),
                'bytes' => filesize($path),
                'sha256' => hash_file('sha256', $path),
            ];
        }
    }

    writeFile($caseDir . '/case.json', json_encode($case, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n");

    return $case;
}

/**
 * @return array{ok: bool, path: ?string, error: ?string}
 */
function writeLocalOutput(string $path, callable $callback): array
{
    try {
        $output = $callback();
        writeFile($path, $output);

        return ['ok' => true, 'path' => $path, 'error' => null];
    } catch (Throwable $throwable) {
        writeFile($path . '.error.txt', exceptionSummary($throwable) . "\n");

        return ['ok' => false, 'path' => $path . '.error.txt', 'error' => exceptionSummary($throwable)];
    }
}

/**
 * @param list<string> $arguments
 * @return array{ok: bool, path: ?string, error: ?string}
 */
function writePandocOutput(string $pandoc, array $arguments, string $path): array
{
    $result = runProcess(array_merge([$pandoc], $arguments));
    $body = $result['stdout'];
    if ($result['stderr'] !== '') {
        writeFile($path . '.stderr.txt', $result['stderr']);
    }
    if ($result['exitCode'] === 0) {
        writeFile($path, $body);

        return ['ok' => true, 'path' => $path, 'error' => $result['stderr'] === '' ? null : $result['stderr']];
    }

    $message = trim($result['stderr'] !== '' ? $result['stderr'] : $result['stdout']);
    if ($message === '') {
        $message = 'pandoc exited with status ' . $result['exitCode'];
    }
    writeFile($path . '.error.txt', $message . "\n");

    return ['ok' => false, 'path' => $path . '.error.txt', 'error' => $message];
}

/**
 * @param list<string> $command
 * @return array{stdout: string, stderr: string, exitCode: int}
 */
function runProcess(array $command): array
{
    $descriptors = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];
    $process = proc_open(escapedCommand($command), $descriptors, $pipes);
    if (!is_resource($process)) {
        return ['stdout' => '', 'stderr' => 'proc_open failed', 'exitCode' => 127];
    }

    fclose($pipes[0]);
    $stdout = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[1]);
    fclose($pipes[2]);
    $exitCode = proc_close($process);

    return [
        'stdout' => is_string($stdout) ? $stdout : '',
        'stderr' => is_string($stderr) ? $stderr : '',
        'exitCode' => is_int($exitCode) ? $exitCode : 1,
    ];
}

/**
 * @param list<string> $command
 */
function escapedCommand(array $command): string
{
    return implode(' ', array_map('escapeshellarg', $command));
}

function renderReport(array $report): string
{
    $rows = [];
    foreach ($report['cases'] as $case) {
        $rows[] = renderCase($case);
    }

    return '<!doctype html>'
        . '<html lang="en"><head><meta charset="utf-8">'
        . '<meta name="viewport" content="width=device-width, initial-scale=1">'
        . '<title>' . h((string) $report['title']) . '</title>'
        . '<style>'
        . 'body{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;background:#f7f7f4;color:#20201d;}'
        . 'header{padding:24px 28px 16px;border-bottom:1px solid #d8d6cf;background:#fff;}'
        . 'h1{font-size:24px;line-height:1.2;margin:0 0 8px;}'
        . 'h2{font-size:18px;margin:0;}'
        . 'h3{font-size:15px;margin:0 0 8px;}'
        . 'main{padding:20px 28px 36px;}'
        . '.summary{display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;}'
        . '.stat{border:1px solid #d8d6cf;background:#fff;padding:10px 12px;border-radius:6px;min-width:140px;}'
        . '.stat strong{display:block;font-size:20px;}'
        . '.case{border:1px solid #d8d6cf;background:#fff;border-radius:6px;margin:0 0 20px;overflow:hidden;}'
        . '.case-header{padding:14px 16px;border-bottom:1px solid #e4e2dc;}'
        . '.meta{display:flex;gap:10px;flex-wrap:wrap;font-size:12px;color:#5f5c55;margin-top:8px;}'
        . '.pill{border:1px solid #d8d6cf;background:#fafaf8;border-radius:99px;padding:2px 8px;}'
        . '.links{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px;font-size:13px;}'
        . 'a{color:#135f8d;text-decoration:none;}a:hover{text-decoration:underline;}'
        . 'details{border-top:1px solid #ebe9e3;}'
        . 'summary{cursor:pointer;padding:10px 16px;font-weight:650;}'
        . '.compare{display:grid;grid-template-columns:1fr 1fr;gap:0;border-top:1px solid #ebe9e3;}'
        . '.panel{min-width:0;border-right:1px solid #ebe9e3;}'
        . '.panel:last-child{border-right:0;}'
        . '.panel-title{font-size:12px;font-weight:700;color:#5f5c55;background:#fafaf8;border-bottom:1px solid #ebe9e3;padding:8px 10px;}'
        . 'pre{margin:0;padding:10px;max-height:420px;overflow:auto;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#fff;}'
        . 'iframe{display:block;width:100%;height:420px;border:0;background:#fff;}'
        . '.error{color:#9f1d1d;background:#fff6f6;}'
        . '.ok{color:#26723d}.bad{color:#9f1d1d}'
        . '@media (max-width: 900px){.compare{grid-template-columns:1fr}.panel{border-right:0;border-bottom:1px solid #ebe9e3}.panel:last-child{border-bottom:0}}'
        . '</style></head><body><header>'
        . '<h1>' . h((string) $report['title']) . '</h1>'
        . '<div>' . h((string) $report['description']) . '</div>'
        . '<div class="meta"><span>Generated ' . h((string) $report['generatedAt']) . '</span><span>Pandoc ' . h((string) $report['pandocVersion']) . '</span></div>'
        . '<div class="summary">'
        . summaryStat('Cases', (string) $report['caseCount'])
        . summaryStat('Local native', okCount($report, 'localNativeOkCount'))
        . summaryStat('Pandoc native', okCount($report, 'pandocNativeOkCount'))
        . summaryStat('Local HTML', okCount($report, 'localHtmlOkCount'))
        . summaryStat('Pandoc HTML', okCount($report, 'pandocHtmlOkCount'))
        . summaryStat('WordPress', okCount($report, 'localWordPressOkCount'))
        . '</div></header><main>'
        . implode('', $rows)
        . '</main></body></html>';
}

function summaryStat(string $label, string $value): string
{
    return '<div class="stat"><strong>' . h($value) . '</strong>' . h($label) . '</div>';
}

function okCount(array $report, string $key): string
{
    return (string) ($report[$key] ?? 0) . '/' . (string) ($report['caseCount'] ?? 0);
}

/**
 * @param array<string, mixed> $case
 */
function renderCase(array $case): string
{
    $links = [];
    foreach ([
        'localNative' => 'local native',
        'pandocNative' => 'pandoc native',
        'localHtml' => 'local HTML',
        'pandocHtml' => 'pandoc HTML',
        'localWordPress' => 'local WordPress',
    ] as $key => $label) {
        $output = $case['outputs'][$key] ?? null;
        if (is_array($output) && is_string($output['path'] ?? null)) {
            $links[] = '<a href="' . h(urlPath((string) $output['path'])) . '">' . h($label) . '</a>';
        }
    }

    $features = array_map(static fn (string $feature): string => '<span class="pill">' . h($feature) . '</span>', $case['features'] ?? []);
    $sourceUrl = is_string($case['sourceUrl'] ?? null)
        ? '<a href="' . h((string) $case['sourceUrl']) . '">' . h((string) $case['sourceUrl']) . '</a>'
        : h((string) $case['sourceFile']);

    return '<section class="case">'
        . '<div class="case-header">'
        . '<h2>' . h((string) $case['label']) . '</h2>'
        . '<div class="meta">'
        . '<span class="pill">' . h((string) $case['format']) . '</span>'
        . '<span class="pill">pandoc -f ' . h((string) $case['pandocFormat']) . '</span>'
        . '<span>' . h(number_format((int) ($case['sourceBytes'] ?? 0))) . ' bytes</span>'
        . '<span>source: ' . $sourceUrl . '</span>'
        . '</div>'
        . ($features === [] ? '' : '<div class="meta">' . implode('', $features) . '</div>')
        . '<div class="links">' . implode('', $links) . '</div>'
        . '</div>'
        . renderNativeComparison($case)
        . renderHtmlComparison($case)
        . renderWordPressOutput($case)
        . '</section>';
}

/**
 * @param array<string, mixed> $case
 */
function renderNativeComparison(array $case): string
{
    return '<details open><summary>Native AST output</summary>'
        . '<div class="compare">'
        . renderTextPanel('Local port native', $case['localNative'])
        . renderTextPanel('Pandoc native', $case['pandocNative'])
        . '</div></details>';
}

/**
 * @param array<string, mixed> $case
 */
function renderHtmlComparison(array $case): string
{
    return '<details><summary>Rendered HTML output</summary>'
        . '<div class="compare">'
        . renderFramePanel('Local port HTML', $case['localHtml'])
        . renderFramePanel('Pandoc HTML', $case['pandocHtml'])
        . '</div></details>';
}

/**
 * @param array<string, mixed> $case
 */
function renderWordPressOutput(array $case): string
{
    return '<details><summary>WordPress block output from local port</summary>'
        . '<div class="compare">'
        . renderTextPanel('Local WordPress blocks', $case['localWordPress'])
        . renderFramePanel('Rendered WordPress HTML/comments', $case['localWordPress'])
        . '</div></details>';
}

/**
 * @param array{ok: bool, path: ?string, href?: string, error: ?string} $result
 */
function renderTextPanel(string $title, array $result): string
{
    $class = $result['ok'] ? 'ok' : 'bad';
    $body = is_string($result['path'])
        ? previewFile($result['path'])
        : (string) ($result['error'] ?? 'No output file');

    return '<div class="panel"><div class="panel-title ' . $class . '">' . h($title) . '</div><pre' . ($result['ok'] ? '' : ' class="error"') . '>' . h($body) . '</pre></div>';
}

/**
 * @param array{ok: bool, path: ?string, href?: string, error: ?string} $result
 */
function renderFramePanel(string $title, array $result): string
{
    $class = $result['ok'] ? 'ok' : 'bad';
    if (!$result['ok'] || !is_string($result['path'])) {
        $body = is_string($result['path'])
            ? previewFile($result['path'])
            : (string) ($result['error'] ?? 'No output file');

        return '<div class="panel"><div class="panel-title ' . $class . '">' . h($title) . '</div><pre class="error">' . h($body) . '</pre></div>';
    }

    $href = is_string($result['href'] ?? null) ? (string) $result['href'] : basename($result['path']);

    return '<div class="panel"><div class="panel-title ok">' . h($title) . '</div><iframe src="' . h(urlPath($href)) . '"></iframe></div>';
}

function previewFile(string $path): string
{
    $bytes = file_get_contents($path, false, null, 0, 30000);
    if (!is_string($bytes)) {
        return 'Unable to read output preview.';
    }
    if (is_file($path) && filesize($path) > strlen($bytes)) {
        return $bytes . "\n\n[preview truncated; open the linked output file for the full content]";
    }

    return $bytes;
}

function writeFile(string $path, string $bytes): void
{
    ensureDirectory(dirname($path));
    if (file_put_contents($path, $bytes) === false) {
        throw new RuntimeException("Unable to write {$path}");
    }
}

function ensureDirectory(string $path): void
{
    if (!is_dir($path) && !mkdir($path, 0777, true) && !is_dir($path)) {
        throw new RuntimeException("Unable to create directory {$path}");
    }
}

function normalizePath(string $repoRoot, string $path): string
{
    if ($path === '') {
        return $repoRoot;
    }
    if ($path[0] === '/') {
        return $path;
    }

    return $repoRoot . '/' . $path;
}

function relativePath(string $base, string $path): string
{
    $base = rtrim($base, '/') . '/';
    if (str_starts_with($path, $base)) {
        return substr($path, strlen($base));
    }

    return $path;
}

function resolveExecutable(string $candidate): ?string
{
    if (str_contains($candidate, '/') && is_executable($candidate)) {
        return $candidate;
    }
    $result = runProcess(['/usr/bin/env', 'sh', '-lc', 'command -v ' . escapeshellarg($candidate)]);
    $path = trim($result['stdout']);
    if ($result['exitCode'] === 0 && $path !== '') {
        return $path;
    }

    return null;
}

function pandocVersion(string $pandoc): string
{
    $result = runProcess([$pandoc, '--version']);
    if ($result['exitCode'] !== 0) {
        return 'unknown';
    }
    $lines = preg_split('/\R/', trim($result['stdout']));

    return is_array($lines) && isset($lines[0]) ? $lines[0] : 'unknown';
}

function exceptionSummary(Throwable $throwable): string
{
    return get_class($throwable) . ': ' . $throwable->getMessage()
        . ' at ' . $throwable->getFile() . ':' . $throwable->getLine();
}

function summaryLine(array $report): string
{
    return 'Cases: ' . $report['caseCount']
        . '; local native: ' . $report['localNativeOkCount'] . '/' . $report['caseCount']
        . '; pandoc native: ' . $report['pandocNativeOkCount'] . '/' . $report['caseCount']
        . '; local HTML: ' . $report['localHtmlOkCount'] . '/' . $report['caseCount']
        . '; pandoc HTML: ' . $report['pandocHtmlOkCount'] . '/' . $report['caseCount']
        . '; local WordPress: ' . $report['localWordPressOkCount'] . '/' . $report['caseCount'];
}

function slug(string $value): string
{
    $slug = strtolower((string) preg_replace('/[^a-zA-Z0-9._-]+/', '-', trim($value)));
    $slug = trim($slug, '-._');

    return $slug === '' ? 'case' : $slug;
}

function h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function urlPath(string $path): string
{
    return implode('/', array_map('rawurlencode', explode('/', $path)));
}
